### ISSUE TITLE
Dublicating kerbal when leaving external seat

### ISSUE THREAD

**Issue by Sladernimo** [LunaMultiplayer/LunaMultiplayer#100]
Dublicating kerbal when leaving external seat.
(No dublicating on enter seat but on leave seat now ...)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: WIN7 SP1 x64

------------------------------------------------------------------------------

KSPVersion: 1.4.1.2089

------------------------------------------------------------------------------

LMP version: 0.3.27 Debug

------------------------------------------------------------------------------

MODS (add link to download them): No mods used. Just main game + expansion

------------------------------------------------------------------------------

Expected behaviour: Leave seat without dublicating kerbal.

------------------------------------------------------------------------------

Current behaviour: On leaving the seat kerbal gets dublicated (1 remains in seat, 1 is next to the seat)

------------------------------------------------------------------------------

Steps to reproduce: Use Aeris 3A with external seat on top. Try to enter and to leave the seat.

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1815559/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1815563/output_log.txt)
[lmpserver 2018-03-15 14-24-44.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1815565/lmpserver.2018-03-15.14-24-44.log)
[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1815566/Universe.zip)

**Comment by gavazquez** [comment]
Will fix it for next release

**Comment by garemoko** [comment]
I'm seeing an issue where when a kerbal goes on EVA and re-boards, they get duplicated left in space, but the one left in space is a weird expanded monster. Is that the same bug as this or should I open another issue?

**Comment by Sladernimo** [comment]
I can confirm that bug.
Spaghetti kerbal spawns after getting back into cockpit.
It takes 10 - 30 seconds for spaghetti kerbal to spawn.
Can also happen when landed.
Spawned spaghetti kerbal can destroy vessels nearby when spawning very close to a vessel or even inside one.
Spaghetti kerbal is not controllable and it has usually the chute opened which is looking transparent and the kerbal obviously looks like spaghetti ;)

Maybe those bugs collerate but I don't think that this is excactly the same bug, cause there are some differences:
When leaving external seat, kerbal clone appears inside the seat almost instantly, kerbal clone is controllable and it never becomes a spaghetti monster :)
