### ISSUE TITLE
Vessels are destroyed immediately upon launch, before the game renders anything

### ISSUE THREAD

**Issue by Dan-Shields** [LunaMultiplayer/LunaMultiplayer#101]
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1816638/output_log.txt)
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1816643/KSP.log)

[config and universe](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1816649/lmp.zip)

OS: 
------------------------------------------------------------------------------
Windows 10 on client, Debian Stretch on the server

KSPVersion: 
------------------------------------------------------------------------------
1.4.1

LMP version (include the build number if you are using a nighly build): 
------------------------------------------------------------------------------

0.3.28

MODS (add link to download them): 
------------------------------------------------------------------------------
Tried with and without the Making History expansion

Bug report
------------------------------------------------------------------------------
Launching/switching to a vessel should work, but on the client the vessel is immediately destroyed and the view changes to either the space centre or an asteroid, with the message "the vessel you were spectating was removed".

Tried with launching a vessel from runway/launchpad and also switching to a vessel already in orbit.

The destroyed vessel is resent to the client some time after switching back to the space centre, and you can try switching to it again, suggesting this is a client side bug only.

**Comment by gavazquez** [comment]
Have you tried CLEANING the universe and mod files? Install the server in a totally new folder

**Comment by Dan-Shields** [comment]
Although this was an upgrade from 0.2.22, I renamed the Universe folder, and deleted everything else before installing the new server files, meaning it was basically clean. I also deleted my LMP game save on my client.

**Comment by Dan-Shields** [comment]
I just extracted the server files to my desktop machine and ran a totally fresh install, issue still persists.

**Comment by gavazquez** [comment]
Are you playing without mods?

**Comment by Dan-Shields** [comment]
Yeah, I have tried with and without the expansion though

**Comment by Dan-Shields** [comment]
Disabling mod control seems to be a temporary work around. It's strange though, Squad and LunaMultiplayer are the only two folders in my GameData

**Comment by gavazquez** [comment]
Ok fixed it. Going to do a monkey patch release
