### ISSUE TITLE
Not getting the menu

### ISSUE THREAD

**Issue by zonta** [LunaMultiplayer/LunaMultiplayer#112]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10 64 bits

------------------------------------------------------------------------------

KSPVersion: 1.4.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): Luna Multi Player 0.3.28

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: Getting a menu

------------------------------------------------------------------------------

Current behaviour: Not getting the menu

------------------------------------------------------------------------------

Steps to reproduce: I don't know I start my game and I don't get the menu in order to connect

**Comment by gavazquez** [comment]
Fixed in nightly and for next release
