### ISSUE TITLE
Playername is settable after handshake with server

### ISSUE THREAD

**Issue by 4669842** [LunaMultiplayer/LunaMultiplayer#114]
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS:  Windows

------------------------------------------------------------------------------

KSPVersion:  1.4.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

0.3.31.121

MODS (add link to download them): 
N/A

Expected behaviour: 

Anything entered into namebox should be reverted to the entry submitted during handshake OR textbox grayed out to stop tinkering

Current behaviour: 

Playername can be changed after handshake exposing the risk of forging authentication 

Steps to reproduce:  

1. Connect to any server
2. During login after successful handshake and vessel and kerbal manifest download, quickly edit player name entry to anything else.
3. Play as anyone without requiring valid handshakes.

**Comment by gavazquez** [comment]
Fixed
