### ISSUE TITLE
Server randomly deleting crafts 

### ISSUE THREAD

**Issue by savageduckerino** [LunaMultiplayer/LunaMultiplayer#116]
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 8.1 for server, Windows 10 for client
------------------------------------------------------------------------------

KSPVersion: 1.4.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.3.31.134

------------------------------------------------------------------------------

MODS (add link to download them): Moon Village Capsule Corp: https://forum.kerbalspaceprogram.com/index.php?/topic/171635-13-capsule-corp-exploration-moon-village/

CommunityCategory Kit and CommunityResourcePack
https://github.com/BobPalmer/CommunityCategoryKit/tree/master/FOR_RELEASE
https://github.com/BobPalmer/CommunityResourcePack

Extraplanatery Launchpads
http://taniwha.org/~bill/Extraplanetary_Launchpads_v5.9.0.zip

Firespitter
https://github.com/snjo/Firespitter/releases

JX2Antenna
https://spacedock.info/mod/1107/JX2Antenna

KAS and KIS
https://forum.kerbalspaceprogram.com/index.php?/topic/142594-14-kerbal-attachment-system-kas-v064/
https://forum.kerbalspaceprogram.com/index.php?/topic/149848-14-kerbal-inventory-system-kis-v110/

SpaceX Launchers Pack
https://forum.kerbalspaceprogram.com/index.php?/topic/71323-131-launchers-pack-spacex-pack-v5-released-august-25/

Launch Towers Pack
https://forum.kerbalspaceprogram.com/index.php?/topic/128370-13-launch-towers-pack/

Kerbal Planetary Base Systems
https://forum.kerbalspaceprogram.com/index.php?/topic/133606-13114x-kerbal-planetary-base-systems-v16-20-march-2018/

TAC Life Support
https://forum.kerbalspaceprogram.com/index.php?/topic/146465-141-tac-life-support-v0139-release-17th-march-2018/

Snacks! 
https://forum.kerbalspaceprogram.com/index.php?/topic/149604-141-snacks-friendly-simplified-life-support/

SpaceX ITS
https://forum.kerbalspaceprogram.com/index.php?/topic/150729-12-spacex-interplanetary-transportation-system-by-thrimm-aerospace-091/

Vapor Vents
https://forum.kerbalspaceprogram.com/index.php?/topic/146847-131-vapor-vent-released/

Tweakscale
https://www.curseforge.com/kerbal/ksp-mods/tweakscale

Server stuff:
[Debug.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1836841/Debug.zip)

output_log:
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1836846/output_log.txt)

------------------------------------------------------------------------------

Expected behaviour: Server to run without deleting all vessels for no reason or anyone doing it.

------------------------------------------------------------------------------

Current behaviour: Server deleting all vessels randomly.

------------------------------------------------------------------------------

Steps to reproduce: Run the build version as server I listed, run client same version, place vessels, fly around for a bit and should randomly delete one minute or another.

**Comment by gavazquez** [comment]
The server is not the one that deletes the vessels. The vessels are deleted **be the people**. You can see on the logs who removed them

Ex:
![image](https://user-images.githubusercontent.com/12727761/37762468-a6a547ac-2dbc-11e8-8d91-f4b5430d94ef.png)

**Comment by gavazquez** [comment]
Will check anyway
