### ISSUE TITLE
Socket bound to 0.0.0.0

### ISSUE THREAD

**Issue by Wunderwaffle11** [LunaMultiplayer/LunaMultiplayer#118]
Having an issue where a server I've created decides that it is free and designates its IP as 0.0.0.0. Obviously this does not work. I'm sure this is a simple thing that I've done wrong, but how do I fix it?
![image](https://user-images.githubusercontent.com/17326553/37868632-c53ec21a-2fa1-11e8-9022-fbca5e948239.png)

**Comment by gavazquez** [comment]
Normal and expected behaviours. Read the wiki documentation and lidgren documentation
