### ISSUE TITLE
Station at Duna glitched out/Scienceprogress reset after Serverrestart

### ISSUE THREAD

**Issue by Alldemize** [LunaMultiplayer/LunaMultiplayer#126]
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.4.2

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.7.38 (but i updated in hope of bug resolve)

------------------------------------------------------------------------------

MODS (add link to download them): Mechjeb, Docking Port Aligment Indicator

------------------------------------------------------------------------------

Expected behaviour: ?

------------------------------------------------------------------------------

Current behaviour: 

Hi its my first bugreport or anything like this so sorry if i miss something.

First Bug ist the Duna Station glitched out:

i play with a friend on a local hosted server and he tried do dock with our Station at Duna (3 or 4 connected modules) with his Lander for the first time. As soon as he got to 1km~ distance he got major fps drops and his ksp crashed. Today i tried it and only got the major fps drops but no crash so i switched over to the station to check if i get the same fps drops there. The only thing i see from my station is a command pot with no kerbals or anything interactable for 10sec then the camera glitches out and its like you are on max warp (only the camera its actualy on standard speed)

Second Bug Disapearing Science:

I flew to EVE and did some science in high orbit returned researched the drone for 550 science. Build some relays launched them to kerbin and Duna. Logged off, closed the Server. Next day i boot everything up and the science progress is like the day before when i started but my points are the same as yesterday when i was finished. I had enough points to the research again because otherwise my relays would have a problem. Played for a while closed everything and started the next day with the same problem again Science Progress gone and points gone too. I dont know if i can do the science agaian where i got the points but i think it will be done already.

------------------------------------------------------------------------------

Steps to reproduce: 

[ksp bug.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1912168/ksp.bug.zip)

**Comment by gavazquez** [comment]
Both should work in latest nightly version
