### ISSUE TITLE
Outer planets mod malfunctioning

### ISSUE THREAD

**Issue by mrkoendb** [LunaMultiplayer/LunaMultiplayer#127]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"

[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1913283/output_log.txt)
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1913278/KSP.log)
[lmpserver 2018-04-15 21-25-10.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1913279/lmpserver.2018-04-15.21-25-10.log)

(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS:  Windows 10 (x64)

------------------------------------------------------------------------------

KSPVersion: 1.4.2

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build):  0.6.37

------------------------------------------------------------------------------

MODS (add link to download them): 
OPM 2.2.1 (https://github.com/Galileo88/OPM_Galileo/releases)
Kopernicus 1.4.2-1 (https://github.com/Kopernicus/Kopernicus/releases/download/release-1.4.2-1/Kopernicus-1.4.2-1.zip)
Module manager 3.0.6 (included in Kopernicus package)

------------------------------------------------------------------------------

Expected behaviour: 
Added planets to the game in the solar system.

------------------------------------------------------------------------------

Current behaviour: 
Ships randomly decelerating from orbit without any player interaction, planets are present however

------------------------------------------------------------------------------

Steps to reproduce: 
Get anything into any orbit and give it a few minutes

**Comment by Sladernimo** [comment]
Hi mrkoendb, thanks for your report.
Are you sure the bug only occures when using the mentioned mods?
Because fixing mod issues will be a thing that we will maybe achieve after lmp is final.
@gavazquez or what do you mean?

**Comment by gavazquez** [comment]
@Sladernimo told him to report it to have a track of it but yes, I agree we should focus on LMP bugs first
