### ISSUE TITLE
Changing control unit before undock

### ISSUE THREAD

**Issue by Sickonce** [LunaMultiplayer/LunaMultiplayer#131]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1959291/KSP.log)
[Lander3c.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1959296/Lander3c.zip)

OS: 
Windows 10.0 x64 Pro (compilation 16299)
------------------------------------------------------------------------------

KSPVersion: 
1.4.3 + Expansion 1.4.3 (v1.2)
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.7.41.398
------------------------------------------------------------------------------

MODS (add link to download them): 
https://www.curseforge.com/kerbal/ksp-mods/mechjeb/download
------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 
Duplicate ship while undock.
------------------------------------------------------------------------------

Steps to reproduce: 
I made two part ship (with docking port connections) and send it to stable orbit. Ship in atachment.

First one is Kerbal controlled (SHIP), and second one CPU controlled(HUB). Interpolation OFF, no warps and time sync between steps.
1. Undock SHIP*
2. Set "Control from here" on SHIP Docking port
3. Dock again to HUB
4. Change "Control from here" to HUB CPU - we want control HUB after undock
5. Undock HUB from SHIP

*Sometimes when I undocked from HUB and try fast switch to HUB by [, it is marked as controlled by other player on server (not me).

Both ships seems to be duplicated. Massive explosion after that.

**Comment by gavazquez** [comment]
Hi @Sickonce Thanks for the bug report very descriptive! It was very easy to reproduce. I uploaded a fix to nightly so it will be nice if you can test it aswell. In my case I didn't got any more epxlosion.

**Comment by Sickonce** [comment]
@gavazquez: Yep, no more explosions.
