### ISSUE TITLE
Asteroid, orbit around Sun

### ISSUE THREAD

**Issue by Sickonce** [LunaMultiplayer/LunaMultiplayer#133]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1974214/KSP.log)
[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1974215/LMPServer.zip)
[lmpserver 2018-05-04 10-23-54.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1974219/lmpserver.2018-05-04.10-23-54.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1974222/output_log.txt)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS:
Windows 10.0 x64 Pro (compilation 16299)

KSPVersion:
1.4.3 + Expansion 1.4.3 (v1.2)

LMP version:
0.8.42.408

MODS (add link to download them):
https://www.curseforge.com/kerbal/ksp-mods/mechjeb/download

Current behaviour: 
When I was flying around Sun trying to catch asteroid I found weird behaviour. Asteroid or ship changing the orbit or place in time. It looks like asteroid is disapear and show in diferent place on same orbit.
When I was in the middle of burning and asteroid change the position, my burning is clamped to 0%

Steps to reproduce: 
Server and client runing on the same machine. Connected locally. No other players on server.

**Comment by gavazquez** [comment]
Expected behaviour. Check https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Timewarp
