### ISSUE TITLE
LMP On linux / Raspberry pi

### ISSUE THREAD

**Issue by joshgreatuk** [LunaMultiplayer/LunaMultiplayer#139]
Hi, this isn't really an issue but is there a way to port an LMP server over to Linux or a Raspberry pi (Debian), this might sound weird but it would make for a low budget 24 hour server. Thanks

**Comment by keamos** [comment]
You already can, you need to install mono and use it to run the exe file.

https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server

**Comment by joshgreatuk** [comment]
Thanks
