### ISSUE TITLE
Duplicate vessels and explosions at decoupling

### ISSUE THREAD

**Issue by Lleios** [LunaMultiplayer/LunaMultiplayer#140]
[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2018302/LMPServer.zip)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2018303/output_log.txt)
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2018304/KSP.log)

(start around 20:42:00)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10 64bits April Update

------------------------------------------------------------------------------

KSPVersion: 1.4.3

------------------------------------------------------------------------------

LMP version: 
0.8.42

------------------------------------------------------------------------------

Expected behaviour: 
Decouple vessel

------------------------------------------------------------------------------

Current behaviour: 
Vessel is duplicate. There is a vessel before decoupling and vessel after decoupling. But often vessels explode

------------------------------------------------------------------------------

Steps to reproduce: Decouple vessel from rocket

![capture d ecran 18 _li](https://user-images.githubusercontent.com/10956848/40253469-282ddd7a-5ae0-11e8-9738-c0bf50a91119.jpg)

**Comment by Lleios** [comment]
Yesterday, I played 4 hours without interpolation and i had no problems.
It may be that.

**Comment by gavazquez** [comment]
I think i fixed it in latest nightly. Better if you try it as it's a quite unstable code

**Comment by Lleios** [comment]
Me and a friend tried release(0.9.44) et nightly(0.10.45) version and we had the same behavior.
With and without interpolation.

**Comment by gavazquez** [comment]
Are you using any mod?

**Comment by Lleios** [comment]
No mod. I'll try to make a video of this bug soon
