### ISSUE TITLE
Server eats ram on raspian

### ISSUE THREAD

**Issue by joshgreatuk** [LunaMultiplayer/LunaMultiplayer#142]
Im running a ksp server on my raspberry pi, now this works fine and all but i have 1 problem, every couple of days a restart is required.

basically the server eats the ram up in 2 days to the point where the raspberry pi crashes and corrupts the universe file, much appreciated if this is fixed as it means the server would be extremely low maintenence
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 

Raspberry pi (Raspian)

KSPVersion: 

server

LMP version (include the build number if you are using a nighly build): 

latest server

MODS (add link to download them): 

none

Expected behaviour: 

it would run for ages no problem

Current behaviour: 

it eats up ram until the raspberry pi crahes

Steps to reproduce: 

run the server

**Comment by gavazquez** [comment]
Have you tried running it in "Database mode" instead of dictionary?

Check RelaySettings.xml

```XML
  <!--Relay system mode. Dictionary uses more RAM but it's faster. DataBase use disk space instead but it's slower. Values: Dictionary, DataBase-->
  <RelaySystemMode>Dictionary</RelaySystemMode>
```

**Comment by joshgreatuk** [comment]
yeah i changed the value to 'DataBase and it came up with an error that said invalid value

**Comment by gavazquez** [comment]
You're right please try with the value: Database


```XML
  <!--Relay system mode. Dictionary uses more RAM but it's faster. DataBase use disk space instead but it's slower. Values: Dictionary, Database-->
  <RelaySystemMode>Dictionary</RelaySystemMode>
```

**Comment by joshgreatuk** [comment]
thanks, i tried that last night and this morning i find its crashed, normally it would do this because it ran out of ram

**Comment by gavazquez** [comment]
is there any stack trace? can't do much without further logs

**Comment by joshgreatuk** [comment]
i know why, my internet went down early this morning and the server tried to work but couldnt so it resulted in a crash, i have looked through the logs

**Comment by gavazquez** [comment]
Ok then. Will close this issue as this should solve it. Refer to the specific wiki page about hosting a server using a rpi
