### ISSUE TITLE
Incorrect vessel is messaged for deletion when recovering vessel

### ISSUE THREAD

**Issue by jamesw6811** [LunaMultiplayer/LunaMultiplayer#145]
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2046419/output_log.txt)
[shipdisappearbugserverlog.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2046411/shipdisappearbugserverlog.txt)

OS: 
Debian Server, Windows 10 Client
------------------------------------------------------------------------------

KSPVersion: 
1.4.3.2152
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.8.42
------------------------------------------------------------------------------

MODS (add link to download them): 
MechJeb, Kerbal Engineering
------------------------------------------------------------------------------

Expected behaviour: 
Ship landed on Mun should not disappear while walking around on EVA.
------------------------------------------------------------------------------

Current behaviour: 
My vessel disappeared at nearly the same time as the 2nd player on the server recovered a different vessel.
------------------------------------------------------------------------------

Message from another client recovering his vessel seems to have sent a VesselRemove message for the ship my player was EVA'ing near.

In the logs see vessel 61ab48c8-16ff-4e62-b324-60f964ddefbd - poor Valentina was left stranded on the moon.

```
	Line 154: [19:15:50][Debug] : jamesw acquired lock Update - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 155: [19:15:50][Debug] : jamesw acquired lock UnloadedUpdate - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 158: [19:15:53][Debug] : jamesw released lock UnloadedUpdate - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 159: [19:15:53][Debug] : jamesw released lock Update - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 160: [19:15:53][Debug] : jamesw released lock Control - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 167: [19:15:55][Debug] : jamesw acquired lock Update - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 168: [19:15:58][Debug] : jamesw acquired lock UnloadedUpdate - 61ab48c8-16ff-4e62-b324-60f964ddefbd
	Line 176: [19:16:38][Debug] : Removing vessel 61ab48c8-16ff-4e62-b324-60f964ddefbd from rgbiv
```

Steps to reproduce: 
Unknown. Potentially try logging out of game with a player, then logging back in and recovering a vessel, all while another player is standing next to an empty vessel.
------------------------------------------------------------------------------

Question: Are the vessel-related systems potentially not being completely reset when someone logs out of a server and then back in?

**Comment by gavazquez** [comment]
Just had a look at it. Could it be that your friend recovered YOUR vessel?
Looking at the code that's the only possibility...

**Comment by jamesw6811** [comment]
I'll try to get his log file. You can't recover a vessel landed on the Mun,
can you?

Is there any way for a recently re-logged in player the vessel ids could
get corrupted?

**Comment by gavazquez** [comment]
Perhaps it was terminated instead of recovered? The log of your friend might tell you.

Either way, I checked and improved the code that lock/unlock the recover/terminate buttons in the tracking station

**Comment by jamesw6811** [comment]
In the log the recovery text was adjacent to the vessel removal, and I
didn't see any other vessels removed due to the recovery. That's why I
thought it was so weird. I'll bug friend for the log - thanks!

**Comment by jamesw6811** [comment]
Friend's log is nearly empty, must have restarted the game or something, resetting the log. Oh well, feel free to toss this one.
