### ISSUE TITLE
Science rewards missing after logout/login in the middle of a flight

### ISSUE THREAD

**Issue by micah-eberhard** [LunaMultiplayer/LunaMultiplayer#146]
OS: 
Windows 10

------------------------------------------------------------------------------

KSPVersion: 
1.4.3.2152

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
Version 0.9.44
Build 0.9.44.441

------------------------------------------------------------------------------

MODS (add link to download them): 
None (Just LMP)

------------------------------------------------------------------------------

Expected behaviour: 
- When a player does a science experiment anywhere in space, logs out, logs back in and continues flying their mission back to Kerbin, upon landing, the science experiments completed in-flight before their logout should be rewarded.
- Science experiments should receive the proper reward upon returning to Kerbin regardless of the player logging out in the middle of a mission or not.
------------------------------------------------------------------------------

Current behaviour: 
- Science experiments *DO NOT* receive the proper reward upon returning to Kerbin if the player has logged out of the server after doing some experiments on a mission, then resuming and completing their mission at a later time.
------------------------------------------------------------------------------

Steps to reproduce: 
- Launch a mission
- Run science experiments
- Log out of the server while mission is still running
- Log back in
- Take over your current flight from the tracking station
- Successfully land your craft and recover it on Kerbin
- Notice that you don't get any science from experiments completed on the mission before your log out

Other notes:
- I'm always available on the LMP discord under the alias `Altiar` feel free to PM me for more info.

**Comment by gavazquez** [comment]
Hmmm I don't think that will be possible to do... I think it's way too much work as it would involve keeping partial experiments server-side.

Any idea @MalteJanz ?

**Comment by gavazquez** [comment]
Seems to be related with the class "ScienceData" but I don't know where it's even stored in the scenario...

**Comment by micah-eberhard** [comment]
The vessels seem to already save some of this info (sort of?). The experiments attached to your vessel after logging back in display the proper state, like the goo container shows it's self as open, and acts like it has data saved in it if you right click on it. It's just not rewarded at the end of a mission.

Also, unsure if I'm right about this, but DMP did handle this properly, and it seems like LMP makes use of some of the old DMP code? Obviously this case is a little bit different since DMP didn't have to sync in-progress experiments across clients since all science was unique to each player client.

**Comment by gavazquez** [comment]
Unfortunately the code is totally different in LMP.
From what I see that experiment data is stored in the ModuleScienceExperiment inside the vessel.

Perhaps I can fix by listening to the game event when "storing" science and then force to send the vessel to the server. 

Should be simple (in theory)

**Comment by gavazquez** [comment]
I just uploaded a fix for this. Let me know if it works (you'll have to test it from a nightly version)
