### ISSUE TITLE
ID not mapped in VesselRelayDbItem

### ISSUE THREAD

**Issue by ekul6547** [LunaMultiplayer/LunaMultiplayer#149]
I get an error when flying simple travelling around the server for a bit.
I have to be controlling the craft, and it sometimes crashes the server, and thus disconnects me.
It doesn't matter if mods are on or not as I did a fresh install of both client and server, and still got the error.

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10
Client: Steam Version
Server: Either windows or Raspberry Pi
------------------------------------------------------------------------------

KSPVersion: 
1.4.3
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.9.44
------------------------------------------------------------------------------

MODS (add link to download them): 
Happened with mods on, so I did a completely fresh install (both client and server) and it still happens
------------------------------------------------------------------------------

Expected behaviour: 
... work
------------------------------------------------------------------------------

Current behaviour:
Stops writing to db - sometimes crashes, sometimes doesn't
------------------------------------------------------------------------------

Steps to reproduce: 
Relay settings set to Database, Interval=10000
Play around for a bit in a ship. Doesn't matter what.

![screenshot_1](https://user-images.githubusercontent.com/4570157/41045896-42488622-69a1-11e8-9c50-eec7ab8c1152.png)
Server log:
[lmpserver 2018-06-06 15-48-23.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2076788/lmpserver.2018-06-06.15-48-23.log)
KSP log:
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2076798/KSP.log)
output_log:
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2076801/output_log.txt)

Server Files:
[ServerFiles.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2076809/ServerFiles.zip)

**Comment by gavazquez** [comment]
Database relay setting is broken. Currently working on a fix for next version and it will be handled client-side
