### ISSUE TITLE
Building upgrade is not restored correctly in career mode

### ISSUE THREAD

**Issue by AlexFaraino** [LunaMultiplayer/LunaMultiplayer#150]
------------------------------------------------------------------------------
Server OS: Linux Debian
Client OS : win 10
------------------------------------------------------------------------------
KSPVersion: 1.4.3
------------------------------------------------------------------------------
LMP version (include the build number if you are using a nighly build): 0.10.45.512
------------------------------------------------------------------------------
MODS (add link to download them): None
------------------------------------------------------------------------------
Expected behaviour: In Career mode, when you upgrade a building at the KSC, the upgrade level is saved on the server and stay when you reconnect.
------------------------------------------------------------------------------
Current behaviour: The building is upgraded to max level. All other buildings are still at the stock level.
------------------------------------------------------------------------------
Steps to reproduce: 
- Create a server in Career mode
- Upgrade a building at the KSC (launchpad)
- Disconnect.
- Reconnect to the server. 
-> The building is upgraded to the max level.

Debug files:
[LMP.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2085994/LMP.zip)

**Comment by AlexFaraino** [comment]
You will see that the Scenario/scenarioUpgradableFacilities.xml contains:
`<Node name="SpaceCenter/LaunchPad">
    <Parameter name="lvl">1</Parameter>
  </Node>`
But still, it's not working ;)

**Comment by gavazquez** [comment]
That's because level 1 must be 0.5 and level 2 must be 1
