### ISSUE TITLE
[Carreer] You can recover a vessel twice

### ISSUE THREAD

**Issue by AlexFaraino** [LunaMultiplayer/LunaMultiplayer#151]
------------------------------------------------------------------------------
Server OS: Linux Debian
Client OS : win 10
------------------------------------------------------------------------------
KSPVersion: 1.4.3
------------------------------------------------------------------------------
LMP version (include the build number if you are using a nighly build): 0.10.45.512
------------------------------------------------------------------------------
MODS (add link to download them): None
------------------------------------------------------------------------------
Expected behaviour: In Career mode, when you recover a vessel, you get science, funds and xp for your kerbal. However, you can recover the vessel only once ;)
------------------------------------------------------------------------------
Current behaviour: Once you have recovered the vessel, there is an icon on the KSC, near the runway. If you click on it, you can recover the vessel twice.
------------------------------------------------------------------------------
Steps to reproduce: 
- Create a server in Career mode
- launch a simple vessel, with science module
- Run the science module on the ground or during the flight
- Fly :)
- Once splashed down, recover the vessel by unfolding the top menu
- The game brings you back to the KSC and display the window showing how much science, fund and xp you earned. Validate this window.
-> The window closes and there is an icon near the runway, on the KSC, that you can click to recover the vessel again.

Debug files:
[LMP-nightly.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2086116/LMP-nightly.zip)

Note: It seems that if there is no science module embedded, the bug does not occurs.

**Comment by gavazquez** [comment]
I think it's fixed now but let me know if it still fails ;)

I tried recovering with the button and also with the marker
