### ISSUE TITLE
LunaMP doesnt Start 

### ISSUE THREAD

**Issue by lYasharl** [LunaMultiplayer/LunaMultiplayer#159]
Hi
i just downloaded the latest Release Client and putted the needed content in the gamedata folder so i have a "LunaMultiplayer" Folder in my "GameData" Folder but when i start the game i dont see any new menu so i can register there . im not using any mods. is there a specific version of KSP that is needed or this mod works on all versions ?  (i have installed the Release Version of the Client) 
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2102460/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2102461/output_log.txt)

**Comment by gavazquez** [comment]
Hi, you need latest KSP version for it to work. You are on 1.3.1 and you need 1.4.3

**Comment by lYasharl** [comment]
Thanks
