### ISSUE TITLE
Laggy Asteroids!

### ISSUE THREAD

**Issue by AdamRashers** [LunaMultiplayer/LunaMultiplayer#160]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
Windows
------------------------------------------------------------------------------

KSPVersion: 
1.4.3
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

-----------------Latest-------------------------------------------------------------

MODS (add link to download them): 

------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 

------------------------------------------------------------------------------

Steps to reproduce:

**Comment by gavazquez** [comment]
Shitty bug description. Closing it
