### ISSUE TITLE
Contract interface is buggy

### ISSUE THREAD

**Issue by AlexFaraino** [LunaMultiplayer/LunaMultiplayer#161]
------------------------------------------------------------------------------

OS: Client : Windows 10 - Server : Linux Debian

------------------------------------------------------------------------------

KSPVersion: 1.4.3

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

------------------------------------------------------------------------------

MODS (add link to download them): 0.10.46

------------------------------------------------------------------------------

Expected behaviour: Clean contract interface

------------------------------------------------------------------------------

Current behaviour: Too much contracts available + contract history is too short (only 3)

------------------------------------------------------------------------------

Steps to reproduce: Not sure. Once, I got a contract where every steps are "done" but the contract is still ongoing. So I used KSP debug interface to close contracts. Since then, I often got this contract mess.

[Debug.tar.gz](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2116796/Debug.tar.gz)

**Comment by AlexFaraino** [comment]
![screenshot1](https://user-images.githubusercontent.com/1453854/41622793-fdf2001e-7410-11e8-9c8d-c6fb39603a81.png)

**Comment by Embries** [comment]
I can duplicate. Even have multiple contracts for "terminal" contract (major contacts given when leveled up) 2 leave the atmosphere.

**Comment by gavazquez** [comment]
We are bit crowded with normal jobs and other more urgent bugs but will have a look once we're more free

**Comment by Embries** [comment]
No need to rush on my account. Just want to help the environment.

Sent from my iPhone

On Jul 24, 2018, at 9:52 AM, Gabriel Vázquez (Dagger) <notifications@github.com<mailto:notifications@github.com>> wrote:


We are bit crowded with normal jobs and other more urgent bugs but will have a look once we're more free

**Comment by gavazquez** [comment]
Hey @MalteJanz I think I managed to fix this let me know if you've got any idea of what may be causing bugs.

@Embries and @AlexFaraino feel free to test it on nightly and let me know if the problem still persists. 

Thank you all!
