### ISSUE TITLE
Career Bugs: Hire, Tourists, Rescue

### ISSUE THREAD

**Issue by Sladernimo** [LunaMultiplayer/LunaMultiplayer#167]
Career Mode seems to have some new bugs:

1. Sometimes you can't hire new Kerbals in the complex. It says 0 money for next hire. But If you try, nothing happens. After reconnecting hiring works again.

2. Sometimes when accepting a tourist mission, the responding tourist is not available for mission.

3. Sometimes when accepting a rescue mission and you try to get close to the capsule at a few k meters frame rate drops extremely and you cant switch to that capsule to get the Kerbal out that you want to rescue.

Tested on latest KSP + LMP nightly (28.06.18)

**Comment by shakaah** [comment]
"Sometimes when accepting a tourist mission, the responding tourist is not available for mission."

Same problem with my friend

**Comment by DevoraP** [comment]
Same here.

**Comment by gavazquez** [comment]
I think it's fixed now :)

**Comment by gandalf3** [comment]
Still not seeing tourists in 0.11.47
