### ISSUE TITLE
Auto-Recovery Bug.

### ISSUE THREAD

**Issue by supercid87** [LunaMultiplayer/LunaMultiplayer#169]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2264937/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2264940/output_log.txt)

[UniverseConfig.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2264942/UniverseConfig.zip)
[UniverseConfig.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2264943/UniverseConfig.zip)

OS: 
Windows 7
------------------------------------------------------------------------------

KSPVersion: 
1.4.4
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
(Nightly) 0.11.47.620  [(Added player name...)]
------------------------------------------------------------------------------

MODS (add link to download them): 
None.
------------------------------------------------------------------------------

Expected behaviour: 
Persistence of orbiting kerbal-manned vessels.
------------------------------------------------------------------------------

Current behaviour: 
Orbiting vessels become auto-recovered on the launch of a certain new vessel.
------------------------------------------------------------------------------

Steps to reproduce: 
1. Have 2 players connect to a server. (You could prob try with 1 player, just will take longer)
2. Have them launch manned vessels, getting them into stable orbits around kerbin.
3. When each vessel is placed in a stable orbit around kerbin leave it there by pressing escape and choosing tracking station or space center.
4. After the 4th or 5th vessel is left in space the older vessels will begin to be auto-recovered when pressing the "launch" button in the V.A.B. for a new vessel.

**Comment by gavazquez** [comment]
On the "GeneralSettings.xml of the server. What is the value of:

```XML
  <!--Specify if the vessels that are being CONTROLLED and in a past subspace will be shown for players in future subspaces-->
  <ShowVesselsInThePast>true</ShowVesselsInThePast>
```

Do you have that set to false?

**Comment by supercid87** [comment]
Here are the news steps to reproduce as "showvesselsinthepast>true" didn't seem to change it.
https://imgur.com/a/8546Fd2

Also, here are the logs and config.
[bug report logs&config.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2268153/bug.report.logs.config.zip)
