### ISSUE TITLE
Vessel gets unloaded when in EVA and other player starts a new rocket

### ISSUE THREAD

**Issue by ShyRed** [LunaMultiplayer/LunaMultiplayer#170]
Playing together as 2 players, sometimes a vessel disappears when a player is on EVA and the 2nd player starts a new vessel.

------------------------------------------------------------------------------

OS: 
Damaskar: Windows 7, 64 Bit
Avoider: Windows 7, 64 Bit

------------------------------------------------------------------------------

KSPVersion: 
1.4.5  (without the history DLC)

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.10.46 Build 0.10.46.573 ( https://github.com/LunaMultiplayer/LunaMultiplayer/releases/tag/0.10.46 )

------------------------------------------------------------------------------

MODS (add link to download them): 

- Scatterer 0.0331b ( https://github.com/LGhassen/Scatterer/releases/tag/0.0331b )
- Distant Object v1.9.1 ( https://github.com/MOARdV/DistantObject/releases/tag/v1.9.1 )
- Kerbal Engineer Redux v1.1.5.3 ( https://github.com/jrbudda/KerbalEngineer/releases/tag/1.1.5.3 )

------------------------------------------------------------------------------

Expected behaviour: 

Vessels stay with the player, if the player goes on EVA.

------------------------------------------------------------------------------

Current behaviour: 

Vessels despawn / disappear when the player goes on EVA and the 2nd player stats a new flight on the starting pad.

------------------------------------------------------------------------------

Steps to reproduce: 

It does not happen 100% of the time, but basically:

1. Player A starts a flight, lands somewhere far away from player B and goes with the only pilot in the vessel on EVA.
2. Player B starts a new flight.

One factor might be if there is an old vehicle or debris on the starting pad.

Please see attached logfile. Starting at 18:23:41 I (Damaskar) did some experiments on Mun. Then I left the vehicle (releasing several locks). 82a7d8ca-7aad-403f-9141-cddc1ba21e9b is one of them. Suddenly Avoider (who was on Kerbin) gained locks to the same vehicle and seems to have unloaded it?

There is some strange locking going on as I had control over Jebediah Kerman all the time. There should not have been a released lock.

I unfortunately do not know much about locking system, but Avoider should never get a lock to a vessel that is not even close to him and I should never lose a lock on a Kerbal that I still have under my control?

We first encountered the issue on LunaMultiplayer Nightly and switched to the latest stable release thinking it was a bug in the nightly, but it seems that the bug is there in both stable and nightly.

The issue sounds similar to #145 

IDEA: Avoider just told me, that he got a message asking him if he wanted to recover a vessel on the launch pad. Could it be that he saw my vessel in the past there when I was already in the future? (timewarp)?

This could explain what has happened...

[lmpserver_2018-08-12_15-32-08.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2281117/lmpserver_2018-08-12_15-32-08.log)

**Comment by gavazquez** [comment]
This is the same bug as https://github.com/LunaMultiplayer/LunaMultiplayer/issues/169
It's already fixed but only on nightly
