### ISSUE TITLE
Messed up Timewarp Causing Major orbit/landed glitches

### ISSUE THREAD

**Issue by ZaosDaOne** [LunaMultiplayer/LunaMultiplayer#174]
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows

------------------------------------------------------------------------------

KSPVersion: 1.4.5

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build):  0.11.47

------------------------------------------------------------------------------

MODS (add link to download them): KER and Mechjeb

------------------------------------------------------------------------------

Expected behaviour: time sync to work properly and have my friend landed with me

------------------------------------------------------------------------------

Current behaviour: "A" is ahead in time "B" is behind lets say A is timewarping and then stops and does manuever nodes or anything really thats not time warping once B surpasses him (surpasses him through time so B is now ahead) WITHOUT either of them syncing from the beginning the game gets confused of whats where usually giving me a cockpit that was "landed" out in open space going 0.0m/s with no orbit
![image](https://user-images.githubusercontent.com/32281247/44381618-28902e00-a4df-11e8-807a-db5051490e9c.png)
![image](https://user-images.githubusercontent.com/32281247/44381624-2d54e200-a4df-11e8-9ce4-9836c6d515e9.png)

------------------------------------------------------------------------------

Steps to reproduce:

**Comment by gavazquez** [comment]
Fixed on latest nightly after several commits
