### ISSUE TITLE
Losing Kerbals for no reason

### ISSUE THREAD

**Issue by ZaosDaOne** [LunaMultiplayer/LunaMultiplayer#175]
------------------------------------------------------------------------------

OS: Windows

------------------------------------------------------------------------------

KSPVersion: 1.4.5

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.11.47

------------------------------------------------------------------------------

MODS (add link to download them): mechjeb and KER

------------------------------------------------------------------------------

Expected behaviour: Me being able to recover my craft without having my kerbals go MIA

------------------------------------------------------------------------------

Current behaviour: kerbals go MIA when i try recovering and 90% of the time it doesnt let me so i spam the recover button it presses and nothing happens i go to tracking station and it suddenly goes back in time to a previous moment (the craft) playing with 1 other friend

------------------------------------------------------------------------------

Steps to reproduce: just try to recover a craft

**Comment by gavazquez** [comment]
Just tested and it works fine, I will need better reproduction steps
