### ISSUE TITLE
My crafts disappear when I disconnect/reconnect from the server

### ISSUE THREAD

**Issue by MoOSTiiK** [LunaMultiplayer/LunaMultiplayer#179]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2332187/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2332195/output_log.txt)

All my crafts disappear from the server at each disconnection, whether I am in orbit of Kerbin, Mun or Minmus, and even when I land on the last two.

Also, when I do an EVA, I can control my Kerbinaut for 1 to 2 minutes, then my game becomes "inactive": I can move the camera, move my pointer to different elements (I can see them go green), but impossible to select anything and move my Kerbinaut, so I have to disconnect / reconnect and ... I lose my craft.

We are several on the LMP server and I am the only one in this case (to my knowledge).
------------------------------------------------------------------------------

OS: 
Windows 10 Pro 64bits
------------------------------------------------------------------------------

KSPVersion: 
KSP 1.4.5.2243
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
Build 0.11.47.650
------------------------------------------------------------------------------

MODS (add link to download them): 
B9 Part Switch v2.3.3 (https://github.com/blowfishpro/B9PartSwitch/releases/download/v2.3.3/B9PartSwitch_v2.3.3.zip)
HullcamVDS Continued v0.1.9.3 
(https://archive.org/download/HullcamVDSContinued-0.1.9.3/C4248D1A-HullcamVDSContinued-0.1.9.3.zip)
Kerbal Alarm Clock v3.9.1.0
(https://archive.org/download/KerbalAlarmClock-v3.9.1.0/77C605FE-KerbalAlarmClock-v3.9.1.0.zip)
Kerbal Attachment System v0.6.4.0
(https://kerbal.curseforge.com/projects/kerbal-attachment-system-kas/files/2539044/download)
Kerbal Engineer Redux v1.1.5.3
(https://archive.org/download/KerbalEngineerRedux-1.1.5.3/40701193-KerbalEngineerRedux-1.1.5.3.zip)
Kerbal Inventory System v1.14
(https://github.com/ihsoft/KIS/archive/1.14.zip)
MechJeb 2 v2.7.3.0
(https://archive.org/download/MechJeb2-2.7.3.0/2DAFC250-MechJeb2-2.7.3.0.zip)
Module Manager v3.0.7
(https://archive.org/download/ModuleManager-3.0.7/9139E221-ModuleManager-3.0.7.zip)
Near Future IVA Props v0.3.3
(https://github.com/ChrisAdderley/NearFutureProps/archive/0.3.3.zip)
RasterPropMonitor v0.30.5
(https://github.com/Mihara/RasterPropMonitor/archive/v0.30.5.zip)
RasterPropMonitor Core v0.30.5
(https://archive.org/download/RasterPropMonitor-Core-1-v0.30.5/31DBFB47-RasterPropMonitor-Core-1-v0.30.5.zip)
SCANSat v18.7
(https://github.com/S-C-A-N/SCANsat/archive/v18.7.zip)
Stockalike Station Parts Expansion Redux v1.0.5
(https://spacedock.info/mod/1682/Stockalike%20Station%20Parts%20Expansion%20Redux/download/1.0.5)
Toolbar v1.7.17.11
(https://archive.org/download/Toolbar-1.7.17/074E60A8-Toolbar-1.7.17.zip)
Tweak Scale - Rescale everything! v2.3.12
(https://archive.org/download/TweakScale-v2.3.12/4986771D-TweakScale-v2.3.12.zip)
------------------------------------------------------------------------------

Expected behaviour: 
To be able to find my crafts after a reconnection, and move my Kerbinaut in EVA for a long time

------------------------------------------------------------------------------

Current behaviour: 
- Kerbinaut freezes after a few minutes of EVA
- Loss of all my crafts after reconnection
------------------------------------------------------------------------------

Steps to reproduce: 
1) Go into orbit or go to the mun
2) Disconnect and reconnect
3) To note the removal of the crafts

**Comment by gavazquez** [comment]
Probably caused by a mod. try nightly but bear in mind we don't provide support for them
