### ISSUE TITLE
Allow Other Launchsites Config not Supported

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#183]
Seemingly, Luna Multiplayer doesn't allow the "Allow other Lanchsites" config to be enabled, at least the GameplaySettings.xml doesn't have an appropriate set of tags for it.

**Comment by thygrrr** [comment]
Luna Server version: 0.12.49 (C:\Games\Steam\steamapps\common\Kerbal Space Program\LMPServer)

This doesn't even work when converting an existing savegame, sadly.

**Comment by gavazquez** [comment]
Available in next version or in nigthly
