### ISSUE TITLE
Reverting does not revert Funds / Science / Rep on Server

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#187]
OS: 
------------------------------------------------------------------------------
Win 10 Pro / Home 64 bits (happens on both)

KSPVersion: 
------------------------------------------------------------------------------
1.4.5

LMP version 
------------------------------------------------------------------------------
0.13.50.793 / 18dfb0ec

MODS (add link to download them): 
------------------------------------------------------------------------------
Making History Expansion
clean install, verified on both machines using Steam "Verify local files"

Expected behaviour: 
------------------------------------------------------------------------------
After Reverting, all players lose the earnings (Science / Funds / Reputation) from the reverted mission.

Current behaviour: 
------------------------------------------------------------------------------
When reverting a flight, the local player loses the funds and science (probably also rep, but that is difficult to read) from that flight.

However, the OTHER players keep all the extra science and funds. 

Furthermore, if the reverting player reconnects, they, too, will have the higher funds.

Steps to reproduce: 
------------------------------------------------------------------------------
- Download nightly.
- Click server.exe, then CTRL-C
- Delete Universe (not sure if necessary?)
- In the GeneralSettings.xml, change game type from Sandbox to Career (not sure of necessary?)
- Click server.exe, start KSP, join server (using local / LAN IP, but usually reproducible through NAT as well).

1. Join 1st player
2. Join 2nd player
3. Observe identical Science and Funds
4. As 1st player, launch a simple vessel to earn some World's Firsts or complete a contract
5. Observe Science+Funds gains made (hover over funds icon for 1st player) on all machines
5. As 1st player, Crash Vessel & Revert
6. Observe 1st player has deducted funds & science, and contract reappears for all players, etc (btw awesome work <3)
7. Observe 2nd player still has funds and science equal to the pre-revert state.

**Comment by gavazquez** [comment]
Fixed, although I think that I might miss something like contracts for example
