### ISSUE TITLE
Extraneous Contract Rewards and Errors

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#189]
OS: 
------------------------------------------------------------------------------
Win 10 Pro / Home 64 bits (happens on both)

KSPVersion: 
------------------------------------------------------------------------------
1.4.5

LMP version 
------------------------------------------------------------------------------
0.13.50.793 / 18dfb0ec

MODS (add link to download them): 
------------------------------------------------------------------------------
Making History Expansion
clean install, verified on both machines using Steam "Verify local files"

Expected behaviour: 
------------------------------------------------------------------------------
One Contract is Complete. One reward is paid.

Current behaviour: 
------------------------------------------------------------------------------
I get 1.5 Million Funds and over 200 science.

Steps to reproduce: 
------------------------------------------------------------------------------
- Download nightly.
- Use attached Config & Universe (config only has Career gamemode, rest is default, universe has a tiny bit of gameplay progress completed and an appropriate contract selected) 
[Config-Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2435127/Config-Universe.zip)

- Click server.exe, start KSP, join server (using local / LAN IP, but usually reproducible through NAT as well).

1. Join Players 1 and 2
2. As 1st Player, put "Jumping Flea (Stock)" craft on pad and wait in flight scene
3. As 2nd Player put "Jumping Flea (Stock)" craft on pad and wait in flight scene
4. As 1st Player, launch and hold right (D) until the contract completes (when the speed drops below 240)
5. Observe MANY repeat contract rewards. (37x on Player 1, 32x on Player 2, actual amount often varies, screenshot is from another repro attempt where only 3x rewards happened.) 
![9627049 499999965_ksp_x64_2018-10-01_19-46-29](https://user-images.githubusercontent.com/8904620/46307420-2aa5dc00-c5b7-11e8-8003-48ef9dee4f67.png)

**Comment by thygrrr** [comment]
Based on this scenario, #190 can be reproduced by adding some extra steps. As those involve a Revert and result in totally different types of errors, I moved it to a separate issue.

**Comment by gavazquez** [comment]
This should have been fixed with the patch that avoids sending contract "updates". Also with the fix of CachedQuickLz to support multithreading
