### ISSUE TITLE
Recover Vessel and Space Center buttons don't work after Revert

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#191]
OS: 
------------------------------------------------------------------------------
Win 10 Pro / Home 64 bits (happens on both)

KSPVersion: 
------------------------------------------------------------------------------
1.4.5

LMP version 
------------------------------------------------------------------------------
0.13.50.793 / 18dfb0ec

MODS (add link to download them): 
------------------------------------------------------------------------------
Making History Expansion
clean install, verified on both machines using Steam "Verify local files"

Expected behaviour: 
------------------------------------------------------------------------------
Buttons work.

Current behaviour: 
------------------------------------------------------------------------------
Buttons can be clicked, but don't work.

Steps to reproduce: 
------------------------------------------------------------------------------
- Download nightly.
- Use attached Config & Universe (config only has Career gamemode, rest is default, universe has a tiny bit of gameplay progress completed and an appropriate contract selected) 
[Config-Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2435127/Config-Universe.zip)
- Click server.exe, start KSP, join server (using local / LAN IP, but usually reproducible through NAT as well).

1. Join Server
2. Put Craft "Jumping Flea (Stock)" on Pad
3. Hit SPACE to launch, then ESC and Revert Flight to Launchpad
4. Observe the buttons under the altimeter do not work anymore.
![image](https://user-images.githubusercontent.com/8904620/46308513-23cc9880-c5ba-11e8-94e8-02e12f379152.png)

**Comment by thygrrr** [comment]
I have observed this also after a lot of missions, but haven't been able to reproduce reliably with a short mission profile. May require others playing.

**Comment by gavazquez** [comment]
Difficult to reproduce but the issue is because this evaluates to false:
´HighLogic.CurrentGame.Parameters.Flight.CanLeaveToSpaceCenter´

This is needed to properly Recover the vessel:

´´´
AltimeterSliderButtons class....

        private void recoverVessel()
        {
            this.clearToSaveStatus = FlightGlobals.ClearToSave();
            if (this.clearToSaveStatus == ClearToSaveStatus.CLEAR && HighLogic.CurrentGame.Parameters.Flight.CanLeaveToSpaceCenter)
            {
                GameEvents.OnVesselRecoveryRequested.Fire(FlightGlobals.ActiveVessel);
            }
        }
´´´

**Comment by gavazquez** [comment]
Not sure if this will work.....
