### ISSUE TITLE
Spectating Fails Spectacularly when Warping on Chutes

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#193]
OS: 
------------------------------------------------------------------------------
Win 10 Pro / Home 64 bits (happens on both)

KSPVersion: 
------------------------------------------------------------------------------
1.4.5

LMP version 
------------------------------------------------------------------------------
0.13.50.793 / 18dfb0ec

MODS (add link to download them): 
------------------------------------------------------------------------------
Making History Expansion
clean install, verified on both machines using Steam "Verify local files"

Expected behaviour: 
------------------------------------------------------------------------------
Can click on VAB or other buildings.

Current behaviour: 
------------------------------------------------------------------------------
Can't click, nor mouseover.

Steps to reproduce: 
------------------------------------------------------------------------------
- Download & install nightly, start game.

1. Join Server as Players 1 and 2
2. As 1st player, Launch "Jumping Flea (Stock)" craft.
3. When on the parachute, as 2nd player, spectate the craft by clicking "Fly" in the Tracking Station
4. Observe (often) weird behaviour of the SRB, which is firing and causing the simulations to diverge.
5. As 1st player, while craft is hanging on chute, engage physics warp (4x for maximum effect).
6. As 2nd player, observe insane physics, craft exploding on ground (despite it being the past, not future?), etc. This appears to maybe be an interpolation issue, because strangely, the physics look a bit like a mix of slow motion and fast forward.
7. Observe often inability to properly catch up with the other player's subspace. Other crafts in the tracking station may or may not phase in and out of existence for either player.
8. Observe depending on state of the craft, that the Altimeter "Recover Craft" and "Space Center" buttons don't show up, because it technically has crashed, but also no flight report dialog shows up.

**Comment by gavazquez** [comment]
Regarding the positioning, I think that the issue is that while timewarping no positions are sent, not sure if this has any solution....

**Comment by thygrrr** [comment]
I thought you are sending positions with timestamps during Timewarp... wasn't that one of the main points of the interpolation?

**Comment by gavazquez** [comment]
mmm more or less... I can give a think about this but the reality is that to interpolation with precision we use the subspace time difference as that's a safe timing value that is not affected by the FPS and things like that

**Comment by gavazquez** [comment]
Well I think this one is fixed aswell

**Comment by thygrrr** [comment]
Spectator will still sink through the ground quickly when the controlling player warps while on parachutes / near the ground.

Worse: 
1. Spectator can get depth records and rewards for this "sinking"
2. Spectator can destroy the ship by returning to space center. -> #205
