### ISSUE TITLE
Spectator clones Kerbal, gets Funds+Science for (not actually) Recovering a Craft

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#194]
OS: 
------------------------------------------------------------------------------
Win 10 Pro / Home 64 bits (happens on both)

KSPVersion: 
------------------------------------------------------------------------------
1.4.5

LMP version 
------------------------------------------------------------------------------
0.13.50.793 / 18dfb0ec

MODS (add link to download them): 
------------------------------------------------------------------------------
Making History Expansion
clean install, verified on both machines using Steam "Verify local files"

Expected behaviour: 
------------------------------------------------------------------------------
Can click on VAB or other buildings.

Current behaviour: 
------------------------------------------------------------------------------
Can't click, nor mouseover.

Steps to reproduce: 
------------------------------------------------------------------------------
- Download nightly.
- Use attached Config & Universe (config only has Career gamemode, rest is default, universe has a tiny bit of gameplay progress completed and an appropriate contract selected) 
[Config-Universe-Buttons.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2435219/Config-Universe-Buttons.zip)

- Click server.exe, start KSP, join server (using local / LAN IP, but usually reproducible through NAT as well).

1. Join Server as Players 1 and 2
2. As 1st player, Launch any simple Craft on the Pad.
3. When out of the bubble, as 2nd player, spectate the craft by clicking "Fly" in the Tracking Station (actually also reproducible by immediately spectating through the Tracking Station)
4. As 1st player, once landed, recover craft. Observe Recovery dialog, etc.
5. ~~~As 2nd player, observe errors on screen and log: (likely this was #184 in some sort of flavor, as the menu error message is the same, though the log shows no error immediately, but probably wasn't flushed)~~~
6. As 1st player, OBSERVE a copy of the craft still where it landed! (may need to look around but it can't have gone far)
![image](https://user-images.githubusercontent.com/8904620/46311511-bffa9d80-c5c2-11e8-88df-372ee9b65214.png)

7. Wait, if you are the real Jebediah, then whom did we recover five minutes ago? **dramatic music plays**

8. As 1st player, observe you can go back into the craft over and over again and keep recovering it for more and more reward. Actually, any spectator can recover the craft at any time it is recoverable.

9. In Astronaut Complex, 1st Player can also find the (non-recovered) craft's pilot as "ready for next mission"

10. If done in a timely fashion, 1st player can launch another mission with the same pilot while the other still has their clone in their craft.

11. 2nd player will observe that their pilots seat is now empty (but the pilot nametag is still there, and the player also has full control over the craft)

12. 2nd player cannot click "View" for IVA, but can click EVA. Both players can successfully EVA. If they re-Board their craft, the Kerbal Kloning process is complete. I wasn't able to get them both to stand next to each other for a photo, but I also didn't want to create an even bigger dimensional paradox.

**Comment by thygrrr** [comment]
Sometimes the player who is spectating sees a slew of errors like these:
![image](https://user-images.githubusercontent.com/8904620/46311875-bde50e80-c5c3-11e8-98af-383465bdefdd.png)

These do not end up in KSP log right away but also seem to be a flavor of #184

**Comment by thygrrr** [comment]
Yep.
```
[ERR 21:47:50.589] [LMP]: Error handling Message type LmpCommon.Message.Data.ShareProgress.ShareProgressScienceSubjectMsgData, exception: System.NullReferenceException: Object reference not set to an instance of an object
  at ScienceSubject.Load (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at ScienceSubject..ctor (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at LmpClient.Systems.ShareScienceSubject.ShareScienceSubjectMessageHandler.ConvertByteArrayToScienceSubject (System.Byte[] data, Int32 numBytes) [0x00000] in <filename unknown>:0 
  at LmpClient.Systems.ShareScienceSubject.ShareScienceSubjectMessageHandler.NewScienceSubject (LmpCommon.Message.Data.ShareProgress.ScienceSubjectInfo subject) [0x00000] in <filename unknown>:0 
  at LmpClient.Systems.ShareScienceSubject.ShareScienceSubjectMessageHandler+<>c__DisplayClass4_0.<HandleMessage>b__0 () [0x00000] in <filename unknown>:0 
  at LmpClient.Systems.ShareProgress.ShareProgressBaseSystem`3[T,TS,TH].RunQueue () [0x00000] in <filename unknown>:0 
  at LmpClient.Systems.ShareProgress.ShareProgressBaseSystem`3[T,TS,TH].QueueAction (System.Action action) [0x00000] in <filename unknown>:0 
  at LmpClient.Systems.ShareScienceSubject.ShareScienceSubjectMessageHandler.HandleMessage (IServerMessageBase msg) [0x00000] in <filename unknown>:0 
  at LmpClient.Base.MessageSystem`3[T,TS,TH].HandleMessage (IServerMessageBase msg) [0x00000] in <filename unknown>:0 
```

**Comment by thygrrr** [comment]
I changed the title because the bug is probably NOT that the craft still sticks around (simplifying the repro to put a single capsule on the pad and tipping it over by pressing W and then spectating and recovering showed that the other player can take over control. AMAZEBALLS.

Still, 1st player (first recoverer) gets a funds recovered dialog even though they are also told "you cannot recover this craft, it is not yours".

**Comment by gavazquez** [comment]
Fixed :)
