### ISSUE TITLE
Erroneous Warp Message upon Server Join

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#202]
OS: 
------------------------------------------------------------------------------
Win 10 x64

KSPVersion: 
------------------------------------------------------------------------------
1.4.5 Making History

LMP version (include the build number if you are using a nighly build): 
------------------------------------------------------------------------------
Nightly 0.13.50.828 / 27e3c5af

Expected behaviour: 
------------------------------------------------------------------------------
I see the MotD.

Current behaviour: 
------------------------------------------------------------------------------
I see the MotD but also an erroneous "Timewarp" message.

Repro:
--------------------
1. Look at center of screen just after joining a server.

![ksp_x64_2018-10-07_19-54-14](https://user-images.githubusercontent.com/8904620/46584992-f45ed580-ca6a-11e8-907d-1c6dfe84cd9d.png)

**Comment by gavazquez** [comment]
That happens as you're syncing your time with the server just after connecting to it. 
Making a "custom" timewarp method would take some work and be prone to errors.

Also this can't be patched as the message is posted inside a coroutine so I think we will have to live with this :/
