### ISSUE TITLE
Contracts List Diverges for Multiple Players

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#204]
OS: 
------------------------------------------------------------------------------
Win 10 x64

KSPVersion: 
------------------------------------------------------------------------------
1.4.5 Making History

LMP version
------------------------------------------------------------------------------
Nightly 0.13.50.828 / 27e3c5af

Current behaviour: 
------------------------------------------------------------------------------
Sometimes, contracts diverge on client machines. In particular, the following behaviours have been noticed:

1. Player takes new contract, other player doesn't see contract (but sees experimental parts associated with it)
2. Player solves contract, other player keeps it in their list (often "green", i.e. solved, but it sticks there probably until next recovery)
3. ~~Player solves contract, reconnects, same contract is there again.~~ (maybe a wrong observation)
4. Player can accept a contract AGAIN, even though the game already has that contract (e.g. active contract "Orbit Kerbin", can take again, can complete twice too)

Repro:
--------------------
Frequent, but somewhat random. (no sure way to repro).

**Comment by gavazquez** [comment]
Okay I tested in this way:

P1 and P2 are in KSC
P1 goes to Mission control and takes a contract of making a part test
P2 goes to Mission control and checks that there's a contract active that is the same as P1 took
P1 and P2 sees the experimental parts in R&D building
P1 takes a vessel and solves contract **but stays in flight**
P2 checks R&D and now there are no experimental parts
P2 checks mission control and contract is listed as SOLVED
P2 checks that there's NO repeated contract in mission control
P1 recovers it's vessel
P1 and P2 do the same checks of mission control and R&D and everything seems to be fine :)

**Comment by gavazquez** [comment]
I'll leave it open until you say it's bugfree ;)
