### ISSUE TITLE
Duplicate Facility Upgrades

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#210]
OS: 
------------------------------------------------------------------------------
Win 10 x64

KSPVersion: 
------------------------------------------------------------------------------
1.4.5 Making History

LMP version
------------------------------------------------------------------------------
Nightly 0.13.50.828 / Nightly 0.13.50.830 / 1eeb86583e765f2476ba3efdbcace185f613b311

Current Behaviour
-----------------------------
Upgrading a facility causes it to be upgraded twice.

1. Join a CAREER game server
2. Upgrade a Level 1 facility (i.e. 0 in code /  persistence)
3. Observe: Facility is Level 2 (i.e. 1 in code / logs,  because that counts from zero)
4. Leave server
5. Join server
6. Observe: Facility is upgraded to Level 3 now

**Comment by thygrrr** [comment]
I debugged it and it seems to be correctly saved on the server.

**Comment by thygrrr** [comment]
```         
public void LoadScenarioDataIntoGame()
 ```

This also seems to receive the correct data.

**Comment by thygrrr** [comment]
When Player 2 connects, and Player 1 upgrades a facility, the facility is the correct level for both.

Once a player reconnects, it's the incorrect level (3) for them, but not for the player who stayed in the server.

**Comment by thygrrr** [comment]
When completely disabling LoadGame through a patch, all the facilities seem to default to Level 3, so there is a chance that it has problems maybe parsing said info in / out of the persistent.sfs , or applies them to reach an invalid state which also defaults to 3.

**Comment by thygrrr** [comment]
Turns out:
```
		SpaceCenter/Administration
		{
			lvl = 0.5
		}
```

Wait, what?

**Comment by gavazquez** [comment]
Is the `ScenarioUpgradeableFacilities.txt` at the `Server/Scenarios` folder correct?
Does it has a correct value?

**Comment by thygrrr** [comment]
Not sure, running a clean test.

**Comment by thygrrr** [comment]
persistent.sfs (before reconnect)
--------
```
		SpaceCenter/LaunchPad
		{
			lvl = 0.5
		}
```
ScenarioUpgradeableFacilities.txt (immediately after upgrade)
-------------
```
SpaceCenter/LaunchPad
{
	lvl = 1
}
```

Server log
---------
```
[12:47:20][Debug] : Player acquired lock Contract
[12:47:20][Debug] : Player synced with subspace '0' created by Server
[12:47:29][Debug] : Performing backups...
[12:47:45][Debug] : Saving 7 scenario modules from Player
[12:47:54][Debug] : Funds received: 200000 Reason: StructureConstruction
[12:47:54][Debug] : Player Upgraded facility SpaceCenter/LaunchPad To level: 1
```

Crap, I was looking for the wrong number all along.

**Comment by thygrrr** [comment]
So, with the server relaying the correct update event to the other clients, I will now try to find out if this is a serialization issue on the server side.

**Comment by gavazquez** [comment]
Forget about the persistent.sfs file.

Whenever you connect to a server, the server sends you the scenario files and they are patched into the game "ScenarioRunner". We never read/use the persistent file

**Comment by thygrrr** [comment]
![rider64_2018-10-10_12-51-59](https://user-images.githubusercontent.com/8904620/46731558-4a11c880-cc8b-11e8-9bed-4d66a7f3c7b5.png)

**Comment by thygrrr** [comment]
I found it.

Level is not an int.

**Comment by gavazquez** [comment]
oooh fuck parsing error between a double and an int

**Comment by thygrrr** [comment]
"We never read/use the persistent file" <-- this is kinda true, kinda not. It is read by FlightDriver in FlyVessel(...), and saved by many functions before that.

In another test I tried to disable GamePersistence.SaveGame and LoadGame, but without LoadGame, the flight scene will have fully uninitialized data, i.e. nothing there to play (0.0000000 m/s strange orbit around Kerbin, no visible ship, etc.)

**Comment by gavazquez** [comment]
Mmm yes, it's "used" also when reverting and so on but LMP doesn't actively touch it but I know what you mean
