### ISSUE TITLE
MotD and Server Message are identical and both shown

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#211]
OS: 
------------------------------------------------------------------------------
Win 10 x64

KSPVersion: 
------------------------------------------------------------------------------
1.4.5 Making History

LMP version
------------------------------------------------------------------------------
Nightly 0.13.50.828 / Nightly 0.13.50.830 / 1eeb86583e765f2476ba3efdbcace185f613b311

Current Behaviour
------------------------------------------
![ksp_x64_2018-10-08_20-06-56](https://user-images.githubusercontent.com/8904620/46625838-b7abe080-cb35-11e8-8e91-1b458c9d8e9b.png)

**Comment by gavazquez** [comment]
Fixed
