### ISSUE TITLE
Part tolerances may change in immortality system

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#212]
Design question - aren't part tolerances variable between parts? (e.g. compare an engine to a service bay)
LT-45 engine `crashTolerance = 7` vs. 1.25m Service Bay `crashTolerance = 14`  vs. Materials Bay `crashTolerance = 6`

This code seems to set 9 gees for everything.

https://github.com/LunaMultiplayer/LunaMultiplayer/blob/142c0d38d0ed168e48232235c4c6e914243ab75d/LmpClient/Extensions/PartExtension.cs#L53

I think it's somewhat okay to do it this way as an intermediate solution but should be acknowledged that the tolerances may need to be reinstated at some later development stage. With many structural parts players use for impact shielding their landers, I'd say generally this increases the game difficulty significantly.

**Comment by gavazquez** [comment]
You're right... let me have a look if we can get it from the database....

**Comment by thygrrr** [comment]
Maybe you can pull it from the Protovessel.

I'm working on a mod that randomizes [proto]vessels a little bit based on tech level (think engineering tolerances), and certain mods such as DangIt! would probably keep the changed properties in the protovessel, per vessel.

**Comment by gavazquez** [comment]
you can access to the part definition trough `part.partInfo`

**Comment by gavazquez** [comment]
One of the weird things is that crashTolerance field is NEVER set in the code, I really don't know how KSP creates the parts and set those values....

**Comment by thygrrr** [comment]
I'd maybe suspect they are using a Deserializer, maybe even the Unity one even though I have no idea what its internal format it (it's not unlikely it's similar to how config nodes serialize)
