### ISSUE TITLE
Kerbals on Mission considered Lost on Server Start

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#213]
OS:
------
Win 10 x64

KSPVersion:
------
1.4.5 Making History

LMP version
------
Devel 0.14.51 / d8e77e052f3ce794ec44fb335ad87ca8fa78c26c , earlier versions too

Behaviour
-------
When starting the server, having a vessel somewhere that we were flying when the server was shut down, the kerbals in side it can be considered lost. Another user also reported that reverting can cause them to be dead/lost.

Expected Behaviour
--------
Kerbals on missions are not considered lost or dead.

Repro
---------
1. Start & Join Server
2. Put capsule on Launchpad (and fly it) [Crew would be considered "Assigned" in Astronaut Complex]
3. Stop server
4. Start server
5. Reconnect, find Craft On Launchpad where it was left
6. Observe: Crew is still onboard.
7. Click Astronaut Complex
8. Observe: Crew is considered Lost.
9. Recover Vehicle
10. Observe: Crew is considered Available.

**Comment by gavazquez** [comment]
Fixed ;)
