### ISSUE TITLE
[enhancement] Add general authorization system for LMP

### ISSUE THREAD

**Issue by DanGSun** [LunaMultiplayer/LunaMultiplayer#215]
Hello everybody!
What about auth system? I have one account (TimeLord, for example). Using player name as login, and allowing users to create their passwords. A user creates an account, LMP sends to master-server or another server his data, and then we will synchronize everything about this user.

For what we should do it?
I think the answer is simple.  You have a multiple PCs, and want to synchronize your data across them all.

I can realize a Python-Backend server with auth, etc.

**Comment by gavazquez** [comment]
Woudn't it be easier to just copy the "Universe" folder across servers?

**Comment by DanGSun** [comment]
No, I meant that I just have a user account. So I can authorize using it from any computer, but using only one nickname

**Comment by thygrrr** [comment]
Oops, somehow I mistyped #214 haha, this issue is not resolved.

But there is not need for authentication at this time, but there will be once we have player groups/agencies and private locked vehicles.

**Comment by DanGSun** [comment]
So maybe I should start writing backend?

**Comment by thygrrr** [comment]
Currently the server mostly archives scenarios and vessels, and relays the messages from the clients.

**Comment by gavazquez** [comment]
I would love to some day implement orbit physics on a separate DLL. That would actually allow us to create a totally new game.

This enhancement tough doesn't make sense
