### ISSUE TITLE
When I use wheels for a plane of mine the ship starts wobbling.

### ISSUE THREAD

**Issue by cominixo01** [LunaMultiplayer/LunaMultiplayer#220]
------------------------------------------------------------------------------

OS: Win 10 64x

------------------------------------------------------------------------------

KSPVersion: 1.4.5 no expansions

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.13.50 Stable

------------------------------------------------------------------------------

Expected behaviour: Ship does the same thing as in singleplayer

------------------------------------------------------------------------------

Current behaviour: The wheels won't stop wobbling, can even explode if it's fixed (only happens on the wheels used in this plane: https://i.imgur.com/2FgoNHM.png)

------------------------------------------------------------------------------

Steps to reproduce: Use the wheels shown on the picture above and use it on a plane

**Comment by thygrrr** [comment]
Can you send the .craft file?

**Comment by cominixo01** [comment]
Well it's working normally on the nightly build
