### ISSUE TITLE
Tracking Station bugs.

### ISSUE THREAD

**Issue by cominixo01** [LunaMultiplayer/LunaMultiplayer#221]
------------------------------------------------------------------------------

OS: Win 10 64x

------------------------------------------------------------------------------

KSPVersion: 1.4.5 no expansions

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.13.50 Stable

------------------------------------------------------------------------------

Expected behaviour: Tracking station shows correct position

------------------------------------------------------------------------------

Current behaviour: Sometimes it glitches saying that the vessel is flying to the Sun or somewhere else (which it's not). Some examples: https://cdn.discordapp.com/attachments/385163232798572564/500676256422166538/unknown.png https://cdn.discordapp.com/attachments/385163232798572564/500676513453047809/unknown.png

My guess it's due to time warping because the person in the future sees the future trajectory of the other.

------------------------------------------------------------------------------

Steps to reproduce: Try watching someone through the tracking station and time warping.

**Comment by gavazquez** [comment]
_Steps to reproduce: Try watching someone through the tracking station and time warping._

You mean that YOU are timewarping? or the OTHER player is timewarping?

**Comment by cominixo01** [comment]
Oh sorry for being vague, the times that happened I was timewarping, didn't happen always though. It might just be when you're out of sync and not when a specific player is timewarping

**Comment by gavazquez** [comment]
Does it still happens? I changed the positioning code quite a lot

**Comment by cominixo01** [comment]
I'll check when i'm home

**Comment by cominixo01** [comment]
From what I've seen this doesn't happen anymore

**Comment by gavazquez** [comment]
Perfect!
