### ISSUE TITLE
Kerbal is shown as dead

### ISSUE THREAD

**Issue by cominixo01** [LunaMultiplayer/LunaMultiplayer#223]
------------------------------------------------------------------------------

OS: Win 10 64x

------------------------------------------------------------------------------

KSPVersion: 1.4.5 no expansions

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.13.50 Stable

------------------------------------------------------------------------------

Expected behaviour: Kerbal is alive

------------------------------------------------------------------------------

Current behaviour: When I'm doing a mission, after some seconds the Kerbal screen on the left bottom corner goes noise, and when I hover the EVA button it says this: https://cdn.discordapp.com/attachments/386299658403840029/501032869138006046/unknown.png the way I counteracted this is going to the tracking station going back to the vessel and EVA and do whatever I want to do. It's quite annoying.

------------------------------------------------------------------------------

Steps to reproduce: Not sure, only happens sometimes

**Comment by thygrrr** [comment]
0.13.50 is a pretty broken build, I suggest we prepare a somewhat more stable release soon. :)

Trying to repro this bug on the nightly...

**Comment by thygrrr** [comment]
I think this was fixed in 0.14 ...

**Comment by gavazquez** [comment]
Yeah this was fixed in 0.14
Is it still hapening in nightly @cominixo01 ?

**Comment by cominixo01** [comment]
I don't think so, it's not happening anymore

**Comment by gavazquez** [comment]
Ok closing it
