### ISSUE TITLE
Rescue Contracts Cause NRE on CONNECT

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#226]
OS: 
------------------------------------------------------------------------------
Win10

KSPVersion: 
------------------------------------------------------------------------------
1.5.0 Making History

LMP version (include the build number if you are using a nighly build): 
------------------------------------------------------------------------------
0.14.51.828 / 7cfb4b906936d33597fe87fea5cb67df73785c31

Current behaviour: 
------------------------------------------------------------------------------
When connecting, a NullReferenceException is thrown in some advanced games (Rescue Contracts)

LOG Snippet
-----------------
```
[LOG 23:08:52.304] [LMP]: Contracts loaded.
[LOG 23:08:52.473] Warping to UT:10221698.8. Max Rate Allowed: 1.0x.
[LOG 23:08:52.475] [MessageSystem] Reposition 0.02 64301
[LOG 23:08:52.475] [GenericAppFrame] Reposition 0.02 64301
[LOG 23:08:52.475] [GenericAppFrame] Reposition 0.02 64301
[EXC 23:08:52.551] NullReferenceException: Object reference not set to an instance of an object
	Contracts.Templates.RecoverAsset.get_ProtoKerbal ()
	Contracts.Templates.RecoverAsset.Cleanup ()
	Contracts.Templates.RecoverAsset.OnOfferExpired ()
	Contracts.Contract.SetState (State newState)
	Contracts.Contract.Update ()
	Contracts.ContractSystem.UpdateContracts ()
	Contracts.ContractSystem+<UpdateDaemon>c__Iterator1.MoveNext ()
	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
[LOG 23:08:52.577] Real-time resumed. Current UT is: 10221698.9. TgtUT Error is 0.04s. (Overshot)
[LOG 23:08:52.619] [UIApp] Adding Missions App to Application Launcher
[LOG 23:08:52.620] ScaleModList: listSize 41 maxListSize 1433
[LOG 23:08:52.620] [UIApp] Adding Contracts to Application Launcher
[LOG 23:08:52.621] ScaleModList: listSize 41 maxListSize 1392
[LOG 23:08:52.629] [MissionsApp] OnAppStarted(): id: -317478
[LOG 23:08:52.629] MissionsApp does not execute in this game mode, destroying this instance
[LOG 23:08:52.629] [UIApp] OnDestroy: Missions App
```

**Comment by gavazquez** [comment]
Rescue contracts are a PIA... They create a vessel and a kerbal in the local roster. Syncing that is going to be a headache :/

This is how it works now:

P1: Accepts a rescue contract and the contract system spawns a vessel with id "X"
P2: Receives the contract update. And it spawns a vessel with id "Y"
P3: Connects and he doesn't see any new spawned vessel

For this reason I'm going to remove this contract type from LMP. Perhaps in a future this can be done but it's a hole of bugs atm
