### ISSUE TITLE
Mod or (better!) Server Compatibility must be limited to ONE version of KSP

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/LunaMultiplayer#227]
Currently, we support 1.4.x and 1.5.x 

... awesome, right?

... but that means that 1.4 and 1.5 players can play together on the same server.

**Comment by thygrrr** [comment]
(interestingly, I believe this causes the physics to glitch hard, which is amazing because it should not be happening)

Trying to verify.

**Comment by gavazquez** [comment]
Yeah the thing is that Jatwaa got a preview version of 1.5.0 and I wanted him to test LMP. After 1.5.0 was out i forgot to properly update the compatible version.

I already did it on: https://github.com/LunaMultiplayer/LunaMultiplayer/commit/3b068dc08d1ac6c42682711236b7c9f78a826ddf

But what do you mean making the server to be compatible with only 1 version?

**Comment by thygrrr** [comment]
That people might want to run a 1.5 or a 1.4 server, and that they could set that in the config.

However, just strictly supporting "latest KSP" is easier and I would prefer it.
