### ISSUE TITLE
Generate universe from saved game creates xml vessel files instead of txt

### ISSUE THREAD

**Issue by SloPro** [LunaMultiplayer/LunaMultiplayer#228]
Server OS: Ubuntu 18.04.1
Client OS: Windows 10
Version: 0.14.51.864-debug from Appveyor
___
I uploaded a singleplayer Universe that was converted using _Generate Universe from saved game_ and the server wouldn't start afterwards due to XML parsing errors.
**Cause**: the Universe/Vessels folder was full of files with .xml extensions instead of .txt. 
**Solution**: Renaming all Vessels/*.xml files to .txt makes the server work just fine

**Comment by cominixo01** [comment]
This might be related to #222 because I didn't test with vessels and thought it was fixed.

**Comment by SloPro** [comment]
Here is the exception https://cdn.discordapp.com/attachments/378456662392045573/502119232008355840/unknown.png

**Comment by cominixo01** [comment]
Seems like the same thing I was getting

**Comment by cominixo01** [comment]
I got it fixed, creating a PR in a sec
