### ISSUE TITLE
Career mode banned parts money remove

### ISSUE THREAD

**Issue by Sladernimo** [LunaMultiplayer/LunaMultiplayer#230]
------------------------------------------------------------------------------

OS: WIN7 SP1 x64

------------------------------------------------------------------------------

KSPVersion: Latest KSP Version (KSP + Expansion)

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build):  Latest LMP Nightly Version

------------------------------------------------------------------------------

MODS (add link to download them): No Mods

------------------------------------------------------------------------------

Expected behaviour: When starting a vehicle in career mode with banned parts from KSP I would expect that no money should be removed because vehicle is not spawned.

------------------------------------------------------------------------------

Current behaviour: When starting a vehicle in career mode with banned parts from KSP vehicle is not spawned but the money for it gets removed.

------------------------------------------------------------------------------

Steps to reproduce: Start a vehicle in career mode with banned parts from KSP.

**Comment by gavazquez** [comment]
Confirmed.

The check for banned parts happens in VesselProtoEvents.FlightReady()
Perhaps this should be done much earlier in the game, before the actual vessel is spawned in game
