### ISSUE TITLE
Stutter every ~10 seconds

### ISSUE THREAD

**Issue by SloPro** [LunaMultiplayer/LunaMultiplayer#235]
------------------------------------------------------------------------------

OS: client is Windows 10, server is Ubuntu 18.04.1 LTS

------------------------------------------------------------------------------

KSPVersion: 
1.5.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
14.51.893 nightly

------------------------------------------------------------------------------

MODS (add link to download them): 
Kerbal Engineer Redux but it happens without it as well

------------------------------------------------------------------------------

Expected behaviour: 
smooth gameplay, like in singleplayer

------------------------------------------------------------------------------

Current behaviour: 
0.3-0.5s stutter every 10ish seconds, irrelevant of where or what I am doing...
In the KSC overview, in the VAB, in the SPH, flying, on the moon, anywhere...
gets worse the longer your play session

PC specs: Xeon E3-1231v3, 12 GB RAM, R9 280 3GB, running on an SSD

------------------------------------------------------------------------------

Steps to reproduce: 
join the server and just move your view up and down slightly in KSC overview
GCMonitor MP: 
![image](https://user-images.githubusercontent.com/11058773/47270556-b59e4480-d56d-11e8-9d66-e920a92eb1a4.png)

GCMonitor SP: 
![image](https://user-images.githubusercontent.com/11058773/47270545-943d5880-d56d-11e8-8f9d-cd0eacf48035.png)

Universe: 
[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2499464/Universe.zip)

**Comment by gavazquez** [comment]
Fixed it
