### ISSUE TITLE
Master Warp Config

### ISSUE THREAD

**Issue by SupperRobin6394** [LunaMultiplayer/LunaMultiplayer#236]
Master warp itself has been removed, but the config file for warp settings (WarpSettings.xml) still shows the following setting:

  <WarpMaster />

Cheers!

**Comment by gavazquez** [comment]
That's because your settings file is old:

![image](https://user-images.githubusercontent.com/12727761/47395938-17ef7480-d729-11e8-8e72-64550adaba76.png)

**Comment by gavazquez** [comment]
mm wait ok yes the warp master username is still there. going to delete it

**Comment by SupperRobin6394** [comment]
I just downloaded the latest release (stable), sooooo I doubt I got outdated files haha

**Comment by gavazquez** [comment]
Yep. fixed in nightly
