### ISSUE TITLE
Vessel stages collide/explode when a spectating player takes control

### ISSUE THREAD

**Issue by HughesMDflyer4** [LunaMultiplayer/LunaMultiplayer#237]
**Universe/Config Contents:** https://www.dropbox.com/s/5qr3xcy9uuw6ly2/Server.zip?dl=0
**Craft:** https://www.dropbox.com/s/h0lswze5isyyn8l/Boom.craft?dl=0

**OS:** Windows 10
**KSP Version:** 1.5.1
**LMP version:** 0.15.0
**Mods:** None

**Expected behavior** 
Spectating players should be able to take control of separated stages immediately after staging, and fly them away without damaging other stages.

**Current behavior**
After two stages separate on a multistage vessel and a spectating player immediately/nearly immediately takes control of one of the stages, a collision/teleporting can occur and the vessels collide. With the same server configs/craft, this did not happen in KSP 1.4.5/LMP 0.13.50.

Below is a gif of 3 scenarios. The first 2 are from KSP 1.5.1/LMP 0.15.0, and the third is from KSP 1.4.5/LMP 0.13.50 to show it working fine in a previous version. Note that while in the second scenario there was no explosion, waiting longer before taking control does seem to affect things, and you can see the upper stage teleport lower down.
https://gfycat.com/gifs/detail/UniformZestyBackswimmer

**Steps to reproduce**
1. Load up the supplied server configs and craft file.
2. Have a second player spectate the launch as soon as liftoff occurs.
3. Fly the vessel up to about 28,000m (with a slow gravity turn heading East - see above gif for target pitch) and trigger staging. Remain in control of the lower stage.
4. 1-3 seconds after staging, have the second player switch focus to the upper stage.
5. The lower stage should explode.

**Comment by gavazquez** [comment]
This should be fixed in latest version as there was a race condition with the locks

**Comment by HughesMDflyer4** [comment]
@gavazquez Thanks for following up on this! Unfortunately, we're seeing the same issue in 0.17.0. :(

**Comment by gavazquez** [comment]
I added some code in the nightly version (https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/How-to-get-nightly-builds) It's not 100% perfect but I don't think I can do much more as the code of KSP that instantiates vessels is quite bad.

Let me know if this at least helps it a bit

**Comment by HughesMDflyer4** [comment]
No noticeable change with the nightly build (client and server updated). If it would help, I'm available via Discord if you want to do more rapid testing. I'm part of the LMP server, same username as GitHub (as well as my friend, who is GameSyns on the LMP Discord).

**Comment by gavazquez** [comment]
ok will contact you once I have some more fixes that I'm doing atm :)

**Comment by HughesMDflyer4** [comment]
So that's definitely a step in the right direction. We're able to have successful change of control now at least, however the second stage pilot must take control _immediately_, otherwise the stages will collide a second or two after separation. Some funky desync seems to occur if they do collide - my friend saw my first stage broken up, even though it was fine.

**Comment by gavazquez** [comment]
Ok will have a look again

**Comment by HughesMDflyer4** [comment]
Sorry for the delay in responding - that does seem to have fixed it. Thanks!
