### ISSUE TITLE
Is it possible to run servers on MacOS?

### ISSUE THREAD

**Issue by Codebreakerblue** [LunaMultiplayer/LunaMultiplayer#243]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
MacOS X 10.12.6
------------------------------------------------------------------------------

KSPVersion: 
1.5.1
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
Server 0.15.0
------------------------------------------------------------------------------

MODS (add link to download them): 
N/A
------------------------------------------------------------------------------

Expected behaviour: 
Starting server via Terminal, 'mono server.exe'; Server loads into terminal, I then connect via the clientside menu in KSP.
------------------------------------------------------------------------------

Current behaviour: 
Server begins loading in terminal window; loads universe, groups, settings, modcontrol, and plugins; opens port 8800 and 8900. Fatal error; Exception: System.NotImplementedException: The method or operation is not implemented.
-----------------------------------------------------------------------------

Steps to reproduce:
 In Terminal, in correct directory, "mono server.exe"

[lmpserver_2018-10-27_16-18-37 copy.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2522280/lmpserver_2018-10-27_16-18-37.copy.log)

**Comment by cominixo01** [comment]
I remember seeing something similar, this is what I found https://forums.xamarin.com/discussion/67375/osx-getactivetcplisteners-not-implemented-system-net-networkinformation-ipglobalproperties
Apparently it was never implemented in OSX

**Comment by Codebreakerblue** [comment]
Well, shoot.
Thanks for the info!

**Comment by Codebreakerblue** [comment]
should I close this issue or leave it open?

**Comment by cominixo01** [comment]
Leave it open, I guess. It might be possible to implement

**Comment by gavazquez** [comment]
I don't have a Mac so not possible for me to fix this.
