### ISSUE TITLE
No money back when reverting the flight

### ISSUE THREAD

**Issue by Erdroy** [LunaMultiplayer/LunaMultiplayer#244]
Hello!
There is no money back when reverting the flight.

--
I know that this might get tricky to fix. AFAIK there is no costs sent to the server nor there is no way to calculate vessel cost on the server side - beside checking money diff when new vehicle is being launched.

**Comment by Sladernimo** [comment]
As far as I know reverting is not really supported by LMP atm and maybe never will be...

Like Nightmare wrote at Discord:
"To simply put is reverting is not supported by lmp in a way like it is in singelplayer
it simply kills your ship but sets you not back in time
so kerbals dead money gone"

**Comment by gavazquez** [comment]
No way to get money back in career and multiplayer. To be honest I will probably disable revert for career in LMP as this just generates too much crap
