### ISSUE TITLE
Explosion on Dock

### ISSUE THREAD

**Issue by prestonfaiks** [LunaMultiplayer/LunaMultiplayer#247]
OS: Windown 10

------------------------------------------------------------------------------

KSPVersion: 1.5.1.2335

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.15.0
------------------------------------------------------------------------------

MODS (add link to download them): 
Attached as mods_list.txt
------------------------------------------------------------------------------

Expected behaviour: 
Docking does not explode
------------------------------------------------------------------------------

Current behaviour: 
Explosion after docking, 
Only happens when connected to server, 1 user.
Playing saved game standalone does not explode.
Occurs about 50% of the time with LMP with these same vehicles, but not all docking events explode.
------------------------------------------------------------------------------

Steps to reproduce: 
The saved game can be used to create the situation just prior to docking.  Minimal/no steering required, just drift in and watch.  

[logs.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2568072/logs.zip)

Thanks for maintaining and updating this Mod,

-Preston

**Comment by gavazquez** [comment]
Fixed it with the lock system in the latest release

**Comment by Zappyfuel** [comment]
@gavazquez ik you might believe its fixed and i am not trying to contest your belief but when we and my friend went to dock in low kerbin orbit on 7th of december 2023 when docking, on my screen the dock was succesful however on my friends screen his vessel blew up and only had half of his vessel was left if you reply back asking for video proof then i will get a video showing my problem.
