### ISSUE TITLE
Subspace syncing between atmospheric player and space player causes de-sync

### ISSUE THREAD

**Issue by Twoseventyone** [LunaMultiplayer/LunaMultiplayer#248]
When syncing between subspaces when one player is in-atmosphere and the other is in space, a de-sync will occur which will result in spastic orbits for other vessels for the side that performed the sync.
This may result in the vessel being destroyed and removed if it was landed in atmosphere, or crash through terrain in other situations.
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10, Windows 7

------------------------------------------------------------------------------

KSPVersion: 1.5.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.16.999.32

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: Subspace syncs smoothly

------------------------------------------------------------------------------

Current behaviour: Sync causes ship position de-sync

------------------------------------------------------------------------------

Steps to reproduce: 
1. Have two players present: One controlling a ship in flight in atmosphere, the other a ship in space.
2. Have one of them perform warp.
3. Sync subspace.
4. Check map.

**Comment by gavazquez** [comment]
Hi! Thanks a lot for taking the effort of providing a good bug report!! I think I managed to fix it but let me know if there's still some edge case
