### ISSUE TITLE
Timed out after building a ship larger than ~190KBytes

### ISSUE THREAD

**Issue by Scooter1337** [LunaMultiplayer/LunaMultiplayer#252]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2626399/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2626404/output_log.txt)
[Config and Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2621919/Config.and.Universe.zip) (I used a brand new universe so only mind the config :))

Tests I executed:

With mods, private server: I get disconnected (0.16.0 + 0.17.0)
Without mods, private server: I get disconnected (0.16.0 + 0.17.0)
Public server: I get disconnected (0.17.0)
Friend of mine, private server: Does not get disconnected with(out) mods (0.16.0)

Turning off McAfee Net guard does NOT work.
Turning off McAfee Firewall does NOT work.

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------
OS: 
Windows 10 Home
------------------------------------------------------------------------------
KSPVersion: 
1.5.1.2235
------------------------------------------------------------------------------
LMP version: 
0.17.0 (Want to update but my server administrator has not responded to my request yet.)
------------------------------------------------------------------------------
MODS:

- Lunamultiplayer 0.16.0/0.17.0 Client

------------------------------------------------------------------------------
Expected behaviour: 
Letting me fly my ship and actually logging that I did so, AKA not getting timed out. :)
------------------------------------------------------------------------------
Current behaviour: 
Kicking me from any server
------------------------------------------------------------------------------
Steps to reproduce: 

1. Download and run KSP

2. Add LMP to your gamedata folder 

3. Join your/a server  

4. Create a pretty large spaceship, screenshot [here](https://imgur.com/a/tTSSAJr). (This screenshot also shows the in-game message I get after timing out.)

5. Get kicked / Timed out after being spammed with [these](https://imgur.com/a/eCCxs60) messages in your server log

**Comment by Scooter1337** [comment]
Will test my problem on a public server tomorrow, have to download 0.17 and I do not have the time to do that right now.

**Comment by gavazquez** [comment]
I don't think that the issue is on the vessel. The issue is on the amount of mods that you use. We don't support other mods specially the ones that modify KSP to a huge extent like  "KSP Interstellar Extended".

You can try to increase the timeout both in server and on client but I don't think that this is caused by LMP

**Comment by Scooter1337** [comment]
> I don't think that the issue is on the vessel. The issue is on the amount of mods that you use. We don't support other mods specially the ones that modify KSP to a huge extent like "KSP Interstellar Extended".
> 
> You can try to increase the timeout both in server and on client but I don't think that this is caused by LMP

I tested it without any mods, my friend doesn't seem to have this problem either with or without mods. I think it is the security on my internet causing something weird
