### ISSUE TITLE
Career mode tourists are not removed after contract completion

### ISSUE THREAD

**Issue by Bonkeybee** [LunaMultiplayer/LunaMultiplayer#254]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2646855/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2646856/output_log.txt)
[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2646860/LMPServer.zip)

OS: Windows 10 Pro
KSPVersion: 1.5.1.2335 x64
LMP version: 0.18.0

Expected behaviour: (Tourist contracts should be disabled???)

Current behaviour: Tourist contract found in misson control and if accepted and completed, tourists will remain in kerbal crew list.

Steps to reproduce: Go to mission control and accept tourist contract. Add tourist to vessel, launch, and complete contract. Tourists remain in the kerbal crew list after contract completion (even have flight experience).

![lmp-bug-report](https://user-images.githubusercontent.com/9619823/49485578-1a052280-f801-11e8-856f-a649ceac3add.png)

**Comment by gavazquez** [comment]
Tourists contracts are not supported: https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Limitations

**Comment by Bonkeybee** [comment]
Yes... I read that but it also says they should be disabled. They are not disabled.

**Comment by gavazquez** [comment]
Yep, will check why they are not disabled. I don't play career anyway so I don't waste efforts on this

**Comment by gavazquez** [comment]
Just pushed a fix on nightly version. Let me know if that fixes it

**Comment by jeq1** [comment]
problem is still there now with 1.12 kerbal. tourists doesn't get disabled.

**Comment by Belkon** [comment]
+1
