### ISSUE TITLE
Can't rendezvous in orbit due to time sync jump

### ISSUE THREAD

**Issue by sgtnoodle** [LunaMultiplayer/LunaMultiplayer#255]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Linux

------------------------------------------------------------------------------

KSPVersion: Kerbal Space Program - 1.5.1.2335 (LinuxPlayer) en-us

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
https://github.com/LunaMultiplayer/LunaMultiplayer/releases/download/0.18.0/LunaMultiplayer-Release.zip

------------------------------------------------------------------------------

MODS (add link to download them): 
Installed through ckan:
Chatterer
DistantObject
KerbalEngineer
MechJeb2
MechJebForAll

------------------------------------------------------------------------------

Expected behaviour: 

I time warp until my ship is within 200m of a space station and then do an engine burn to match velocities. My ship should remain 200m away from the space station.

------------------------------------------------------------------------------

Current behaviour:

I time warp until my ship is within 200m of my space station and then match velocities. Suddenly, the space station is 7km away!

------------------------------------------------------------------------------

Steps to reproduce:

Put a space station in orbit. Try to approach it with another ship.

Attached is my KSP.log. It looks to me like a time syncing issue?

I'm not sure where my output_log.txt lives because I'm in linux, but I can try to find it if it's important. I also shut down my server. I don't want to share the config files without sanitizing them first, but let me know if it's 

[LOG 22:20:11.759] Real-time resumed. Current UT is: 362723.6. TgtUT Error is 0.0055s. (Overshot)
[LOG 22:20:11.773] Unpacking Station Ring
[LOG 22:20:11.774] Unpacking Station 125K - Fuel, Ore Processing and Fun
[LOG 22:20:11.810] [LMP]: Locked to subspace 80, time: 362723.633612819
[LOG 22:20:14.949] RCS lock/unlock
[LOG 22:20:18.495] RCS lock/unlock
[LOG 22:20:36.492] RCS lock/unlock
**[WRN 22:20:46.294] [LMP] Adjusted time from: 362754.629481848 to: 362758.137279319 due to error: -3507.80147110345**
[LOG 22:20:46.294] Packing Station 125K - Fuel, Ore Processing and Fun for orbit
[LOG 22:20:46.333] Station 125K - Fuel, Ore Processing and Fun Unloaded
[LOG 22:20:46.411] ScaleModList: listSize 205 maxListSize 1093
[LOG 22:20:46.492] ScaleModList: listSize 205 maxListSize 1093

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2651914/KSP.log)

**Comment by gavazquez** [comment]
Your game clock lags too much (3,5 sec) and then LMP syncs the game clock. Either your space station has too many parts and it's difficult to handle by your computer or perhaps the game is running very slow and with very few fps
