### ISSUE TITLE
Connect button doesn't work with URLs, only dot-decimal

### ISSUE THREAD

**Issue by prestonfaiks** [LunaMultiplayer/LunaMultiplayer#256]
OS: Windows 10
KSPVersion: 1.5.1.2335 (windows 64-bit)
LMP: 0.19.0 Release

Expected behaviour: 
Clicking the connect icon will initiate login to server.
"Connecting To : xxx" will be displayed on the bottom of the login window.

Current behaviour: 
When using a URL, connect does nothing and no "Connecting To" text appears.
Using a dot-decimal IP works as expected..

**Comment by gavazquez** [comment]
I fixed that on the commit: https://github.com/LunaMultiplayer/LunaMultiplayer/commit/c75a0680f23f180ce73d48a40712ffd3618c7bb5

Can you try it with nightly version?

**Comment by prestonfaiks** [comment]
Confirmed fixed with the nightly.
