### ISSUE TITLE
Kerbals lose all levels on relog

### ISSUE THREAD

**Issue by OmniTitan** [LunaMultiplayer/LunaMultiplayer#259]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows

------------------------------------------------------------------------------

KSPVersion: 1.5.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.19.0

------------------------------------------------------------------------------

MODS (add link to download them): KerbalEngineer, Mechjeb

------------------------------------------------------------------------------

Expected behaviour: Pilot levels are saved

------------------------------------------------------------------------------

Current behaviour: Pilot levels are reset on logging into the server

------------------------------------------------------------------------------

Steps to reproduce: Level up pilot, log out and then back in again and pilot will be back to 0.
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2711678/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2711682/output_log.txt)

**Comment by gavazquez** [comment]
Should be fixed in nightly
