### ISSUE TITLE
LMP Deleting Modular Vessels after Decoupling and Warping.

### ISSUE THREAD

**Issue by Jedmeyer** [LunaMultiplayer/LunaMultiplayer#265]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10 Pro

------------------------------------------------------------------------------

KSPVersion: 1.6.1.2401

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 20.0

------------------------------------------------------------------------------

MODS (add link to download them): 
BonVoyage 0.14.3.0 
(https://github.com/jarosm/KSP-BonVoyage/releases)
Kerbal Engineer Redux 1.1.3  
(https://forum.kerbalspaceprogram.com/index.php?/topic/17833-130-kerbal-engineer-redux-1130-2017-05-28/)
Final Frontier 
(https://forum.kerbalspaceprogram.com/index.php?/topic/61065-160-final-frontier-kerbal-individual-merits-153-3465/)
SCANSat 18.10 
(https://github.com/S-C-A-N/SCANsat/releases/tag/v18.10)
[x] Science! 5.17
(https://forum.kerbalspaceprogram.com/index.php?/topic/107661-ksp-145-x-science-ksp-science-report-and-checklist-v517/)
-----------------------------

Expected behaviour: Created a Modular Craft - One that has several usable craft within it that can be deployed after Decoupling from Docking Nodes. Flew to Orbit of Body of Interest (Mun), and Decoupled. Decoupled Craft and Origin Craft should then be individually handled.

------------------------------------------------------------------------------

Current behaviour: Upon Decoupling and Warpng - Craft was Deleted by LMP after distance was greater than ~85Km. 
Vessel was deleted by LMP at 20:19:03 in the server log.

------------------------------------------------------------------------------

Steps to reproduce: 
I was able to reproduce the issue:
Build a Modular Craft (I have included mine in the ZIP File)
Fly it to Low Mun Orbit.
Decouple a child craft, and move away using RCS
Switch to Child Craft
Warp
Parent Craft will be deleted.

Edit: I've concluded this is a manifestation of the Warp Issue #263, as when replicating a 3rd time, the parent craft lost its orbital velocity as described in #263. I've also confirmed this occurs with the latest release 4 days ago.

[LMP-Issues.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2753515/LMP-Issues.zip)

**Comment by gavazquez** [comment]
Same as #263 so closing this issue
