### ISSUE TITLE
Subspace.txt not created when creating Universe from a saved game.

### ISSUE THREAD

**Issue by prestonfaiks** [LunaMultiplayer/LunaMultiplayer#266]
Version 0.20.2 (not new, also affects earlier versions)

Recreate Issue:
Create a Universe from a saved game and move it to the server, replacing the existing one.
Re-start server and connect.
 
When the server starts a Universe without a Subspace.txt file, the time is reset to 0 resulting in:
1) The spacecraft (Vessels/*.txt) has lastUT < lct wich results in negative met
2) The game thinks you are warping and you have no control

Workaround:
Use the persistent.loadmeta file's UT value to populate the Subspace.txt with 0:< UT >

Notes:
I have run into this same issue in the past when I had game crashes, and then re-connected with the server once the game reloaded.  In those instances, only a short amount of time was out of sync, so warping in-game restored controlability.

**Comment by gavazquez** [comment]
Thanks. Should be fine now in nightly
