### ISSUE TITLE
Query Protocol?

### ISSUE THREAD

**Issue by Aterfax** [LunaMultiplayer/LunaMultiplayer#268]
Not seen any documentation on how to query the running servers to see if they are live?

Do they follow the DMP query protocol?

**Comment by gavazquez** [comment]
It works with a master server system. You can read the details in the wiki
https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Master-server

**Comment by Aterfax** [comment]
Ah excellent! Might need to make things a bit more clear in documentation.  Thanks!
