### ISSUE TITLE
Webserver Response Includes Headers in content?

### ISSUE THREAD

**Issue by Aterfax** [LunaMultiplayer/LunaMultiplayer#269]
Should be an easy one to debug and I am not sure if I am having some kind of OS based issue with curl however when I am calling the webserver I am getting the HTML response header at the bottom of the data where I do not expect it unless I am calling for it with -i or -I

e.g. 
```
.....truncated.....
    "ServerConnectionSettings": {
      "Port": 27028,
      "HearbeatMsInterval": 1000,
      "ConnectionMsTimeout": 30000,
      "Upnp": true,
      "UpnpMsTimeout": 5000,
      "MaximumTransmissionUnit": 1408,
      "AutoExpandMtu": false
    },
    "ServerWebsiteSettings": {
      "EnableWebsite": true,
      "Port": 8900,
      "RefreshIntervalMs": 5000
    }
  }
]HTTP/1.1 200 Ok
Date: Sun, 20 Jan 2019 15:37:12 GMT
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 23186

```

Incidentally, calling curl with -I should only give the response header output and instead gives 

```
curl: (8) Weird server reply
```

Not sure what to make of it, since I only have Debian and Ubuntu to test with it may be an OS based issue?

I did try this with wget and it appeared to have the same behaviour as the former.

------------------------------------------------------------------------------

OS:  Debian and Ubuntu

------------------------------------------------------------------------------

KSPVersion: N/A

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build):  0.20.2

------------------------------------------------------------------------------

Expected behaviour:  curl to not be including headers unless explicitly called via command line argument.

------------------------------------------------------------------------------

Current behaviour: curling the webserver finishes the data output with the HTTP response header.

------------------------------------------------------------------------------

Steps to reproduce: curl the webserver on LMPServer.

**Comment by godarklight** [comment]
Fixed in 404eefcd9d50084207097bc17f5527721c260537
