### ISSUE TITLE
Contract Tourist Kerbals Remain After Contract Completion 

### ISSUE THREAD

**Issue by dtrent1** [LunaMultiplayer/LunaMultiplayer#271]
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.6.1.2401

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.20.2

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: Tourist Kerbals will be removed from the available astronauts list once contract is complete

------------------------------------------------------------------------------

Current behaviour: Tourist Kerbals remain in available astronaut list after contract is complete

------------------------------------------------------------------------------

Steps to reproduce: Accept VIP Tour contract, complete contract with VIP tourist Kerbal, Kerbal remains in available astronaut list

**Comment by gavazquez** [comment]
Tourist contracts are disabled. Very difficult to sync them across clients
