### ISSUE TITLE
Vessel explodes for no reason, and the terrain shakes.

### ISSUE THREAD

**Issue by JellyBrick** [LunaMultiplayer/LunaMultiplayer#274]
------------------------------------------------------------------------------

OS: Windows 10 (64bit) 

------------------------------------------------------------------------------

KSPVersion: 1.6.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.20.2

------------------------------------------------------------------------------

MODS (add link to download them): MechJeb2

------------------------------------------------------------------------------

Expected behaviour: The Vessel must be able to fly without damage unless shocked.

------------------------------------------------------------------------------

Current behaviour: Vessel crumples and explodes for no reason, and terrain shakes violently.

------------------------------------------------------------------------------

Steps to reproduce: 

1. Load the default Vessel "`Stratolauncher`".
2. Start the flight on the runway.

**Comment by gavazquez** [comment]
Could not reproduce on latest KSP version
