### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by CHazz** [LunaMultiplayer/LunaMultiplayer#276]
hi server working good, but when try restart from command line or game admin menu get this error.
thanks for help 

[21:06:58][LMP]: Restarting...  Please wait until all threads are finished
[21:06:59][LMP]: So long and thanks for all the fish!

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'LmpCommon, Version=0.20.2.192, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'LmpCommon, Version=0.20.2.192, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'LmpCommon, Version=0.20.2.192, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'LmpCommon, Version=0.20.2.192, Culture=neutral, PublicKeyToken=null'

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: ubuntu 16.04

------------------------------------------------------------------------------

KSPVersion: 1.6.1

------------------------------------------------------------------------------

LMP version latest nightly: 

------------------------------------------------------------------------------

MODS (add link to download them): 

------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 

------------------------------------------------------------------------------

Steps to reproduce:

**Comment by Aterfax** [comment]
I'm fairly sure I have also seen this happen.

**Comment by gavazquez** [comment]
It seems that some of the dll's are missing on the folder. reinstall the server
