### ISSUE TITLE
100% CPU drain on one core, when running as daemon

### ISSUE THREAD

**Issue by Ochlup** [LunaMultiplayer/LunaMultiplayer#278]
hello when I run Luna with a mono working good and have a normal "low" cpu usage .. but when I try run as daemon with mono-service or daemon .. Luna (mono) takes 100% on one cpu core (normal 1-20% ), it's pretty unpleasant. please help  ( tested on two servers and the same results)

thank you :)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: ubuntu 16.04 and 18.04

------------------------------------------------------------------------------

KSPVersion: 1.6.1but any .. its iddle state

------------------------------------------------------------------------------

LMP version 0.20.2.192

------------------------------------------------------------------------------

MODS (add link to download them):  with any mods or server settings

------------------------------------------------------------------------------

Expected behaviour: 
same cpu drain with daemon and pure mono
------------------------------------------------------------------------------

Current behaviour: 
high cpu drain when running as daemon
------------------------------------------------------------------------------

Steps to reproduce: 
mono-service  /LMPServer/Server.exe

**Comment by gavazquez** [comment]
I'm no linux expert so can't help on that

**Comment by zocker-160** [comment]
what version of mono are you using?
extremely high CPU usage is a known bug in mono 4.2.3.4 - 4.8
there are reports that version 5.16 is affected as well

it shouldn't be an issue with the latest 5.18 / 5.20 though

**Comment by CHazz** [comment]
currently latest nightly  6.3.0.688 .. but latest stable on all machines and on ubuntu 16.04 , ubuntu 18.10. mint 19.1 , debian 10 .. same bug ..  when running with pure mono (Mono Server.exe its ok.. but useless) Monoservice is buged still get 100% on one core ..

**Comment by gavazquez** [comment]
No idea about this. @godarklight do you know something about this? Does it happens in DMP aswell?

**Comment by CHazz** [comment]
DMP running normal but .. DMP is crap for me :(

**Comment by royalmustard** [comment]
This problem still persists. I am currently running LMP 0.25.0 with mono  6.8.0.105.
When running just with mono everything is fine (around 20% CPU when noone is on the server), but when running it as a service with systemd, CPU rises to 150% instantly (100% being one core fully utilized). I think this might be an underlying issue with mono.

**Comment by gavazquez** [comment]
This is not something we can control so I'm closing the issue. 
You should ask to the mono repo or in a linux forum

https://unix.stackexchange.com/questions/191621/systemd-service-using-100-of-my-cpu-when-it-doesnt-if-i-start-it-without-syste

https://stackoverflow.com/questions/55641233/systemd-service-using-100-of-my-cpu-when-start-as-service-and-it-doesnt-if-i-s

**Comment by CHazz** [comment]
links is for problem with systemd .. this problem is with monoservice + lmp .. process monoservice stuck one core on system .. a try lots of aps .. but problem is only with LMP :(  a pity that LMP is "windows only" most servers are exclusively under linux/unix and emulators are useless .. it slows down the applications and creates unnecessary bugs :(
