### ISSUE TITLE
LMP Master - Rejecting Auto-Requests

### ISSUE THREAD

**Issue by SupperRobin6394** [LunaMultiplayer/LunaMultiplayer#284]
For some reason, an automated HTTP request to any master server returns absolutely nothing, some Discord user I forgot who also had the same issue whilst a 'manual' request does return JSON.

Idk what else to write.

**Comment by gavazquez** [comment]
No idea about automated requests but a simple GET request against http://masterserver:port/json returns json data

Example: http://servers.lunamultiplayer.com:8701/json

![image](https://user-images.githubusercontent.com/12727761/56069807-08babc80-5d85-11e9-805c-1c7c830ebdc1.png)
