### ISSUE TITLE
NRE during BDAMultiplayer development

### ISSUE THREAD

**Issue by jrodrigv** [LunaMultiplayer/LunaMultiplayer#286]
I have seen some NREs during my testing, everything ended in a fatal crash.

> ApplyInterpolations: System.IndexOutOfRangeException: Array index is out of range.
>   at (wrapper stelemref) object:stelemref (object,intptr,object)
>   at System.Threading.Tasks.CircularArray`1[LmpClient.Systems.VesselPositionSys.VesselPositionUpdate].Grow (Int32 bottom, Int32 top) [0x00000] in <filename unknown>:0 
>   at System.Threading.Tasks.CyclicDeque`1[LmpClient.Systems.VesselPositionSys.VesselPositionUpdate].PushBottom (LmpClient.Systems.VesselPositionSys.VesselPositionUpdate obj) [0x00000] in <filename unknown>:0 
>   at System.Collections.Concurrent.ConcurrentBag`1[LmpClient.Systems.VesselPositionSys.VesselPositionUpdate].Add (LmpClient.Systems.VesselPositionSys.VesselPositionUpdate item) [0x00000] in <filename unknown>:0 
>   at LmpClient.Base.CachedConcurrentQueue`2[T,TD].Recycle (.T item) [0x00000] in <filename unknown>:0 
>   at LmpClient.Systems.VesselPositionSys.VesselPositionUpdate.UpdateVesselWithPositionData () [0x00000] in <filename unknown>:0 
>   at LmpClient.Systems.VesselPositionSys.VesselPositionUpdate.ApplyInterpolatedVesselUpdate () [0x00000] in <filename unknown>:0 

And also this one:

> [LMP]: ApplyInterpolations: System.Collections.Generic.KeyNotFoundException: 4b31cdc6-7a57-4f53-8458-fb8ee470bf55
>   at System.Collections.Concurrent.ConcurrentDictionary`2[System.Guid,LmpClient.Systems.VesselPositionSys.PositionUpdateQueue].GetValue (Guid key) [0x00000] in <filename unknown>:0 
>   at System.Collections.Concurrent.ConcurrentDictionary`2[System.Guid,LmpClient.Systems.VesselPositionSys.PositionUpdateQueue].get_Item (Guid key) [0x00000] in <filename unknown>:0 
>   at LmpClient.Systems.VesselPositionSys.VesselPositionUpdate.UpdateVesselWithPositionData () [0x00000] in <filename unknown>:0 
>   at LmpClient.Systems.VesselPositionSys.VesselPositionUpdate.ApplyInterpolatedVesselUpdate () [0x00000] in <filename unknown>:0 

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2989724/KSP.log)

**Comment by gavazquez** [comment]
There seems to be a bug in the implementation of the concurrent bag. Unfortunately that's MS code and quite complex :/
