### ISSUE TITLE
[Feature Request]: Non-shared progress

### ISSUE THREAD

**Issue by Mushoz** [LunaMultiplayer/LunaMultiplayer#288]
Would it be possible to get a non-shared progress science/career mode? I would love to do a space-race with friends and see who can reach X first, while having to get sufficient funds/science to be able to do so. Currently with science and funds being shared, it doesn't really matter who progresses the most. Only the final flight to get to X will matter.

Thanks!

**Comment by gavazquez** [comment]
Yep. It was on the pendings and it's a very requested feature but it will take a lot of time and I'm the sole developer
