### ISSUE TITLE
CommNet Bug

### ISSUE THREAD

**Issue by Alfred-PictoCube** [LunaMultiplayer/LunaMultiplayer#290]
KSPVersion: 
1.6 / 1.7

------------------------------------------------------------------------------

LMP version:  
Tested on Release branch 0.20.2 (KSP 1.6.1) and nightly 0.21.0.204 (KSP 1.7).

------------------------------------------------------------------------------

MODS: 
No mods, stock server, AllowNonListedPlugins = false.

------------------------------------------------------------------------------

Current behaviour: 
Both vessels, or each vessel tested separately will break CommNet for all existing vessels in the universe. Adding new vessels will also result their communications to be deactivated. 
Deleting both vessels fixes the issue.
**Note:** both vessels were working fine for a few days before this happened. No idea how it really started. Nobody has controlled or spectated the bugged vessels prior this began.

------------------------------------------------------------------------------

Steps to reproduce: 
Add one or both vessels in your "Vessels" folder and start the server.
Try either launching a new vessel or if you already have vessels around, check what happens by going to the tracking station.

[89b62a12-5ac2-4067-bceb-ef5def28245b.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3075514/89b62a12-5ac2-4067-bceb-ef5def28245b.txt)
[c9ea7a22-d69a-4822-b1ed-c54c9dc8d9d8.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3075515/c9ea7a22-d69a-4822-b1ed-c54c9dc8d9d8.txt)

**Comment by gavazquez** [comment]
This seems to happen because those 2 vessels have crew that doesn't exist in your KerbalRooster

If you look at the vessel node:
You will see somth like: 	`crew = Katoly Kerman`

Check if that kerbal exists in the Universe/Kerbals folder

I will think about fixing that automatically however....

**Comment by Alfred-PictoCube** [comment]
I can't give you more details as we switched on a fresh universe since. 
But i remember i once dropped a kerbal outside that ship and then focused on other tasks.
When i took back control he had disappeared (as a recurring situation, kerbals on EVA tended to vanish).
However, Commnet was still working well and the issue only started a few days later.
