### ISSUE TITLE
Cannot connect to any servers, "username already taken"

### ISSUE THREAD

**Issue by guillermofbriceno** [LunaMultiplayer/LunaMultiplayer#293]
OS: Fedora 29, Kernel 5.0.16-200 x86_64

------------------------------------------------------------------------------

KSP Version: 1.7

------------------------------------------------------------------------------

LMP version: 0.21.0

------------------------------------------------------------------------------

Mods: Making History Expansion

------------------------------------------------------------------------------

Expected behaviour: 
1. Being able to successfully connect to other servers

------------------------------------------------------------------------------

Current behaviour: 
1. Attempting to connect to any server results in a "username already taken" error on the LMP window. I had a friend set up a server to see what happens on the server side, here's what happens when I try to connect:

```
[21:45:53][Debug]: Player984 sent Connection end message, reason: Username already taken
[21:45:53][Debug]: Online Players: 0, connected: 0
[21:45:53][Warning]: Received unhandled library message Acknowledge from <MY IP>
```
To note, this particular host is running Windows with the Making History expansion.

------------------------------------------------------------------------------

Steps to reproduce: 
1. Run the KSP with LMP on Fedora 29. Try to connect to any server.

This could be unrelated or it could be helpful, but whenever I try to set up a server, the other connected player can see me in the universe but I cannot see them.

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3189092/KSP.log)

**Comment by gavazquez** [comment]
Doesn't happen on windows and I don't use linux. Might be a bad network. Check wiki as your network must be kinda slow and unreliable

**Comment by sagarreddypatil** [comment]
I am having the same issue. Doesn't exist on Windows. Seems like a Linux only problem.
