### ISSUE TITLE
extremely laggy craft

### ISSUE THREAD

**Issue by elephantae** [LunaMultiplayer/LunaMultiplayer#294]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
----------------------
[KSP.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3194443/KSP.zip)

[output_log.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3194450/output_log.zip)

--------------------------------------------------------

OS: windows 10

------------------------------------------------------------------------------

KSPVersion: 1.7

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): latest(idk number)

------------------------------------------------------------------------------

MODS (add link to download them): none except lmp

------------------------------------------------------------------------------

Expected behaviour: 30-70 part vessel causes none or minimal lag

------------------------------------------------------------------------------

Current behaviour: .2 fps, been loading for an hour with no success after attempt to switch to

------------------------------------------------------------------------------

Steps to reproduce: put small craft in duna orbit, forget about it for a day or 2, come back and try to rendezvous

**Comment by gavazquez** [comment]
Didn't manage to reproduce. Try adding universe folder next time
