### ISSUE TITLE
Flag Selection Issue

### ISSUE THREAD

**Issue by brownlm0411** [LunaMultiplayer/LunaMultiplayer#297]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS:  Windows 10 Pro Version 1803

------------------------------------------------------------------------------

KSPVersion: 1.7.1.2539

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.21.0

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: Functionality to change flag at flag pole and mission flag. Display flag selections at each and allow selection.

------------------------------------------------------------------------------

Current behaviour: When clicking on the flag pole all building icons disappear. Only way to return game to normal is to disconnect and reconnect to the server. When clicking the flag select button in VAB nothing happens

------------------------------------------------------------------------------

Steps to reproduce: Click the flag pole or the flag pole icon. Click the flag selection button in VAB.
[Config.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3277713/Config.zip)
[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3277714/Universe.zip)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3277717/output_log.txt)
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3277718/KSP.log)

**Comment by gavazquez** [comment]
You're not supposed to put flags in the folder by yourself. I'll edit the wiki
