### ISSUE TITLE
Crafts frequently get teleported out of position

### ISSUE THREAD

**Issue by syy1125** [LunaMultiplayer/LunaMultiplayer#298]
------------------------------------------------------------------------------

OS: Windows (both of us)

------------------------------------------------------------------------------

KSPVersion: 1.7.1 + Breaking Ground

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): release 0.21.0

------------------------------------------------------------------------------

MODS (add link to download them): 
[[x] Science! Continued](https://github.com/Flupster/KSP-X-Science/releases/tag/5.22) (installed through ckan)
[AstronomersVisualPack](https://github.com/themaster402/AstronomersVisualPack/releases/tag/v3.81)
[AVP 4k Textures](https://github.com/themaster402/AstronomersVisualPack/releases/tag/v1.8)
[CommunityResourcePack](https://github.com/BobPalmer/CommunityResourcePack/releases/tag/1.1.0.0)
[EnvironmentVisualEnhancements](https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases/tag/EVE-1.4.2-2) (installed through ckan)
[GroundConstruction](https://spacedock.info/mod/1123/Ground%20Construction) (v2.4.0, for some reason github doesn't have that so this is a spacedock link)
[KAS](https://github.com/ihsoft/KAS/releases/tag/1.4) (installed through ckan)
[Kerbal Engineer Redux](https://github.com/jrbudda/KerbalEngineer/releases/tag/1.1.6.0) (installed through ckan)
[KIS](https://github.com/ihsoft/KIS/releases/tag/1.22) (installed through ckan)
[Kerbal Joint Reinforcement Continued](https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued/releases/tag/v3.4.1) (installed through ckan)
[Kopernicus](https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.7.1-5)
[MechJeb2](https://www.curseforge.com/kerbal/ksp-mods/mechjeb)
[MechJebAndEngineerForAll](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3283352/MechJebAndEngineerForAll.zip)
Module Manager (I think everyone has it so I won't bother with this one)
[Restock](https://github.com/PorktoberRevolution/ReStocked/releases/tag/0.1.4) (installed through ckan)
[Restock+](https://github.com/PorktoberRevolution/ReStocked/releases/tag/0.1.4) (same site as above)
[SimpleFuelSwitch](https://spacedock.info/mod/2053/SimpleFuelSwitch) (v1.3.1, github doesn't have tags so this is a spacedock link)
[TextureReplacer](https://github.com/ducakar/TextureReplacer/releases/tag/v3.7)

------------------------------------------------------------------------------

Expected behaviour:

Vessels should stay where they are once they get into a stable orbit.

Vessel velocity should not accelerate from non-relativistic speeds to 20x the speed of light within the fraction of a second.

------------------------------------------------------------------------------

Current behaviour: 

Things keep getting teleported out of place.

There's also the time when I tried to sync up to my friend's timeline and this happened:

(Screenshots my friend uploaded)

Before
![Screenshot_73](https://user-images.githubusercontent.com/8021147/59388780-84070300-8d21-11e9-96e5-1648c95c85fc.png)

After
![Screenshot_74](https://user-images.githubusercontent.com/8021147/59388786-8bc6a780-8d21-11e9-8f41-c43997310d5e.png)

------------------------------------------------------------------------------

Steps to reproduce:

Hard to say for sure. We currently suspect either warping or reverting.

Shutting off the server and starting it pack up also sometimes seem to displace the crafts.

------------------------------------------------------------------------------

My KSP logs:
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3283386/output_log.txt)

Server logs:
[lmpserver_2019-06-12_15-56-04.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3283390/lmpserver_2019-06-12_15-56-04.log)

Additional server files, as requested:
[LMP Data.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3283392/LMP.Data.zip)

**Comment by DrewDaPilot** [comment]
Hello there! I would simply like to introduce myself as a modification developer for various different games. I have experience in networking,  unity, and bugs like this one. I will be attempting to look into this report, and will let you know on my findings at a later time.

**Comment by gavazquez** [comment]
@DrewDaPilot Feel free to have a look, if you have any question regarding the code, let me know. Also have a look at the wiki as most things are explained there

**Comment by gavazquez** [comment]
Solved with: https://github.com/LunaMultiplayer/LunaMultiplayer/commit/632449859df06d6ba581b0b5d1e1401b50e87a19
