### ISSUE TITLE
Solar panels not extending

### ISSUE THREAD

**Issue by unicornpugman** [LunaMultiplayer/LunaMultiplayer#310]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS:  Windows 10

------------------------------------------------------------------------------

KSPVersion:  1.7.3.2594

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.22.0

------------------------------------------------------------------------------

MODS (add link to download them):  Mechjeb 2 [link](https://www.curseforge.com/kerbal/ksp-mods/mechjeb)

------------------------------------------------------------------------------

Expected behaviour:  Right click on solar panels and click on "Extend
panels"
------------------------------------------------------------------------------

Current behaviour:  Right click on panel, there is no button to extend

------------------------------------------------------------------------------

Steps to reproduce: Put the button there and any other missing elements.

**Comment by gavazquez** [comment]
This is not supported if you're spectating
