### ISSUE TITLE
Server Crash - Broken State Backed Up

### ISSUE THREAD

**Issue by Alfred-PictoCube** [LunaMultiplayer/LunaMultiplayer#318]
People were reporting their vessels glitching into the ground after landing, following by rollback and explosion.
They eventually crashed the server... Actually even by restarting, it remains broken.

I kept the universe in its "broken" state so maybe you'd want to look what happened / get info regarding the errors
[BrokenState.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3827248/BrokenState.zip)

Thanks!

**Comment by gavazquez** [comment]
Affected by #290 bug and fixed
