### ISSUE TITLE
always sync kerbals

### ISSUE THREAD

**Issue by ustccgc** [LunaMultiplayer/LunaMultiplayer#326]
**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------
[Universe_issue.tar.gz](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3909652/Universe_issue.tar.gz)
[LMPModControl.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3909655/LMPModControl.zip)
[Config.tar.gz](https://github.com/LunaMultiplayer/LunaMultiplayer/files/3909664/Config.tar.gz)

OS: 
Win10
------------------------------------------------------------------------------

KSPVersion: 
1.8.1.2694
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.24.0
------------------------------------------------------------------------------

MODS (add link to download them): 
MechJeb2. Version: 2.9.0.0
QuantumStrutsContinued. Version: 1.7.5.1
------------------------------------------------------------------------------

Expected behaviour: 
Run ok
------------------------------------------------------------------------------

Current behaviour: 
Always send kerbals and vessels
------------------------------------------------------------------------------

Steps to reproduce: 
after sync the Universe and the server suddenly erupt

**Comment by gavazquez** [comment]
Not a proper bug report. Closing
