### ISSUE TITLE
Kerbals go MIA when recovering a vessel

### ISSUE THREAD

**Issue by twiclo** [LunaMultiplayer/LunaMultiplayer#328]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Fedora 30

------------------------------------------------------------------------------

KSPVersion: 1.8.1.2694 (LinuxPlayer)

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.24.0

------------------------------------------------------------------------------

MODS (add link to download them): Planetary base systems: https://www.curseforge.com/kerbal/ksp-mods/kerbal-planetary-base-systems

------------------------------------------------------------------------------

Expected behaviour: Kerbals should not be marked MIA

------------------------------------------------------------------------------

Current behaviour: Kerbals will be marked as mia when recovering a vessel. It doesn't seem to matter if it's from the launch pad or from a flight.

------------------------------------------------------------------------------

Steps to reproduce: We haven't been able to consistently reproduce this. It seems to happen about 50 percent of the time

**Comment by gavazquez** [comment]
Let me know if it still happens. I uploaded a fix
