### ISSUE TITLE
Screenshots aren't uploaded/saved on the server

### ISSUE THREAD

**Issue by daprice** [LunaMultiplayer/LunaMultiplayer#329]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/4038889/KSP.log)

(there is no "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt" on non-Windows machines, so I can't upload that)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

[LunaMultiplayer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/4038892/LunaMultiplayer.zip) (also includes server logs)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Pop_OS 19.10 and MacOS 10.15.2 clients; server running via Docker on Raspbian 10

------------------------------------------------------------------------------

KSPVersion: 1.8.1.2694

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.24.0 via Docker following [these instructions](https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server)

------------------------------------------------------------------------------

MODS (add link to download them): No server-side mods. The MacOS client has no mods other than LMP. The PopOS client (which the attached log is from) has [Chatterer](https://forum.kerbalspaceprogram.com/index.php?/topic/83290-18x-chatterer-v0998-moar-talking-23-oct-2019/), [Distant Object Enhancement Continued](https://forum.kerbalspaceprogram.com/index.php?/topic/189759-181-distant-object-enhancement-continued-v2000-12-november-2019/), [PlanetShine](https://forum.kerbalspaceprogram.com/index.php?/topic/189071-18x-planetshine-0263-nov-23-2019-ckan-support/), [Docking Port Alignment Indicator](https://forum.kerbalspaceprogram.com/index.php?/topic/40423-141-docking-port-alignment-indicator-version-681-updated-031418/). This issue occurs with both clients.

------------------------------------------------------------------------------

Expected behaviour: Screenshots get saved in the server's Universe/Screenshots directory and can be viewed using the Screenshots button in the LMP client

------------------------------------------------------------------------------

Current behaviour: "Screenshot uploaded" is displayed on screen; folders for each user are created in Universe/Screenshots on the server but they remain empty. Clicking Screenshots and then a username in the LMP client only displays a window with an hourglass but no screenshots ever appear.

------------------------------------------------------------------------------

Steps to reproduce:

1. Join the server
2. Launch a craft
3. Press F1 to take/upload a screenshot

**Comment by gavazquez** [comment]
Seems to be some connection issue as I can't reproduce locally or in other servers
