### ISSUE TITLE
Settings Not Working

### ISSUE THREAD

**Issue by Joejoemyo** [LunaMultiplayer/LunaMultiplayer#331]
OS: Windows

------------------------------------------------------------------------------

KSPVersion: 1.8.1

------------------------------------------------------------------------------

LMP version: 0.24.0

------------------------------------------------------------------------------

MODS: NONE

------------------------------------------------------------------------------

Expected behaviour: Changing settings in the server GAMEPLAY file should affect in-game interactions.
------------------------------------------------------------------------------

Current behaviour: I attempted to tweak the comm network to promote relays and infrastructure. Changing the DSN modifier, range modifier, or attempting to disable extra groundstations had no effect after a server restart.
------------------------------------------------------------------------------

Steps to reproduce: Test loss of signal distance, change DSN power by an order of magnitude, disable ground stations, restart the server, and return to find there are still extra groundstations and the same DSN range. 

note: changing CLIENTSIDE difficulty settings for DSN and groundstations had a predictable effect. If possible, add a setting to enforce server difficulty or allow client's choice?

**Comment by gavazquez** [comment]
Explained in the wiki custom settings
