### ISSUE TITLE
Log creates newline after each character

### ISSUE THREAD

**Issue by royalmustard** [LunaMultiplayer/LunaMultiplayer#335]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
Ubuntu 18.04 LTS
------------------------------------------------------------------------------

KSPVersion: 

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.25.0
------------------------------------------------------------------------------

MODS (add link to download them): 

------------------------------------------------------------------------------

Expected behaviour: 
Log prints all characters belonging to the same log statement in one line
------------------------------------------------------------------------------

Current behaviour: 
Log contains newline after each character
------------------------------------------------------------------------------

Steps to reproduce: 
download 0.25.0 nightly build
extract
run as a service with systemd
look at service logs with sudo journalctl -u lmp

**Comment by famfo** [comment]
Here are screenshots from the logs. 
![unknown](https://user-images.githubusercontent.com/44938471/74666335-96371c00-51a1-11ea-9b9c-875d654b8f32.png)
![unknown](https://user-images.githubusercontent.com/44938471/74666346-9b946680-51a1-11ea-8238-32f7a9437b4c.png)

**Comment by gavazquez** [comment]
It seems to be a problem of your .sh and not of LMP. You can see how in the first screenshot the log is fine.
I don't have Linux so better ask in the discord in case someone faced the same issue
