### ISSUE TITLE
Please allow HTTPS on the LMP-Server generated Website

### ISSUE THREAD

**Issue by xelantro** [LunaMultiplayer/LunaMultiplayer#336]
I wanted to include the LMP-Server Infos, such as current player count and so on my Website using javascript. So I went through serveral annoying steps with CORS and etc but then I got this Error: 
![grafik](https://user-images.githubusercontent.com/40129767/74861286-64ad8480-534a-11ea-801e-5bef33bfeda3.png)
So I can't pull the live-Info from the Server page bacause it doesn't support HTTPS.
I want to do it with js rather than with php because I wanted it to be more or less live and I also can't just turn off HTTPS for this page because I have a full rewrite of all requests to HTTPS on my Website.
So I ask you to please provide HTTPS support to the page :D 
(Note that I am not a main js developer so contact me if there's another option what I can do)
Thank you in advance!

**Comment by gavazquez** [comment]
I can't add support for HTTPS as I would need to buy a certificate and those cost money.

You can use this:
https://cors-anywhere.herokuapp.com/

For example: https://cors-anywhere.herokuapp.com/http://masterserver.pictocube.fr:8711/json

```
function getServers(url){	
	let request = url;	
	let xhr = new XMLHttpRequest();
	xhr.onreadystatechange = function() {
		if (this.readyState === 4 && this.status === 200) {
			$("#waitForServers").remove();
			var response = JSON.parse(this.responseText);
			$('#serverscontainer').html(parseServers(response));
			$("#serverstable").tablesorter( {sortList: [[7,1]]} ); 					
		}
	}
	xhr.open("GET", request);
	xhr.setRequestHeader("x-requested-with", 'LMP');
	xhr.setRequestHeader("Accept", 'application/json');
	xhr.send();	
}
```

e

**Comment by xelantro** [comment]
Thanks for the reply. I already use the code snippet you send after copying it from the LMP Website ;) but I thought of a solution that I could add the path to my Certificate in the Website cofig file and my LMP-Server Website would use this.
Thank you in advance!
