### ISSUE TITLE
Commnet doesnt get enabled.

### ISSUE THREAD

**Issue by WaterpigCZ** [LunaMultiplayer/LunaMultiplayer#338]
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Win 10

------------------------------------------------------------------------------

KSPVersion: 1.9.1.2788

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.25.0

------------------------------------------------------------------------------

MODS (add link to download them):  None

------------------------------------------------------------------------------

Expected behaviour: Commnet should be enabled, is enabled in config files.

------------------------------------------------------------------------------

Current behaviour: Commnet doesnt get enabled no matter the settings, the button to enable commnet is nowhere to be found.

------------------------------------------------------------------------------

Steps to reproduce: Launch the server

**Comment by gavazquez** [comment]
Not a bug. Check custom dificultiy in the wiki
