### ISSUE TITLE
PLS HELP, BDarmory does not work on LMP how can i fix this?

### ISSUE THREAD

**Issue by ojocolet** [LunaMultiplayer/LunaMultiplayer#341]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: windows 10

------------------------------------------------------------------------------

KSPVersion: 1.9.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): latest

------------------------------------------------------------------------------

MODS (add link to download them): 
BDARMORY

------------------------------------------------------------------------------

Expected behaviour: 
Destruction of other players to be seen from my end and theirs  

------------------------------------------------------------------------------

Current behaviour: 
I see them get blown up but then they respawn
------------------------------------------------------------------------------

Steps to reproduce: use gun or missile on them, they blow up for you but their is no damage

**Comment by jrodrigv** [comment]
This is not a LMP issue.  LMP doesn't provide support for mods that requires special sync events like BDArmory. 

You can install BDAMultiplayer from my GitHub but it has not been released for KSP 1.9.1 yet
