### ISSUE TITLE
No back up

### ISSUE THREAD

**Issue by Rispetto073** [LunaMultiplayer/LunaMultiplayer#342]
hello,

I've set up a KSP server but now i have the following problem..

When i start up the server it automatically start up from scratch. Even when i close the server with ctrl+c it still doenst make a back up. The only back up i could make is a sfs file on my own account.

Could some one explain to me how to make a proper back up and how i load the backup in the server?

**Comment by gavazquez** [comment]
the backup is copying the values in the ram memory into a file. your universe folder is basically a backup. Otherwise the values would live in the RAM memory and you woudn't be able to access them
