### ISSUE TITLE
Leaving Runway Safety Bubble Causes Spectating and Unplanned Craft Disassembly

### ISSUE THREAD

**Issue by Mobmaker55** [LunaMultiplayer/LunaMultiplayer#346]
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.9.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): Release 0.25.0

------------------------------------------------------------------------------

MODS (add link to download them): 
[ExtraPlanetaryLaunchpads](http://taniwha.org/~bill/ExtraplanetaryLaunchpads_v6.7.2.zip)
[BDArmory](https://github.com/PapaJoesSoup/BDArmory/releases/download/v1.3.4/BDArmory.1.3.4.0_04092020.zip)
[Kerbal Attachment System](https://www.curseforge.com/kerbal/ksp-mods/kerbal-attachment-system-kas/download/2941625)
[Kerbal Inventory System](https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2940725)
[Kerbal Planetary Base Systems](https://www.curseforge.com/kerbal/ksp-mods/kerbal-planetary-base-systems/download/2928929)
[ThrotleControlledAvionics](https://spacedock.info/mod/198/Throttle%20Controlled%20Avionics/download/3.6.2.2)
[Kerbal Alarm Clock](https://www.curseforge.com/kerbal/ksp-mods/kerbal-alarm-clock/download/2940795)
[Physics Range Extender](https://github.com/jrodrigv/PhysicsRangeExtender/releases/download/1.19.0/PhysicsRangeExtender.1.19_03282020.zip)
------------------------------------------------------------------------------

Expected behavior: Once you pilot a plane / jet / vehicle out of the KSC Runway Safety Bubble, that craft should just load in, and all other users should be unaffected.

------------------------------------------------------------------------------

Current behavior: Once a vehicle leaves the KSC Runway Safety Bubble, every player within render distance of the vehicle is instantly forced to spectate it for maybe 3 seconds, but also causes spontaneous destruction of all of the vessels within render distance. After 3 or so seconds, your view returns to your vessel, but in pieces. 

------------------------------------------------------------------------------

Steps to reproduce: 
1. Launch a vessel from the runway
2. Have someone else launch a vessel after you left the safety bubble
3. Watch the fireworks happen.
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/4612233/KSP.log)

------------------------------------------------------------------------------

A decent work-around to this issue is just going far away from the KSC, but sucks for vehicles that are slower, especially the buggies and cars I am working on.

**Comment by gavazquez** [comment]
Way too many mods that are not supported. Specially physics range extender might be causing bugs. Ask in the bdarmory channel of discord how it should be setup

**Comment by jrodrigv** [comment]
Yes, that is PRE terrain extender without any doubt
