### ISSUE TITLE
Not all dependencies listed in Wiki for building

### ISSUE THREAD

**Issue by andymule** [LunaMultiplayer/LunaMultiplayer#351]
It's my first time trying to build LMP. The wiki seems outdated with regards to dependencies. 

Referenced in project:
![image](https://user-images.githubusercontent.com/1566594/84571486-b82d5d80-ad93-11ea-94b4-547fe969d81f.png)

Instructions in Wiki:
![image](https://user-images.githubusercontent.com/1566594/84571498-cbd8c400-ad93-11ea-97dd-4909e1f94681.png)

To fix my missing references, I just copied literally everything from  from C:\Kerbal Space Program\KSP_x64_Data\Managed to External/KSPLibraries, but someone more knowledgeable should update this list. 

Thanks!

**Comment by gavazquez** [comment]
Fixed! Thanks!
