### ISSUE TITLE
No Docker file available at https://raw.githubusercontent.com/LunaMultiplayer/LunaMultiplayer/master/Dockerfile

### ISSUE THREAD

**Issue by serjevski** [LunaMultiplayer/LunaMultiplayer#352]
When i try to wget https://raw.githubusercontent.com/LunaMultiplayer/LunaMultiplayer/master/Dockerfile, I receive error 404.

**Comment by gavazquez** [comment]
The correct link is:
https://raw.githubusercontent.com/LunaMultiplayer/LunaMultiplayer/master/Dockerfile_Server
