### ISSUE TITLE
System Error upon Syncing locks on connection to servers

### ISSUE THREAD

**Issue by SSwiftGamer440** [LunaMultiplayer/LunaMultiplayer#353]
So recently ive tried to multi-install KSP by cloning the KSP folder, but after i decided that it wasnt working, i deleted the clone folder and suddenly now LMP doesnt work, logs and screenshot attached.
[Find them in this .zip file](https://drive.google.com/file/d/1yOp8JgwU1MdHltaU6z9W1LIBBsXoyUfR/view?usp=sharing)
I've tried reinstalling the mod, restarting my PC, reopening KSP
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10 Home

------------------------------------------------------------------------------

KSPVersion: 1.9.0

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.25.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: Feline Util Rovers, Kopernicus, OPM, HyperEdit, Kerbal Alarm Clock, Trajectories, Waypoint Manager, Better Time Warp, Better Burn Time

------------------------------------------------------------------------------

Expected behaviour: Connects fine and no system error is raised

------------------------------------------------------------------------------

Current behaviour: Gets to Syncing locks and gets a fatal system exception

------------------------------------------------------------------------------

Steps to reproduce: Started happening after copying the KSP folder, and issue has been ongoing ever since, unsure of actual repro steps however.

**Comment by gavazquez** [comment]
Mods are not supported. Also that savegame seems corrupt because of using mods that modify way too much the KSP behaviour

**Comment by SSwiftGamer440** [comment]
@gavazquez the thing is, even on my server which is stock, it doesn't work then either

**Comment by gavazquez** [comment]
1: Remove the Universe folder from server
2: Remove mods from KSP
3: Run LMP

Based on the log Kerbals cant be loaded because you have mods.
Also you have mods that affect the scenario modules and even planet mods.
