### ISSUE TITLE
KSP 1.10.0 - Does not load. (even after version string updated and recompiled)  Logs Attached

### ISSUE THREAD

**Issue by jmigreen** [LunaMultiplayer/LunaMultiplayer#355]
[Player.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/4859996/Player.log)

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/4859988/KSP.log)

OS: Win 10 Pro v1909 build 18363.900

------------------------------------------------------------------------------

KSPVersion: 1.10.0.2917

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.25.0 release

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: EVE, Scatterer  (Both worked before the 1.10 update, and still work now)

------------------------------------------------------------------------------

Expected behaviour: LMP loads and shows client connection menu on startup.

------------------------------------------------------------------------------

Current behaviour: LMP does not load. Log shows: 

[LOG 19:46:16.953] ADDON BINDER: Create binding redirect: LmpClient.XmlSerializers, Version=0.25.0.0, Culture=neutral, PublicKeyToken=null => System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[EXC 19:46:19.729] AmbiguousMatchException: Ambiguous match found.
	System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	Harmony.AccessTools.DeclaredMethod (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) (at <ef472ad41f4948fdb52674edfe069979>:0)
	Harmony.PatchProcessor.GetOriginalMethod () (at <ef472ad41f4948fdb52674edfe069979>:0)
	Harmony.PatchProcessor.PrepareType () (at <ef472ad41f4948fdb52674edfe069979>:0)
	Harmony.PatchProcessor..ctor (Harmony.HarmonyInstance instance, System.Type type, Harmony.HarmonyMethod attributes) (at <ef472ad41f4948fdb52674edfe069979>:0)
	Harmony.HarmonyInstance.<PatchAll>b__9_0 (System.Type type) (at <ef472ad41f4948fdb52674edfe069979>:0)
	Harmony.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <ef472ad41f4948fdb52674edfe069979>:0)
	Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) (at <ef472ad41f4948fdb52674edfe069979>:0)
	LmpClient.Base.HarmonyPatcher.Awake () (at <61a3dc721765478f9663b75f1c22e8d2>:0)
	LmpClient.MainSystem.Awake () (at <61a3dc721765478f9663b75f1c22e8d2>:0)
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	<LoadObjects>d__88:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>d__69:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>d__11:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()

------------------------------------------------------------------------------

Steps to reproduce: Initially, error was received about version compatibility.  Recompiled from source with updated version string. Error message goes away, but numerous errors in KSP log when attempting to instantiate/bind the module.

**Comment by gavazquez** [comment]
This is not a bug. The new version will be compiled when I have time

**Comment by jmigreen** [comment]
Hi Gabriel,
I did recompile it in visual studio with the new DLLs from the KSP install folder. Is there anything simple that I missed, or is it more work than that?

Un saludo...

-

**Comment by gavazquez** [comment]
To be honest I don't know as KSP wasn't working in my computer and Ihad to format it to make it work :(

I'm downloading Visual studio and all the tools but theoretically just by following the compile wiki and updating the dlls + version number it should work.

I'll try to do it today but I'm not so sure if I'll get it on time

**Comment by jmigreen** [comment]
Haha no worries if you can’t get to it instantly. I’m not demanding anything, and it’s only a game. I can only imagine how much work it took to create the mod in the first place. 

I’m only eager to get it working again because it’s excellent!

I’m an amateur iOS developer, so I’m not a visual studio expert, but I do believe I followed the instructions carefully, and the plugins folder did show updated versions of the DLLs in the gamedata folder.

 I also updated the maximum version string in the lmpglobal folder to 1.10.0. 

I included the error logs in the issue list. 
If there’s anything I can do to help, let me know. Always like to learn something new. 

Kind Regards,
Josh


-

**Comment by gavazquez** [comment]
Well, finally fixed it and it's already in the nightly builds.

They made a lot of changes to the code and the harmony patches were messed up. Also the new comets would had break it anyway.

You can get it in the nighlty discord channel or trough appveyor.

Sorry if I sound harsh... English is not my mother language ;)

**Comment by jmigreen** [comment]
Wow, that was really fast actually. Thank you so much for doing that.  No te preocupes.  Nadie se daria cuenta de que el ingles es tu segundo idioma. Saludos, -Josh From: Gabriel VázquezSent: Thursday, July 2, 2020 12:31 AMTo: LunaMultiplayer/LunaMultiplayerCc: jmigreen; AuthorSubject: Re: [LunaMultiplayer/LunaMultiplayer] KSP 1.10.0 - Does not load. (even after version string updated and recompiled) Logs Attached (#355) Well, finally fixed it and it's already in the nightly builds.They made a lot of changes to the code and the harmony patches were messed up. Also the new comets would had break it anyway.You can get it in the nighlty discord channel or trough appveyor.Sorry if I sound harsh... English is not my mother language ;)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
