### ISSUE TITLE
Rasperri auto run......

### ISSUE THREAD

**Issue by tonkepen100** [LunaMultiplayer/LunaMultiplayer#361]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Debian Buster

------------------------------------------------------------------------------

KSPVersion: 1.10

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 

------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 

------------------------------------------------------------------------------

Steps to reproduce: 

Hola Gabriel, escribo en Español, por que mi ingles es realmente malo, 

Estoy siguiendo la wiki para instalación de Master en una de mis rasperris, y tengo una pregunta y un fallo.

1.- Entiendo que hay que instalar los dos Master Servers no? osea, tanto MasterServerNightly  , como MasterServer y por lo tanto que los estén funcionando. es asi?.

2.- Bien aquí llega el problema.. puse los dos archivos de arranque en el escritorio de la raspi, tanto AutorunMS.sh, como AutorunMSNightly.sh y naturalmente les di permisos. 

Al ir a Run the command sudo nano /home/pi/.config/lxsession/LXDE-pi/autostart, parece ser que en esta version de debian autoestar no esta presente, por lo que los ejecute desde ETC/lxde, al reiniciar efectivamente salen las dos consolas de cada server, pero salen con la pantalla totalmente negra, osea que se ejecutan pero no muestran las lineas de comando de carga.

Al hacerlo y ejecutarlas manualmente si funcionan.

Como podría hacer para que se auto ejecutaran en Debian Buster?

Muchas gracias por tu atención

**Comment by gavazquez** [comment]
Hola.

Realmente necesitas ejecutar un masterserver? Ten en cuenta que ese tipo de servidores es para uso interno y si quieres postularte para tener uno ejecutandose las 24h tiene que ser por un minimo de 6 meses.

Si lo que quieres es tener un servidor "estandar" el proceso es diferente.

Lamentablemente no soy muy bueno con Linux ya que casi no lo uso asi que poco te puedo ayudar... Ya me costo horrores hacerlo funcionar en la raspberry asi que imaginate en Debian xD

Creo que lo mejro es que preguntes en stackoverflow u otra web de linux y digas que estas usando un programa que corre sobre "mono" (supongo que algo tendra que ver)

**Comment by tonkepen100** [comment]
Gracias Gabriel por tu respuesta, de veras gracias. Bien rectifique el tema y logre ya por fin poner en uno de mis servidores y activo un LMP nightlight , o como se llame, el tema es que por favor envié la solicitud de que salga como dedicado, no se si lo hice bien. Se llama Piro Servidores De nuevo te agradezco mucho tu interés.  Enviado desde Correo para Windows 10 De: Gabriel VázquezEnviado: domingo, 19 de julio de 2020 19:28Para: LunaMultiplayer/LunaMultiplayerCC: Tonique; AuthorAsunto: Re: [LunaMultiplayer/LunaMultiplayer] Rasperri auto run...... (#361) Hola.Realmente necesitas ejecutar un masterserver? Ten en cuenta que ese tipo de servidores es para uso interno y si quieres postularte para tener uno ejecutandose las 24h tiene que ser por un minimo de 6 meses.Si lo que quieres es tener un servidor "estandar" el proceso es diferente.Lamentablemente no soy muy bueno con Linux ya que casi no lo uso asi que poco te puedo ayudar... Ya me costo horrores hacerlo funcionar en la raspberry asi que imaginate en Debian xDCreo que lo mejro es que preguntes en stackoverflow u otra web de linux y digas que estas usando un programa que corre sobre "mono" (supongo que algo tendra que ver)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tonkepen100** [comment]
Gracias Gabriel por tu respuesta, de veras gracias. Bien rectifique el tema y logre ya por fin poner en uno de mis servidores y activo un LMP nightlight , o como se llame, el tema es que por favor envié la solicitud de que salga como dedicado, no se si lo hice bien. Se llama Piro Servidores De nuevo te agradezco mucho tu interés.

**Comment by gavazquez** [comment]
Para que sea dedicado, debes hacer un "push request" sobre este archivo añadiendo los datos de tu servidor: https://github.com/LunaMultiplayer/LunaMultiplayer/blob/master/MasterServersList/DedicatedServersList.txt

**Comment by tonkepen100** [comment]
Si, ya lo hice ayer, voy a hacerlo de nuevo, a ver que pasa, muchas gracias.
