### ISSUE TITLE
Starting LMP on Mono results in TypeInitializationException 

### ISSUE THREAD

**Issue by TheGoldenMinion** [LunaMultiplayer/LunaMultiplayer#364]
[lmpserver_2020-08-04_17-09-09.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5024633/lmpserver_2020-08-04_17-09-09.log)
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
Ubuntu 20.04
------------------------------------------------------------------------------

KSPVersion: 
1.10
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.26.0
------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 

------------------------------------------------------------------------------

Expected behaviour: 
It starts
------------------------------------------------------------------------------

Current behaviour: 
The updater causes a TypeInitializationException 
------------------------------------------------------------------------------

Steps to reproduce: 
Just start latest version with Mono

**Comment by gavazquez** [comment]
Probably an issue of your system. Check the wiki to see how to install LMP under linux. Also try to ask in the discord as I'm not good under linux OS's
