### ISSUE TITLE
Garbage Collection set to 0 won't disable it

### ISSUE THREAD

**Issue by gxmikvid** [LunaMultiplayer/LunaMultiplayer#366]
OS: windows 10

------------------------------------------------------------------------------

KSPVersion: 1.10 (all dlc)

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 
-KAS
-KIS
(removed these mods and nothing)

------------------------------------------------------------------------------

Expected behaviour: disable garbage collection

------------------------------------------------------------------------------

Current behaviour: spamming garbage collection

------------------------------------------------------------------------------

Steps to reproduce: IntervalSettings "GcMinutesInterval" set to 0

[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5048618/LMPServer.zip)
[lmpserver_2020-08-10_01-39-14.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5048619/lmpserver_2020-08-10_01-39-14.log)

**Comment by gavazquez** [comment]
You shouldn't disable GC. If you don't want to see the messages, reduce the log level

**Comment by dabluecaboose** [comment]
Just like to weigh in and say you should probably change the config comments if "You shouldn't disable GC".  It clearly says "0=Deactivated"

We've been running into issues with GC killing debris instantly which is why we've been trying to disable it.  Guess we'll set it to 1 day or something then

**Comment by dabluecaboose** [comment]
Just want to drop in and say we just figured out "Dekessler" is the one that removes debris, not garbage collection.  My bad!
