### ISSUE TITLE
Show “ [Warning]: Malformed packet; stated payload length 1760, remaining bytes 1495”

### ISSUE THREAD

**Issue by Peter-JY** [LunaMultiplayer/LunaMultiplayer#367]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.10.1/1.10.0

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.26.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 
Must:BDA Multiplayer,PRE,ModuleManager
suggestion:Mj

------------------------------------------------------------------------------

Expected behaviour: No any Warning

------------------------------------------------------------------------------

Current behaviour: show” [Warning]: Malformed packet; stated payload length 1760, remaining bytes 1495”when someone joined the server

------------------------------------------------------------------------------

Steps to reproduce: First, I opened the server, then I let my computer joined the server.When I push the Connect button, the server showed these things 4-5 per second. I can give you the .log of LMPServer, my ksp.log and output_log.log, and all the documents in LMPServer(Included all the documents (such as Universe folder)and the LMPModControl.xml and so on). 
This is the html:[Google Drive Link: https://drive.google.com/drive/folders/10Fm_5N8TCRQ0-Rxm7hnFc8J-17sAeE0W?usp=sharing](https://drive.google.com/drive/folders/10Fm_5N8TCRQ0-Rxm7hnFc8J-17sAeE0W?usp=sharing) 
By the way, there isn’t only me in the server, and when someone joined, it will show the same word.

**Comment by gavazquez** [comment]
probably BDA issue
