### ISSUE TITLE
Number format in Subspace.txt is locale dependend

### ISSUE THREAD

**Issue by fredlllll** [LunaMultiplayer/LunaMultiplayer#372]
i moved my universe from my german windows computer to my english linux box. the english linux box then ignored the comma in the number and suddenly i was 6 million years in the future. to prevent this use the invariant cultureinfo when parsing float numbers

`double.Parse(str,System.Globalization.CultureInfo.InvariantCulture);`

and when outputting floats:

`d.ToString(System.Globalization.CultureInfo.InvariantCulture);`

maybe also check other parts of the codebase if they are locale based?

**Comment by gavazquez** [comment]
I use datetime parse exact to store the time in the StartTime.txt file so no idea about why it happened

https://github.com/LunaMultiplayer/LunaMultiplayer/blob/7ac0be1427993f2a20cbee628b27b22cbefa5486/Server/System/TimeSystem.cs#L51

**Comment by fredlllll** [comment]
but you dont format it with a culture when saving it
https://github.com/LunaMultiplayer/LunaMultiplayer/blob/7ac0be1427993f2a20cbee628b27b22cbefa5486/Server/System/TimeSystem.cs#L26 which leads it to save it using the current locale. (i mightve only started the kerbal server once on my german windows system and then transfered it to english linux, so this wouldve happened on windows too)

**Comment by gavazquez** [comment]
the ":s" in $"{TimeContext.StartTime:s}" is the format of the datetime

![image](https://user-images.githubusercontent.com/12727761/101372300-08512c80-38ac-11eb-9c49-82861e12dc19.png)

**Comment by fredlllll** [comment]
oh you got me all confused, sorry. you are talking about StartTime.txt but im talking about subspace.txt. and that content is printed here https://github.com/LunaMultiplayer/LunaMultiplayer/blob/ec2d15779ca2bdaa80f23e58b8910ed7e06b15fb/Server/Context/WarpContext.cs#L14 so no culture independence here, and its used here https://github.com/LunaMultiplayer/LunaMultiplayer/blob/85b30fab46ebf070c1d07e47c8d0a8238a14e03c/Server/System/WarpSystem.cs#L28 and then the double is parsed again here https://github.com/LunaMultiplayer/LunaMultiplayer/blob/85b30fab46ebf070c1d07e47c8d0a8238a14e03c/Server/System/WarpSystem.cs#L74 also without culture info

**Comment by gavazquez** [comment]
You're definatelly right. Good job spotting that  bug :)
I'll do a PR to this

**Comment by fredlllll** [comment]
a little mistake is in your fix

https://github.com/LunaMultiplayer/LunaMultiplayer/blob/master/Server/System/WarpSystem.cs#L84

this should be subspaceLines.Length not SubspaceFile.Length . the file will almost always be longer than 1 byte
