### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by wirke** [LunaMultiplayer/LunaMultiplayer#373]
![изображение](https://user-images.githubusercontent.com/46074473/94341779-ea965a00-0014-11eb-8744-bc7a8a6ce3b5.png)
Every day, when I log into the server, I see this. Due to this bug, the server is very slow. To fix it, you have to delete a large number of crafts through the server console, it is impossible to understand what exactly is causing the bug. Hosting a server with this bug is unbearable, players are trying to fix it themselves and delete all the crafts in the universe and this is very annoying.

**Comment by gavazquez** [comment]
Probably using mods. Also check the KSP log file for that errors

**Comment by wirke** [comment]
First: all mods were banned on my server, only pure ksp
Second: on each server, with the admin of which I communicate, this bug also periodically appears

**Comment by wirke** [comment]
The problem is most likely due to the fact that crafts fall into the ground, because the error is fixed each time by deleting all landed crafts
