### ISSUE TITLE
Hosted server not appearing in master server list

### ISSUE THREAD

**Issue by ahensley** [LunaMultiplayer/LunaMultiplayer#378]
I have set up an LMP server on an Azure host and am having trouble getting the server to appear on the master server list. It plays fine and players can connect directly, but it would be nice not to have to share the IP address, or worry too much if it changes.

I have tried running a server locally on my PC using the same config XMLs as are in use on the server and this does register with the master server OK. Does the master server try to connect in any unusual way to verify the server before adding it? Port 8800 and 8900 are wide open and both the game server and JSON stats server are available worldwide, so I'm a bit at a loss. Thanks!

[ServerData.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5557867/ServerData.zip)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
Ubuntu Server 20.10
------------------------------------------------------------------------------

KSPVersion: 
1.10.1.2939
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.26.0 (Release)
------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 
none
------------------------------------------------------------------------------

Expected behaviour: 
The server should appear on the master server list within a few minutes of starting. 
------------------------------------------------------------------------------

Current behaviour: 
It does not appear. 
------------------------------------------------------------------------------

Steps to reproduce: 
I am running the server using Docker, using [a slightly modified Dockerfile](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5557880/Dockerfile.txt) from the example on the wiki [here](https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server#docker). I noticed that the server JSON stats webserver did not work with the UDP only port mapping. Thinking this could be preventing the master server from requesting the server settings, I removed the UDP restriction. This did not seem to help.

I have also noticed high CPU usage by the container even when the server is idle with no players connected. It plays fine when you do connect, but perhaps that is an indicator that something related to this issue is unhappy.

**Comment by gavazquez** [comment]
Check that the container has access to the outside. Basically servers announce themselves against the master servers that are described in the muster server list so your server must be capable of accessing the master server list file and also the master servers described there
