### ISSUE TITLE
Garbled characters when run on Linux

### ISSUE THREAD

**Issue by yuki77** [LunaMultiplayer/LunaMultiplayer#379]
When running on Linux, the characters are garbled.
What is the reason for specifying "Console.OutputEncoding = Encoding.Unicode"?

------------------------------------------------------------------------------

OS: Linux

------------------------------------------------------------------------------

KSPVersion: 1.10

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.26.0 (Release)

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: none

------------------------------------------------------------------------------

Expected behaviour: Output to console in UTF8

------------------------------------------------------------------------------

Current behaviour: The log output to the console is UTF-16 encoded, which causes garbled characters.
For the same reason, Systemd recognizes that the output contains a null character ("\0"), so the logs are separated by a single character.

------------------------------------------------------------------------------

Steps to reproduce: Run on Linux

**Comment by fredlllll** [comment]
ah that explains why logs are all fucked up. yeah that should be set to utf8. and if it needs to be unicode on windows then one could just detect the platform and set it accordingly to that

**Comment by gavazquez** [comment]
Changed it to utf8
