### ISSUE TITLE
Can't get new missions at private server.

### ISSUE THREAD

**Issue by jeq1** [LunaMultiplayer/LunaMultiplayer#381]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 

------------------------------------------------------------------------------

KSPVersion: 
1.10.1
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.26.0
------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 

------------------------------------------------------------------------------

Expected behaviour: 
We get missions.
------------------------------------------------------------------------------

Current behaviour: 
I make server from blank, and we don't get new missions, only World Milestone missions are shown.
I can fix this only if i join open public server, and copy their settings to my own host folder. 
------------------------------------------------------------------------------

Steps to reproduce:

**Comment by gavazquez** [comment]
That's because you must first get those missions done to get more missions. Happens the same in single player
