### ISSUE TITLE
What's the full list of banned parts?

### ISSUE THREAD

**Issue by webguy24** [LunaMultiplayer/LunaMultiplayer#382]
Some parts say "this part is banned". What's the full list of the banned parts?

**Comment by gavazquez** [comment]
That's configured by the server in the modcontrol file. You can't see it as a client

The default list is:
https://github.com/LunaMultiplayer/LunaMultiplayer/blob/b254baf83845dcf2f3467b6f2400321945d84c5a/LmpCommon/ModFile/Structure/ModControlStructure.cs#L38
