### ISSUE TITLE
Just a bug in our server with a select few.

### ISSUE THREAD

**Issue by thatepicguy3967** [LunaMultiplayer/LunaMultiplayer#383]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"** I do not sadly

------------------------------------------------------------------------------
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5722188/KSP.log)

Because the stuff happening is hard to explain I do have a video to show whats happening. (Also mb with the compression, Github is garb when it comes to it)

https://user-images.githubusercontent.com/76415503/102737001-e88a2180-430b-11eb-8662-354306f4db23.mp4

My apologies for not getting his Output_log.txt, because I think that comes from crashes? But he wasn't able to find it.
------------------------------------------------------------------------------

OS: 
Windows 10

KSPVersion: 

1.10.1.2939

LMP version (include the build number if you are using a nighly build): 

0.26.0 (The one on CKAN)

MODS. Remember that **mods are not supported**: 

**(Although we went threw there and didn't seem to find the problem if it is mods, as it wasn't happeniing to other people, and all game files where verified...)**

[LMPModControl.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5722215/LMPModControl.txt)

Expected behaviour: 
Throttle control: What pretty much normally happens, all the controls function normally.
Time warping/going to nodes or SOI transitions: Time warping to locations is normal, SOI transitions are fine, orbits work as intended

Current behaviour: 
Throttle control: Cuts every 5-10 seconds at random intervals
Time warping to nodes: Nodes totally change, mainly with SOI transitions

Steps to reproduce: 
Just normal launching with the throttle being cut, and normal SOI transitions and time warping (If I had to guess it would be something dealing with time warping, but I don't know.)

**Comment by gavazquez** [comment]
I think that this happens because you're getting lagged behind the server time. As you can see your clock is in yellow, this means that you're not running at stable FPS so KSP makes your phisics clock go slower. Kinda like "slowing the time"

Since you must be in sync with the server time, LMP puts your vessel on rails and warps the time forward so you're back in sync with the server.

Unfortunately this doesn't have any solution since the physics don't run at the server so your only option is to upgrade your computer and very important, don't use huge monster ships that clog the CPU
