### ISSUE TITLE
[XBOX] Deployable science disappear from containers

### ISSUE THREAD

**Issue by ConArt70** [LunaMultiplayer/LunaMultiplayer#384]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: xbox one

------------------------------------------------------------------------------

KSPVersion: 1.13

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 

------------------------------------------------------------------------------

Expected behaviour: attached deployable science containers to a vehicle. Place science experiments inside. Exit VAB and still have science experiments in containers

------------------------------------------------------------------------------

Current behaviour: when exiting the VAB, the science containers are empty

------------------------------------------------------------------------------

Steps to reproduce: place deployable surface experiments into containers attached to vehicle. Launch vehicle and check containers.

**Comment by gavazquez** [comment]
Just made a small test and I see them. Please do a vidoe or explain it better

![image](https://user-images.githubusercontent.com/12727761/103028538-3f843680-4558-11eb-9b95-71f9f0267a9f.png)

**Comment by ConArt70** [comment]
That doesn't look like xbox version?

Anyway, everytime I use a container on a vehicle, I fill it with deployable science units. Then, when it leaves the VAB each container has two empty slots and one control unit.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ConArt70** [comment]
So is this issue not going to get looked at?

**Comment by gavazquez** [comment]
I don't have an xbox so I can't fix it

**Comment by ConArt70** [comment]
So what's the point of this bug tracker then? How can you close it just because you don't have an xbox?

**Comment by gavazquez** [comment]
I reopened the issu but I'm the only developer now. It might take a long time until somebody wants to have a look and can help you with this

**Comment by ConArt70** [comment]
My sincere apologies. I thought this was the official ksp bug tracker and hadn't realised it was for mods. I am officially an idiot.

**Comment by lfuelling** [comment]
Just in case you are still looking for a way to get support for KSP itself, you will probably get help in [the official KSP forum](https://forum.kerbalspaceprogram.com/)
