### ISSUE TITLE
Kerbals exiting vehicles are not synced / Spectator mode bugged

### ISSUE THREAD

**Issue by lfuelling** [LunaMultiplayer/LunaMultiplayer#386]
When a Kerbal exits a vessel while another player is in spectator mode on the same vessel, the Kerbal is still inside the vessel for the spectating player and the spectating player gains control of the vessel.

------------------------------------------------------------------------------

[KSP.log of Client1](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5740767/KSP.log)
[KSP.log of Client2](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5740764/KSP.log)
[ConfigAndUniverse.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5740741/ConfigAndUniverse.zip)

**OS**: Linux (Server) / macOS (Clients)
**KSP version**: 1.11.0.3045
**LMP version**: 0.27.0 
**Mods**: None

------------------------------------------------------------------------------

**Expected behaviour**: When a Kerbal exists the vehicle, it should exit on all other clients as well.

------------------------------------------------------------------------------

**Current behaviour**: The Kerbal stays inside the vessel (for the spectator) and the spectator gets control of the vehicle (with the Kerbal inside) while the originally controlling player is controling the parachute descent of the Kerbal.

------------------------------------------------------------------------------

**Steps to reproduce**: 
1. Open a server and join with two clients
2. **Client1**: Build a plane and start to fly
3. **Client2**: Build a plane and start to fly alongside Client1
4. **Client2**: Exit the plane ~~at `v>400m/s` (so the Kerbal dies)~~ even works at lower speeds
5. *At this point, Client2 should be "teleported" to spectator mode on the vessel of Client1*
6. **Client1**: Exit the plane (at a velocity the Kerbal won't die)
7. *At this point, Client1 controls the Kerbal and Client2 "gains" control of the plane, the Kerbal is still shown as in the vessel for Client2*

**Comment by gavazquez** [comment]
Same as #368 
Not easy to fix :(
