### ISSUE TITLE
No Servers in the Serverlist

### ISSUE THREAD

**Issue by Shnob** [LunaMultiplayer/LunaMultiplayer#390]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.11

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.27.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: none (tested with a fresh install of ksp 1.11)

------------------------------------------------------------------------------

Expected behaviour: Servers in the server list

------------------------------------------------------------------------------

Current behaviour: Text "No servers!" in the server list (with no servers appearing even after a refresh)

------------------------------------------------------------------------------

Steps to reproduce: Start KSP, click on Server list in LMP GUI

Sorry there isn't really much to go on here, I just don't know what to do at this point.

**Comment by gavazquez** [comment]
Just push refresh, it's working
