### ISSUE TITLE
linux support for Server ?

### ISSUE THREAD

**Issue by dazoe** [LunaMultiplayer/LunaMultiplayer#391]
What was the reason for moving to net 5? I just started running a server using a docker container. The container doesn't work with latest nightly.

**Comment by lfuelling** [comment]
I run a server on Linux successfully (using mono). What exactly are your problems?

**Comment by gavazquez** [comment]
Net 5 of nightly should even work better under linux as you don't need mono.

I switched to net5 as the performance is better

**Comment by dazoe** [comment]
You don't need mono but don't you then need the dotnet 5 runtime time? I haven't done much with dotnet core/5 and am trying to figure out how you are meant to run Server.exe on linux. I tried running a docker from alpine:edge and used microsoft's dotnet install script.
```
bash-5.0# dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.10 [/root/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.1 [/root/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.10 [/root/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.1 [/root/.dotnet/shared/Microsoft.NETCore.App]
bash-5.0# dotnet Server.exe
Error:
  An assembly specified in the application dependencies manifest (Server.deps.json) has already been found but with a different file extension:
    package: 'Server', version: '1.0.0'
    path: 'Server.dll'
    previously found assembly: '/LMPServer/Server.exe'
bash-5.0# dotnet Server.dll
Error:
  An assembly specified in the application dependencies manifest (Server.deps.json) was not found:
    package: 'System.Drawing.Common', version: '5.0.0'
    path: 'runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll'
```

**Comment by dazoe** [comment]
I think i have it figured out. The nightly builds don't include a Linux build? I rewrote my Dockerfile to build the server instead of using the nightly from the build server.

**Comment by gavazquez** [comment]
I'm not so much into docker but feel free to do a push request if yours fixes it
