### ISSUE TITLE
scenario loading order random?

### ISSUE THREAD

**Issue by El13B** [LunaMultiplayer/LunaMultiplayer#398]
ok so I'm poking around stuff and I noticed that the save file the mod creates kind of mixes all scenario sections around. multithread issue or I'm just missing something here?

**Comment by gavazquez** [comment]
You need to proof that statement with examples, a csharp test or some reproduction steps. 

Also, files are properly locked against race conditions:
https://github.com/LunaMultiplayer/LunaMultiplayer/blob/master/Server/System/FileHandler.cs

**Comment by El13B** [comment]
Alrighty here ya go you wanted an exemple? Here's a Save I converted to a Universe folder and when I load get it back from the server it scrambles it.
you can see for example reputation, KerbalInventoryScenario,CommNetScenario and SentinelScenario get loaded before ROCScenario which shouldn't be the case.
[saves.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5766164/saves.zip)
