### ISSUE TITLE
Luna having a seizure when sending scenarios to player??? (GONE WRONG) (GONE SEXUAL) 🤫

### ISSUE THREAD

**Issue by El13B** [LunaMultiplayer/LunaMultiplayer#399]
Alrighty here ya go you wanted an exemple? Here's a Save I converted to a Universe folder and when I load it back from the server it scrambles it.
you can see for example reputation, KerbalInventoryScenario,CommNetScenario and SentinelScenario get loaded before ROCScenario which shouldn't be the case.
[saves.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/5766195/saves.zip)
Couldn't reopen #398 
so I made this one instead

**Comment by El13B** [comment]
Reproduction steps: 
- Make a world as a baseline for what a save should look like. 
- Join any Luna server
- Compare both lunamultiplayer save and the original world save
- Notice how the Scenario section is not ordered properly

**Comment by gavazquez** [comment]
The scenarios are loaded in the order they are received from the server

```
public void LoadScenarioDataIntoGame()
{
	while (ScenarioQueue.TryDequeue(out var scenarioEntry))
	{
		var psm = new ProtoScenarioModule(scenarioEntry.ScenarioNode);
		if (IsScenarioModuleAllowed(psm.moduleName) && !IgnoredScenarios.IgnoreReceive.Contains(psm.moduleName))
		{
			LunaLog.Log($"[LMP]: Loading {psm.moduleName} scenario data");
			HighLogic.CurrentGame.scenarios.Add(psm);
		}
		else
		{
			LunaLog.Log($"[LMP]: Skipping {psm.moduleName} scenario data in {SettingsSystem.ServerSettings.GameMode} mode");
		}
	}
}

```

The order they are written in the file doesn't matter since the ConfigNode file is a key-value format. If there's an error and you suspect is related to the order the nodes are added into the configNode then I'll have a look.

**Comment by El13B** [comment]
Generally the order of the scenario nodes indeed seem not to matter. But some mods (Kerbalism for example) seem to misbehave when their scenario node is received before other scenarios nodes. Dunno if they're would be a way of making the server send certain scenarios in a specific order.

**Comment by gavazquez** [comment]
Well, I don't support mods for this reason. You might want to try to modify the code on the server side but I can't help on that

**Comment by El13B** [comment]
will try to do that, thanks anyways
