### ISSUE TITLE
Use community-distributed Harmony to avoid inter-mod conflicts

### ISSUE THREAD

**Issue by gotmachine** [LunaMultiplayer/LunaMultiplayer#415]
I have released the community distributed Harmony v2 lib available here : https://github.com/KSPModdingLibs/HarmonyKSP

I've also pushed a [Kerbalism release](https://github.com/Kerbalism/Kerbalism/releases/tag/3.13) using it. Sorry for not waiting for everyone to be ready, but I won't be around much in the next months to take care of the situation. 

Note that the CKAN people have done a great job at sorting the compatibility issues by updating the metadata for CKAN indexed mods, but of course that won't help for manual installs.

In the current state of things, mods that bundle Harmony 1 will break when HarmonyKSP is installed, as the KSP assembly loader will always load it first : from my tests, due to the HarmonyKSP folder being named `000_Harmony`, any subsequent load of another version will redirect to that first loaded version.

The HarmonyKSP distribution include a basic install checker that will notify end-users during loading when other Harmony versions are installed : 
![image](https://user-images.githubusercontent.com/24925209/111550361-3b923a00-877e-11eb-84e1-8eb521d6ce46.png)

As far as I know, outside of Kerbalism, the following mods are currently bundling Harmony :
- [Tilt'em](https://github.com/LunaMultiplayer/TiltEm) : bundling Harmony 1, not updated since ~1 year
- [AirlockPlus](https://github.com/cake-pie/AirlockPlus/) : bundling Harmony 1, seems abandoned (last version is for KSP 1.7)
- [ConformalDecals](https://github.com/drewcassidy/KSP-Conformal-Decals) : bundling Harmony 1 through the [Shabby](https://github.com/taniwha/Shabby) library
- [LMP](https://github.com/LunaMultiplayer/LunaMultiplayer) : latest release is bundling Harmony 1, but master seems to have been updated to use Harmony 2
- [KSPW00tNow](https://github.com/Kristallranke/KSPW00tNow) : bundling Harmony 2
- 
I'm copy-pasting this issue in all those repositories for awareness. For details about the how and why, please refer to the initial discussion on the CKAN repository here : https://github.com/KSP-CKAN/NetKAN/pull/8288#issuecomment-801435999

**Comment by DasSkelett** [comment]
A new stable release bundling **Harmony2** is out now.
I'm considering changing the metadata to filter out the bundled Harmony2 DLL, and add a dependency on CKAN's indexed Harmony2 module.
However this would mean that the installations would differ, most noticeable with the community Harmony2 coming with an install checker. In theory ignoring bundled dependencies and replacing them with upstream ones happens all the time, but Harmony is a bit special, as we all now.
