### ISSUE TITLE
Server get stuck in command window when not hitting "Enter"

### ISSUE THREAD

**Issue by FlightMS** [LunaMultiplayer/LunaMultiplayer#418]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.11.2

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.27.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: NONE

------------------------------------------------------------------------------

Expected behaviour: Server runs smoothly in the background without interaction.

------------------------------------------------------------------------------

Current behaviour: Sometimes it's needed to hit a few "Enter" in the console to keep server running. For example sending vessels, aquiring and releasing locks on vessel parts, sync orbits, remove debris and so on.

------------------------------------------------------------------------------

Steps to reproduce: Run server and put cmd window in the background and wait

**Comment by gavazquez** [comment]
Windows config issue:

https://superuser.com/questions/419717/windows-command-prompt-freezing-randomly
