### ISSUE TITLE
Server fails first time startup

### ISSUE THREAD

**Issue by 4oclockfox** [LunaMultiplayer/LunaMultiplayer#438]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nightly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.12

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.28.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: None

------------------------------------------------------------------------------

Expected behaviour: First time launch, config file generates, etc.

------------------------------------------------------------------------------

Current behaviour: server.exe launches and immediately crashes (?). Window pops up for a second, then closes.

------------------------------------------------------------------------------

Steps to reproduce: Downloaded server, unzipped to folder on desktop, ran server.exe

Here's the full server, zipped and ready to go. I tried the updater to get a nightly build instead, but I got an error saying the site was unreachable. I have .net 5 installed, and I had a friend try creating a server completely separately with the same issue.
[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/6743928/LMPServer.zip)

**Comment by gavazquez** [comment]
Read the wiki about prerequisites
