### ISSUE TITLE
server.exe closes instantly after opening, help would be nice.

### ISSUE THREAD

**Issue by jetblade** [LunaMultiplayer/LunaMultiplayer#439]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.12.1.3142

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: no mods

------------------------------------------------------------------------------

Expected behaviour: runs

------------------------------------------------------------------------------

Current behaviour: shits bricks

------------------------------------------------------------------------------

Steps to reproduce: opening server.exe

So the problem I'm having im trying to start a server but when i start the server.exe is instantly closes that's it.

**Comment by gavazquez** [comment]
Check wiki

**Comment by jetblade** [comment]
> 
> 
> Check wiki

i checked the wiki and there is nothing that helps with my problem

**Comment by gavazquez** [comment]
Create a server. Dotnet 5
