### ISSUE TITLE
"Username already taken"???

### ISSUE THREAD

**Issue by RianaStarspaw** [LunaMultiplayer/LunaMultiplayer#443]
Ive tried to make a server but when my friend trying to join she getting this message, vica versa is the same, also turned out we both cannot connect to any server because even if we type random garbage as our user name is somehow magically taken already?

What is this?

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.12

------------------------------------------------------------------------------

LMP version:  0.28.0.460

------------------------------------------------------------------------------

Expected behaviour: Able to connect to any server.

------------------------------------------------------------------------------

Current behaviour: Unable to connect to any server because being dropped with an "Username already taken" error message.

**Comment by Fierce-Cat** [comment]
You can try to delete the Universe folder, and restart the LMP server.

**Comment by RianaStarspaw** [comment]
> 
> 
> You can try to delete the Universe folder, and restart the LMP server.

We did try that, still does not work, same error message. although myself i found couple joinable server but with very high ping. Rest of them just still refuse to work and gives me the same Username already taken error message.

**Comment by RianaStarspaw** [comment]
We did an another attempt yesterday just to be able to grab a clean log files here. Its when i try connecting to my friend's server.
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/6783024/KSP.log)
[Player.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/6783027/Player.log)

**Comment by gavazquez** [comment]
Really don't know whats going on in your network.

My log:

```
[LOG 13:03:18.898] [LMP]: Sending NAT introduction to server. Token: 71760d7717c3a3175064e6e8aba7085a5f2cf7aa
[LOG 13:03:18.982] [LMP]: [Lidgren DEBUG] NAT introduction received; we are designated client
[LOG 13:03:18.982] [LMP]: [Lidgren DEBUG] NAT punch sent to 192.168.0.20:8888
[LOG 13:03:18.982] [LMP]: [Lidgren DEBUG] NAT punch sent to 178.69.104.61:8888
[LOG 13:03:18.983] [LMP]: [Lidgren DEBUG] NAT introduction received; we are designated client
[LOG 13:03:18.983] [LMP]: [Lidgren DEBUG] NAT punch sent to 192.168.0.20:8888
[LOG 13:03:18.983] [LMP]: [Lidgren DEBUG] NAT punch sent to 178.69.104.61:8888
[LOG 13:03:19.013] [LMP]: [Lidgren DEBUG] NAT introduction received; we are designated client
[LOG 13:03:19.013] [LMP]: [Lidgren DEBUG] NAT punch sent to 192.168.0.20:8888
[LOG 13:03:19.013] [LMP]: [Lidgren DEBUG] NAT punch sent to 178.69.104.61:8888
[LOG 13:03:19.013] [LMP]: [Lidgren DEBUG] NAT introduction received; we are designated client
[LOG 13:03:19.013] [LMP]: [Lidgren DEBUG] NAT punch sent to 192.168.0.20:8888
[LOG 13:03:19.013] [LMP]: [Lidgren DEBUG] NAT punch sent to 178.69.104.61:8888
[LOG 13:03:19.057] [LMP]: [Lidgren DEBUG] NAT punch received from 178.69.104.61:8888 we're client, so we send a NatIntroductionConfirmRequest - token is 71760d7717c3a3175064e6e8aba7085a5f2cf7aa
[LOG 13:03:19.057] [LMP]: [Lidgren DEBUG] NAT punch received from 178.69.104.61:8888 we're client, so we send a NatIntroductionConfirmRequest - token is 71760d7717c3a3175064e6e8aba7085a5f2cf7aa
[LOG 13:03:19.107] [LMP]: [Lidgren DEBUG] NAT punch confirmation received from 178.69.104.61:8888 we're client so we go ahead and succeed the introduction
[LOG 13:03:19.107] [LMP]: Nat introduction success against 178.69.104.61:8888. Token: 71760d7717c3a3175064e6e8aba7085a5f2cf7aa
[LOG 13:03:19.107] [LMP]: Connecting to 178.69.104.61 port 8888
[LOG 13:03:19.145] [LMP]: [Lidgren DEBUG] Unhandled type during handshake: NatIntroductionConfirmed length: 42
[LOG 13:03:19.145] [LMP]: [Lidgren DEBUG] Unhandled type during handshake: NatIntroductionConfirmed length: 42
[LOG 13:03:19.145] [LMP]: [Lidgren DEBUG] Unhandled type during handshake: NatIntroductionConfirmed length: 42
[LOG 13:03:19.183] [LMP]: [Lidgren DEBUG] Unhandled type during handshake: NatIntroductionConfirmed length: 42
[LOG 13:03:19.183] [LMP]: [Lidgren DEBUG] Unhandled type during handshake: NatIntroductionConfirmed length: 42
[LOG 13:03:19.386] [LMP]: [Lidgren DEBUG] Initiated average roundtrip time to 130.08 ms Remote time is: 468542.69003875
[LOG 13:03:22.119] [LMP]: Connected to 178.69.104.61:8888
```

It seems that your connection is getting stuck somehow

**Comment by gavazquez** [comment]
I've increased the handshake response time. You might try to download the nightly version and see if it's fixed

**Comment by RianaStarspaw** [comment]
Just an update here, turned out at the end i could not connect to my friend's server also neither i was able to connect to their server due she had her internet settings use IPv6 instead of IPv4. Today soon as she changed their internet settings use IPv4 everything worked just fine.

The nightly build version we used during this time is: 0.28.0.500

Also have to add my issue from before seems irrevelant, Just some moment ago ive tried the release version of the mod and its working just fine, my issue probably been caused by a temporary connection issue.
