### ISSUE TITLE
Problem with the tab opening

### ISSUE THREAD

**Issue by dsagfa** [LunaMultiplayer/LunaMultiplayer#449]
When I launch kerbal space program no luna multiplayer thing opens, not even the little square on the side when in flight.

How did i get here?

**Comment by DasSkelett** [comment]
Sounds like LMP isn't installed correctly. Make sure you installed it completely, including the `000_Harmony` folder. And if you jsut upgraded LMP, make sure you removed the existing installation before extracting the new one, to remove the old `0Harmony.dll` which was in a different place.

If it's neitehr of the above, upload the `KSP.log` file here.

**Comment by dsagfa** [comment]
I do think i have installed it, but i don't remember having to get 000_Harmony.. Also which file should i uninstall? 000_Harmony is a empty file so i think i should install 000_harmony.
