### ISSUE TITLE
Server not working with 0.28.0

### ISSUE THREAD

**Issue by FlightMS** [LunaMultiplayer/LunaMultiplayer#459]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.12.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.28.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: NONE

------------------------------------------------------------------------------

Expected behaviour: Server starting normally

------------------------------------------------------------------------------

Current behaviour: Server trying to start but runs in error

> [22:34:28][Error]: Could not resolve assembly System.Net.Requests.resources, Version=5.0.0.0, Culture=de-DE, PublicKeyToken=b03f5f7f11d50a3a referenced by System.Net.Requests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[22:34:28][Error]: Could not resolve assembly System.Net.Requests.resources, Version=5.0.0.0, Culture=de, PublicKeyToken=b03f5f7f11d50a3a referenced by System.Net.Requests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a <

It stucks then at

> [22:34:29][LMP]: Registering with master servers... <

.NET Core version 5.0.8 was used. The error occurs even with migrated Universe from 0.27.0 and also with blank Universe.

------------------------------------------------------------------------------

Steps to reproduce: Start server with .NET 5.0.8

**Comment by gavazquez** [comment]
Use 64bits net core.
Registering with master servers doesn't mean it's stuck

**Comment by FlightMS** [comment]
Hi!

64bit version was used, but still the same error. It's just the core version and not desktop experience right?

![NET Version](https://user-images.githubusercontent.com/82420268/127405620-bea1a5e8-f8fd-440b-9932-15044357e124.PNG)

**Comment by gavazquez** [comment]
I'm on phone but in the create a server wiki page there's a picture. If you are running on a x86 machine then get the 32bits but usually is the x64

**Comment by DasSkelett** [comment]
> ```
> 22:34:28][Error]: Could not resolve assembly System.Net.Requests.resources, Version=5.0.0.0, Culture=de-DE, PublicKeyToken=b03f5f7f11d50a3a referenced by System.Net.Requests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
``` 

This error message is "expected", as in everyone with a non-English locale gets it and it does not mean the server does not work.
If you can connect to the server and/or it shows up in the server list, everything's good.
