### ISSUE TITLE
move LMPModControl.xml

### ISSUE THREAD

**Issue by zivoy** [LunaMultiplayer/LunaMultiplayer#463]
Have the `LMPModControl.xml` file be in the Configs folder rather than in the root dir of the server

**Comment by Binary-2** [comment]
Please! Docker containers can't access LMPModControl.xml as is.

**Comment by zivoy** [comment]
@Binary-2, the test failed because it's missing the password, which is in a secret. It works fine though. 

also, in the meantime, you can add `"/LMPServer/LMPModControl.xml"` to the 
```dockerfile
VOLUME "/LMPServer/Config" "/LMPServer/Plugins" "/LMPServer/Universe" "/LMPServer/logs"
```
line in the docker file I put in the wiki. Then when creating the container, add `-v /opt/LunaMultiplayer/LMPModControl.xml:/LMPServer/LMPModControl.xml` to the create command.
Though make sure the mod file is present in the dir. Otherwise, it will make a directory in the container with the name `LMPModControl.xml`.

**Comment by Binary-2** [comment]
Doesn't seem to work still sadly, it still bans the modded parts I want to use even though I'm generating an XML with them
