### ISSUE TITLE
Stock Game Parts are Banned by Default

### ISSUE THREAD

**Issue by Musket519** [LunaMultiplayer/LunaMultiplayer#466]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.12.2.3167

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.28.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**:  N/A

------------------------------------------------------------------------------

Expected behaviour:  Use of "Swivel Engine"

------------------------------------------------------------------------------

Current behaviour:  Swivel Engine is banned part by default. Possibly others

------------------------------------------------------------------------------

Steps to reproduce:  Attempt to use Swivel Engine in a career mode game

**Comment by DasSkelett** [comment]
LMP isn't updated for KSP 1.12.2 yet, which added new parts/part revamps. This affects the ground anchor, the Swivel and the Reliant engine.
Dagger will come back from holidays in a few days and might make a new release.

Until then, you could either add the following to the `LMPModControl.xml`:
```xml
<AllowedParts>
     <string>liquidEngine2.v2</string>
    <string>liquidEngine.v2</string>
    <string>groundAnchor</string>
```
