### ISSUE TITLE
Question: Is it possible to start server with vessels pre-populated in orbit?

### ISSUE THREAD

**Issue by rallen10** [LunaMultiplayer/LunaMultiplayer#468]
Just a question, not a direct issue. Sorry this is the best place I can think to post.

I'm new to LMP and I'm trying to figure out if it is possible to start a server with vessels pre-populated in orbit? Alternatively, can you start a server from a single-player saved game state?

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Ubuntu 20.04

------------------------------------------------------------------------------

KSPVersion: 
1.12.1 Making History

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.28.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 
kRPC

**Comment by rallen10** [comment]
Just a friendly bump. Any chance the developers could give insight here?

**Comment by gavazquez** [comment]
There's a button in the LMP options to create a server from a savegame

**Comment by rallen10** [comment]
As a follow-up, I wanted to provide a more comprehensive process that suited my needs
+ First you need to create a single-player saved game. I wanted spacecraft populated into very specific scenarios so I use the Making History expansion pack and created a mission I will call `Hello-Gemini`
+ Start up the mission, then hit `ESC`, and select save game as `hellogemini`
+ Here is a hacky part: you need to copy the saved mission directory that was generated out of the `missions` folder and into the top-level `saves` folder otherwise LMP won't show it as a option for creating a universe
```bash
cp -r KSP_Linux/saves/missions/Hello-Gemini KSP_Linux/saves/
```
+ Then in the main menu open the LMP dialog box -> settings -> "Generate Universe from saved game" -> `Hello-Gemini` (this save won't appear if you don't do the manual copy in the previous step). This should pop up with a notification about generating a KSP_folder/Universe from Hello-Gemini
+ Now you need to manually copy the generated Universe directory in the KSP main folder into the LunaMultiplayer server directory (I made a backup of the existing LunaMultiplayer Universe just in case)
```bash
mv LunaMultiplayer/LMPServer/Universe LunaMultiplayer/LMPServer/Universe.bak/
cp -r KSP_linux/Universe LunaMultiplayer/LMPServer/
```
+ Now when you start the LMP server, it should be from the Hello-Gemini game state:
```bash
cd LunaMultiplayer/LMPServer
sudo dotnet Server.dll   # need sudo because encountered access denied error otherwise
```
