### ISSUE TITLE
MasterServer.exe not respecting /latest.

### ISSUE THREAD

**Issue by Toys0125** [LunaMultiplayer/LunaMultiplayer#471]
Been running a master server of Stable and Nightly using Docker for a while under bloonfallen as he's the host of the box. Had an issue with DNS not resolving ci.app
```
Connecting to luna-masterserver-endpoint.glitch.me (54.162.165.29:443)                                                  │
Connecting to ci.appveyor.com (138.91.141.243:443)                                                                      │
wget: server returned error: HTTP/1.1 404 Not Found
```
correctly and it was fixed once I did a manual wget. 
The config has `rm -f latest 2> /dev/null && wget $LMP_URL && unzip -o latest && cd LMPMasterServer && mono MasterServer.exe -p $PORT -g $HTTP_PORT` no latest set but it reports as being a nightly build. 
```
[20:00:55][LMP]: Starting MasterServer at port: 8700                                                                    │
[20:00:55][LMP]: Listening for GET requests at port: 8701                                                               │
[20:00:55][Error]: You're not listed in the master servers list (https://goo.gl/jgUgU9). Clients/Servers won't see you  │
[20:00:55][Info]: Master server 0.29.0 started! Поехали!
```

**Comment by DasSkelett** [comment]
Did you change the `$LMP_URL` in the Dockerfile? https://luna-masterserver-endpoint.glitch.me/latest is no longer functional as the last stable build has been too long ago and the artifacts are no longer available.
If you used a more recent 0.29.0 nightly build, it explains why `/latest` isn't "working" for you. The auto-update logic doesn't downgrade the existing DLL.

**Comment by Toys0125** [comment]
Okay, then what is required to get the stable build of the master server as I used the dockerfile in the repo.
I eventually changed the docker file where I download the latest artifact from appveyor and build it into the docker image.
But it only has version 0.29 in appveyor.

**Comment by DasSkelett** [comment]
That is a very good question, I honestly don't know, aside from building yourself. Probably nobody bothered setting up a static download source, because the circle of registered master server owners is pretty small, and they update their servers quick enough after new releases where the files are still available in AppVeyor, or just build them themselves.

**Comment by Toys0125** [comment]
Well finally got it built myself and doing a zip add to the docker build instead of it downloading. So I assume the /nightly will still check and update automaticly.
