### ISSUE TITLE
.NET Bundled?

### ISSUE THREAD

**Issue by CuboidRaptor** [LunaMultiplayer/LunaMultiplayer#482]
This isn't really an issue, more of a feature request.

You can bundle .NET in apps, could you do that for LMP?
It might be convienient for people without admin, and I was planning to host this on a server that doesn't natively support C# *or* .NET, so installing it manually would be a heck of a pain.

But, if .NET was stuffed inside of LMP, all these problems would be circumvented.

**Comment by DasSkelett** [comment]
> I was planning to host this on a server that doesn't natively support C# _or_ .NET, so installing it manually would be a heck of a pain.

Are you speaking about a Linux server? If so, there are .NET 5 packets available for download at Microsoft's page. They even host APT repositories, many distros also have it in their standard repositories.

The thing is, as it is right now the releases work for any OS, after installing.NET 5.
If one makes them self-contained, you'll need separate release assets for each OS. Not impossible, but requires some changes in the build system (with which I'm totally unfamiliar with).
