### ISSUE TITLE
Ports are falsely used.

### ISSUE THREAD

**Issue by CuboidRaptor** [LunaMultiplayer/LunaMultiplayer#484]
OS: 
Windows 10

------------------------------------------------------------------------------

KSPVersion: 
1.12.3

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
Newest, 0.28.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: 
BDAMultiplayer for LMP, Tweakscale, Airplane Plus, dependencies.

------------------------------------------------------------------------------

Expected behaviour: 
The Server connects to MasterServer.

------------------------------------------------------------------------------

Current behaviour: 
Constantly complains about how ports are closed, even though they are open. I have made code to find open ports, and I have tried connecting to **all** of them. It doesn't work. Checking afterwards, they are still open.

------------------------------------------------------------------------------

Steps to reproduce: 
Not sure if it'll have the same behaviour on other computers, but change the port number to something random, and it (might?) break.

**Comment by DasSkelett** [comment]
It isn't clear from the issue what problem you are experiencing and what you are trying to do.

> Expected behaviour:
The Server connects to MasterServer.
Current behaviour:
Constantly complains about how ports are closed, even though they are open. I have made code to find open ports, and I have tried connecting to all of them. It doesn't work. Checking afterwards, they are still open.

Who complains? The LMP client? The LMP server? Something else?
When does it complain? What are you trying to achieve? What buttons are you pressing?
Can you share some screenshots of the complaint?

> Steps to reproduce:
Not sure if it'll have the same behaviour on other computers, but change the port number to something random, and it (might?) break.

These steps are useless, unfortunately. Please describe step by step what you are doing, precisely.
What do you do to see the complaint about ports being closed? What port do you change where, to what exactly (random?)

**Comment by DasSkelett** [comment]
Closing due to unresponsiveness of OP
