### ISSUE TITLE
Can't connect to sever

### ISSUE THREAD

**Issue by pubgrub2** [LunaMultiplayer/LunaMultiplayer#489]
- OS: Win 10
- KSP Version: 1.12.3
- LMP version: 0.28.0

[Uploading KSP.log…]()

---

Mods (remember that **mods are not supported**):  

Visual Mods
MechJeb 2
Kerbal Engineer Redux
BDArmory for LMP

---

Expected behaviour:  

I can connect

Current behaviour:  

Handshake already in progress
Can't connect

---

Steps to reproduce:  

I don't know

**Comment by DasSkelett** [comment]
Closing this issue as it doesn't contain any information be able to give help.
@pubgrub2 if you still experience this problem please re-open the issue and provide the following details:
* Does it affect all servers or only a specific one?
* Anything special about your network connection? Mobile network, active VPN...
* Please install the debug build of the client (and if possible server) and upload `KSP.log` and if possible the console output of the server around the time of the connection atttempt
