### ISSUE TITLE
I can't see friend's red position marker. (he can see mine)

### ISSUE THREAD

**Issue by githubUser12352** [LunaMultiplayer/LunaMultiplayer#492]
Background:

- OS: Windows 11
- KSP Version: 1.12
- LMP version (include the build number if you are using a nighly build): 0.28.0.493

---

Mods (remember that **mods are not supported**):  No mods are on the server.

---

Expected behaviour:  
I should be seeing a red marker indicating the other players position. 

Current behaviour:  
I do not see a red marker but my friend does see a red marker indicating my position. I only see a flying plane.

---

Steps to reproduce:  
Join the server.

**Comment by DaltonKirk** [comment]
Hello, this might be due to having that UI setting disabled. I think the hot key is F4 to toggle it on and off.

**Comment by githubUser12352** [comment]
I tried pressing F4 but it didn't work. I solved it by reinstalling the client mod. Now I can see my friend. Thanks anyway!
