### ISSUE TITLE
Idea/Suggestion - Auto sync player's subspace times when not in flight

### ISSUE THREAD

**Issue by DaltonKirk** [LunaMultiplayer/LunaMultiplayer#496]
Not sure if this is a good idea or not. But would it be ok to synchronise the times for each player automatically if no one is in flight? This is just because sometimes we forget to sync and then end up launching rockets in the past quite a lot. This isn't a big deal, just a thought I had and I'm not even sure if it's a good idea.

**Comment by DasSkelett** [comment]
I think this can be unwanted, if the person in the past is waiting for a transfer window or other event that will already have gone by in the future person's subspace.

**Comment by DaltonKirk** [comment]
Yeah that’s a good point. I’m yet to go anywhere that needs a transfer window so that detail slipped my mind!
