### ISSUE TITLE
Disabling the list of banned parts

### ISSUE THREAD

**Issue by MekoNix** [LunaMultiplayer/LunaMultiplayer#498]
I would like to use modded ship parts. For example MechJeb. But on startup I get a message that they are banned (ship parts). Since I don’t know the names of the parts and I don’t want to manually enter them into the config, can I somehow disable the ban list?

**Comment by DasSkelett** [comment]
Please read the wiki: https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Mod-file
Be advised that generating a LMPModControl.xml is preferred over disabling ModControl completely.
