### ISSUE TITLE
WebServer Exposed All Files & Folders Under the LMP Directory

### ISSUE THREAD

**Issue by Fierce-Cat** [LunaMultiplayer/LunaMultiplayer#500]
Background:

- OS: Ubuntu 20.04
- KSP Version: 1.12.2
- LMP version (include the build number if you are using a nighly build): 0.28.0

---

Mods (remember that **mods are not supported**):  

N/A

---

Expected behaviour:  

After opening the website in Config/WebsiteSettings.xml, the port (8900) should only serve json data that allows public access.

Current behaviour:  

Accourding to @littlebroto1, after opening the website in Config/WebsiteSettings.xml, the port (8900) allows access to all files and folders in the server directory, including the GeneralSettings.xml containing the server/admin password.
![Accessed file](https://s1.ax1x.com/2022/05/30/XlVzFO.png)

---

Steps to reproduce:  

1. Set `<EnableWebsite>true</EnableWebsite>` to true in Config/WebsiteSettings.xml,
2. Access [Your Server Address]:8900/Config/GeneralSettings.xml (or other files under the LMP directory)

---

Workaround

Set `<EnableWebsite>` to false.

**Comment by DasSkelett** [comment]
Fix 1: https://github.com/LunaMultiplayer/LunaMultiplayer/commit/89a1ab3ef2f8ca89711d62293a271d85889d0797

**Comment by gavazquez** [comment]
Your solution looks good @DasSkelett 
Do you think I should do a full release of this version?

**Comment by DasSkelett** [comment]
I haven't fully investigated the report about the `/changesettings` command yet, and the screenshot sharing.
Maybe they should be fixed too before releasing a new version.

**Comment by gavazquez** [comment]
I'm not worried about `changesettings ` command as that only works from the main server console. There's no message that can trigger that command from a client, you need to actually type it on the server console

Regarding the screenshot sharing, it only works with png files and only list the files under the screenshot folder

**Comment by DasSkelett** [comment]
Okay, in this case I'd say let's do a release.
