### ISSUE TITLE
Quick Question about mods

### ISSUE THREAD

**Issue by NameLord** [LunaMultiplayer/LunaMultiplayer#502]
Are mods supported for this? and if not then why? whats the reason are not supported?

**Comment by DasSkelett** [comment]
This is explained quite a lot of times in the wikii:
- https://github.com/LunaMultiplayer/LunaMultiplayer/wiki#generic-faq
- https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Mod-support
- https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Mod-file
