### ISSUE TITLE
Cant run the docker image for arm64 (raspberry pi 4)

### ISSUE THREAD

**Issue by ahmedelakkad** [LunaMultiplayer/LunaMultiplayer#507]
Background:

- OS: Raspberry pi lite (64-bit) on raspberry pi 4
- KSP Version:  1.12
- LMP version 0.29
---

Expected behaviour:  

Should be able to run the docker image

Current behaviour:  

The image request is not for arm64 but for amd64 and there is not why to choose arm64 so that it works on rpi

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

---

Steps to reproduce:  

pull and run ghcr.io/lunamultiplayer/lunamultiplayer/server:master on raspiberry pi

**Comment by DasSkelett** [comment]
Hey, can you try `docker.io/dasskelett/lmpserver:multiarch`?
It uses clever cross-compilation, so the impact of arm64 emulation during image build is reduced.
If it works I'll push the updated Dockerfile to the repository and `ghcr.io/lunamultiplayer/lunamultiplayer/server:master` will gain an arm64 version then.

**Comment by ahmedelakkad** [comment]
unfortunately same issue :/  "exec /bin/sh: exec format error" in the container logs.

**Comment by ahmedelakkad** [comment]
oh my bad, it used :latest instead of :multiarch. Thanks a million!
