### ISSUE TITLE
When I click server.exe nothing pops up

### ISSUE THREAD

**Issue by GrumpySpace** [LunaMultiplayer/LunaMultiplayer#512]
Background:

- OS:  Windows 10
- KSP Version:  1.12.2
- LMP version (include the build number if you are using a nighly build): 0.29.0

---

Mods (remember that **mods are not supported**):  None rn bc i cant even set up the server

---

Expected behaviour:  
To be able to click server.exe and to set up server

Current behaviour:  
Nothing is working/happening

---

Steps to reproduce:  
download lmp, put it in folder, try opening server.exe, nothing load up (not even the windows fire wall)

**Comment by Basketing** [comment]
I am having the same issue, .NET is installed yet it still does not work.

**Comment by DasSkelett** [comment]
Make sure you have **.NET 5**, installed, .NET 6 won't work.
Alternatively try the latest nightly build, it comes with .NET bundled and you don't have to install it separately.

https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server
https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/How-to-get-nightly-builds
