### ISSUE TITLE
LMP Server does not have required DLL (hostfxr.dll)

### ISSUE THREAD

**Issue by TangentFoxy** [LunaMultiplayer/LunaMultiplayer#515]
Background:

- OS: Windows 10
- KSP Version: 1.12.4
- LMP version (include the build number if you are using a nighly build): 0.29.0

---

Mods (remember that **mods are not supported**):  

None

---

Expected behaviour:  

Server launches.

Current behaviour:  

Server fails to launch with:

```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [D:\LMPServer\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=5.0.17
```

---

Steps to reproduce:  

1. Download LMP server.
2. Launch LMP server.

Edit: I did install the missing runtime, but this didn't change anything.

**Comment by TangentFoxy** [comment]
In case someone else runs into the same confusion I did:

## *Server* installation instructions are in [Create a server](https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server), not [How to install LMP](https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/How-to-install-LMP)

(I didn't see that the wiki only gives installation instructions for the client and only gives server installation instructions under "Create a server", leading to me not finding the required installation. Additionally, the error message given told me to install the wrong thing, although I do understand that is out of the control of y'all.)

I don't want to recklessly edit the Wiki, but it seems unclear to me. **I saw no instruction on the installation page, and thus assumed simply downloading and unzipping was correct.**

**Comment by DasSkelett** [comment]
> I don't want to recklessly edit the Wiki, but it seems unclear to me. **On the installation page, the only instruction present is to download and unzip the server.** (Edit: I have edited the installation instructions to explicitly point out that finishing installation requires the instructions on creating a server.)

Thanks, I think your change makes it clearer that you are supposed to read the Create-a-server page before proceeding.
