### ISSUE TITLE
the server's .exe file crashes

### ISSUE THREAD

**Issue by IlyaVelikiy** [LunaMultiplayer/LunaMultiplayer#527]
Good day, faced with the problem of launching multiplayer. When you try to run the executive file, the console opens for a second and immediately closes, leaving no logs and other things. The firewall is disabled, nothing should shut down the server. Can you tell me how to solve this problem?
Note: The server crashes at the first start, no downloads occur, just crashes

- OS: Windows 10 20H2
- KSP Version: 1.12
- LMP version: 0.29.0
---

Expected behaviour:  
Server start

Current behaviour:  
Server crash

---

Steps to reproduce:
¯\_(ツ)_/¯ just trying to start the server for the first time

**Comment by DasSkelett** [comment]
You are most likely missing the .NET 5 runtime, please have a look at the setup guide: https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server
