### ISSUE TITLE
Server Console error while trying to connect through Master servers.

### ISSUE THREAD

**Issue by Pict0Cube** [LunaMultiplayer/LunaMultiplayer#53]
------------------------------------------------------------------------------
OS : Ubuntu 14.04
Mono Complete 5.4.1.6
KSPVersion: 1.3.1

------------------------------------------------------------------------------

Expected behaviour: Being able to connect using server menu.

------------------------------------------------------------------------------

Current behaviour: Can't connect through master server (server menu). Server is listed though and running fine when connecting manually (no errors). 

**Server console error message :**
```
[Debug] : Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (0x80004005): Invalid arguments
  at System.Net.Sockets.Socket.SendTo (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEP) [0x00066] in <50d80b08c1a5449282b22aedf03ce925>:0 
  at Lidgren.Network.NetPeer.SendPacket (System.Int32 numBytes, System.Net.IPEndPoint target, System.Int32 numMessages, System.Boolean& connectionReset) [0x00028] in <446bdc015556418abf5208bcb1041e78>:
```0

**Master Server error message :**
```
Master Server Log :
/2017 20:38:31 - NEW SERVER: XX.XX.XX.XX:8800
11/12/2017 20:38:33 - REMOVING SERVER: XX.XX.XX.XX:8800
11/12/2017 20:38:53 - Client requested introduction to nonlisted host!
```
------------------------------------------------------------------------------

Steps to reproduce:  Simply trying to connect using the "server menu". Server is vanilla, fresh installed, mono is up-to-date, config files haven't been modified (except name and amount of players). I'm more thinking about a problem of registration on master server, not on client side.

**Comment by SupperRobin6394** [comment]
@Pict0Cube if you can PM me the IP on Discord I can debug my Master using the website data to see if there's anything wrong on that side.

**Comment by Pict0Cube** [comment]
Dagger already fixed it with .298.
