### ISSUE TITLE
Wont let me join a server

### ISSUE THREAD

**Issue by bblwillzy** [LunaMultiplayer/LunaMultiplayer#530]
Background:

- OS: Windows 11
- KSP Version: 1.12.4
- LMP version (include the build number if you are using a nighly build): 0.29

---

Mods (remember that **mods are not supported**):  

---

Expected behaviour:  

Joining a server

Current behaviour:  

Trying to join servers, it keep saying "Disconnected: Your terrain quality: Default does not match the server quality: High."

---

Steps to reproduce:  

Join a server

**Comment by DasSkelett** [comment]
> it keep saying "Disconnected: Your terrain quality: Default does not match the server quality: High."

It says this for a reason. How about trying to adjust your terrain quality?

**Comment by bblwillzy** [comment]
shoot, i forgot to add it no matter what it wouldnt let me join. i fiddled with all the settings possible and it wouldnt work.
