### ISSUE TITLE
.NET 5 unsupported and complicated to download

### ISSUE THREAD

**Issue by SteelyxYT** [LunaMultiplayer/LunaMultiplayer#532]
Is ot posiable to update the dotnet to a newer version that is actually supported because it's annoying trying to download a unsupported version especially on linux

**Comment by DasSkelett** [comment]
Please try the nightly builds, where this has already been done:
https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/How-to-get-nightly-builds
https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server#lmp-nightlies--0290600
