### ISSUE TITLE
When I try to join a server it stays on "Running"

### ISSUE THREAD

**Issue by Prozoon700-oficial** [LunaMultiplayer/LunaMultiplayer#534]
KSP LOG: (https://github.com/LunaMultiplayer/LunaMultiplayer/files/10404391/KSP.log)

(https://github.com/LunaMultiplayer/LunaMultiplayer/files/10404399/LMPServer.zip)

Background:

- OS: Windows
- KSP Version: 1.12.5.3190
- LMP version (include the build number if you are using a nighly build): 0.29.0

---

Mods (remember that **mods are not supported**):  

No mods.

---

Expected behaviour:  

When I try to join any server (not only mine) the LMP Client stays on running: 
![image](https://user-images.githubusercontent.com/108482805/212139866-e4606444-5003-4683-a34f-9db2ae0e8552.png)

**Comment by DasSkelett** [comment]
If that server isn't in your local network, a private IP address won't work. Use the server list to join, please.
