### ISSUE TITLE
Request: Wildcard allow parts/mods

### ISSUE THREAD

**Issue by Frohrer** [LunaMultiplayer/LunaMultiplayer#546]
This is a feature request. Allow a wildcard to be used in the LMPModControl.xml <AllowedParts>list.
For example: <AllowedParts><string>*</string></AllowedParts>

Alternatively allow disabling the allowed parts check completely.

**Comment by DasSkelett** [comment]
Are you aware of the feature to generate a LMPModControl.xml based on the installed mods through the LMP menu in the game?

> Alternatively allow disabling the allowed parts check completely.

Can you describe what exactly you want to do, which the existing `ModControl` toggle in `GeneralSettings.xml` doesn't cover?

**Comment by Frohrer** [comment]
I was not aware of that feature. If I had read the documentation correctly I would have saved the 15 minutes writing a python script to generate a new xml file by reading the .cfg files in my addon folder. Whoops 😄
