### ISSUE TITLE
Repeated sounds on craft while Flying

### ISSUE THREAD

**Issue by pkmniako** [LunaMultiplayer/LunaMultiplayer#55]
KSP.log: https://pastebin.com/UH4AwyX4
output_log.txt; https://drive.google.com/open?id=1qisEuxehSZznEOTxKIcIUfJ_uI_uxLsu

OS: Windows 10
KSPVersion: 1.3.1
MODS:
    https://github.com/CYBUTEK/KerbalEngineer/releases/tag/1.1.3.0

Expected behaviour: Running Engine Sound Effect
Current behaviour: Running Engine Sound Effect & Engine Startup Sound Effect from time to time
Could not reproduce, but the following information is included:
   RAPIER Engines were used
   Engine were started up with Action Groups
   Stopped engine and reignited with action group while flying.
   3 people in close proximity also flying.

**Comment by gavazquez** [comment]
Probably fixed after the new part sync system
