### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by JeanMarcZimmer** [LunaMultiplayer/LunaMultiplayer#569]
### System:

- OS: Raspbian lite on RPI 4B, bash 5.2.15
- LMP version: Server 0.29.0.574

Mods:  none (and probably with any mod, too)

---

### Error:

Server doesn't find libssl and immediately crashes, with message
```No usable version of libssl was found```

---

### Solution:

install package `libssl1.1`

**Comment by JeanMarcZimmer** [comment]
I posted this just in case someone comes across the same issue and googles it.

**Comment by CNWMakesCode** [comment]
On Debian 12, libssl1.1 isn't available, making it impossible to install.

**Comment by DasSkelett** [comment]
@JeanMarcZimmer @CNWMakesCode The [latest nightly release](https://github.com/LunaMultiplayer/LunaMultiplayer/releases/tag/0.29.0-Draft) should work for you, as it runs on .NET 6, which I believe already supports OpenSSL 3

**Comment by CNWMakesCode** [comment]
> @JeanMarcZimmer @CNWMakesCode The [latest nightly release](https://github.com/LunaMultiplayer/LunaMultiplayer/releases/tag/0.29.0-Draft) should work for you, as it runs on .NET 6, which I believe already supports OpenSSL 3

Dw I already figured it out
