### ISSUE TITLE
Inability to join a server on Mac OS

### ISSUE THREAD

**Issue by AmericanSpy** [LunaMultiplayer/LunaMultiplayer#57]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

------------------------------------------------------------------------------

OS: macOS Sierra

------------------------------------------------------------------------------

KSPVersion: 1.3.1

------------------------------------------------------------------------------

MODS (add link to download them): LMP, MM

------------------------------------------------------------------------------

Expected behaviour: Able to join a server once clicking the left arrow button on the server list

------------------------------------------------------------------------------

Current behaviour: Does nothing after clicking arrow button.

------------------------------------------------------------------------------

Steps to reproduce: Start game, go to servers, click on any running server.

Log: https://drive.google.com/file/d/1C3Mnehd5Jj-88dE6JAi3wFstwSYJJoH5/view?usp=sharing

**Comment by TheHellBox** [comment]
Same on Linux

**Comment by SYZYGY-DEV333** [comment]
same on linux. More detailed bug report filed by myself.

**Comment by gavazquez** [comment]
Same as #58
