### ISSUE TITLE
Will not connect from server list on Linux/Mac OS

### ISSUE THREAD

**Issue by SYZYGY-DEV333** [LunaMultiplayer/LunaMultiplayer#58]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

------------------------------------------------------------------------------

OS: OpenSUSE 64-bit Linux

------------------------------------------------------------------------------

KSPVersion: 1.3.1.1891 (from Steam)

------------------------------------------------------------------------------

MODS (add link to download them): AirplanePlus, Firespitter, LMP, Infernal Robotics, Kerbal Alarm Clock, and ModuleManager.

------------------------------------------------------------------------------

Expected behaviour: When in the Server List, If I click on the little arrow to connect, it should connect, or else give me some sort of error message.

------------------------------------------------------------------------------

Current behaviour: When in the server list, If I click on the little arrow to connect, the server list window disappears, and there is no message on the screen or in the logs about an attempted connection. This leads me to believe that it didn't even try to connect. Also, all the ping values are 9999.  

------------------------------------------------------------------------------

Steps to reproduce: Start KSP; in the LMP window click on "Servers" and then click on the triangle-shaped connect button for any server. The Servers window will disappear and you will not be connected.

NOTE: I could not find an output_log.txt, so I will attach ksp.log.
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1591578/KSP.log)

**Comment by TheHellBox** [comment]
Same problem

**Comment by gavazquez** [comment]
Happens the same in MAC OS.

I tracked the error to the code that gets the subnet mask. I think that it's fixed in commit [https://github.com/LunaMultiplayer/LunaMultiplayer/commit/be1ff67d3d4f3a00e85072909f23964a52ce2230](https://github.com/LunaMultiplayer/LunaMultiplayer/commit/be1ff67d3d4f3a00e85072909f23964a52ce2230)

In order to test it you need to have latest version and run the debug version and a master server + server

**Comment by gavazquez** [comment]
Tested by @TheHellBox 

Should work on latest nightly version
