### ISSUE TITLE
stuck saying i was warping and it went down hill from there

### ISSUE THREAD

**Issue by Brute1984** [LunaMultiplayer/LunaMultiplayer#60]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1649893/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1649894/output_log.txt)

------------------------------------------------------------------------------
windows 10
OS: 

------------------------------------------------------------------------------
latest from steam
KSPVersion: 

------------------------------------------------------------------------------
latest mechjeb
MODS (add link to download them): 

------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------
![screenshot 2018-01-21 10 54 08](https://user-images.githubusercontent.com/35662206/35196045-e7abdfd2-fe9a-11e7-8d2e-3217df669390.png)
![screenshot 2018-01-21 10 53 04](https://user-images.githubusercontent.com/35662206/35196052-fb46a9fa-fe9a-11e7-8a3c-6124ce9e59ae.png)

It started with my vessel getting stuck saying i was warping .. the server stopped updating info from clients .. i restarted server and rejoined the server and started getting errors as well as ships being renamed.. could no longer play on the server.. had to reinstall server..

Current behaviour: 

------------------------------------------------------------------------------

Steps to reproduce:  im not really sure how this happened but i did see it happen 2 other times..

**Comment by Brute1984** [comment]
asteroids are disabled

**Comment by gavazquez** [comment]
I will try it in my computer but without clear steps I don't think I will be able to fix it...

Also, were you using the latest version from github or a nightly build from appveyor?

**Comment by Brute1984** [comment]
9.388.. i understand .. its just very hard to pinpoint.. i just tried to recreate it and couldn't.. but i didn't have another player in the server either .. and things are alot different when there is another player

**Comment by Brute1984** [comment]
a whole lot of locking and unlocking issues tho on a separate problem that always ends up breaking our game when we play

**Comment by gavazquez** [comment]
OK will try to see if the lock system can be more clear so there are not so many trials and errors

**Comment by Brute1984** [comment]
that would be great thank you

**Comment by gavazquez** [comment]
OK fixed the lock system so there's less spamming now.
Also fixed vessel renaming
