### ISSUE TITLE
locked up on syncing vessels

### ISSUE THREAD

**Issue by Brute1984** [LunaMultiplayer/LunaMultiplayer#61]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1650230/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1650231/output_log.txt)

Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
windows 10
------------------------------------------------------------------------------

KSPVersion: 
latest from steam
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
9.388
------------------------------------------------------------------------------

MODS (add link to download them): 
latest mechjeb
------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 
hanging up on syncing vessels when i rejoin my server .. we see this alot after playing for awhile .. i think its when vessels start getting failure to lock and unlock issues.. 
------------------------------------------------------------------------------

Steps to reproduce: 
play with somebody for an hour making space stations or anything out in space and you will see it and more

**Comment by SupperRobin6394** [comment]
Are you playing in Sandbox mode?

**Comment by Brute1984** [comment]
yes

**Comment by Brute1984** [comment]
[vesselsAndcraft.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1650312/vesselsAndcraft.zip)

**Comment by gavazquez** [comment]
I think that the error was related to the file patching bug.
Now vessels have the correct line breaks so they should be correctly read by KSP.

Also I allowed "compression" for vessel data so if you have compression enabled it should transfer the vessels faster
