### ISSUE TITLE
error with vessels sync issue? 

### ISSUE THREAD

**Issue by Brute1984** [LunaMultiplayer/LunaMultiplayer#63]
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1658031/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1658033/output_log.txt)
[Vessels.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1658036/Vessels.zip)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
windows 10
------------------------------------------------------------------------------

KSPVersion: 
latest from steam
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
9.411
------------------------------------------------------------------------------

MODS (add link to download them): 

------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 
played for maybe an hour.. i had 3 vessels out in space.. i quit and rejoined the server and all a sudden i had 50 some vessels to load and when i went to tracking station i had around 15 vessels in space and they were all old vessels .. in previous stages or just different places.. also some where flashing in the tracking station.. as in .. one second you see them one second you don't .. 
------------------------------------------------------------------------------

Steps to reproduce:

**Comment by Brute1984** [comment]
its almost like the game created the whole vessel again on different stages or something.. instead of saving the vessel it makes a copy or something.. you should see something in the vessel files.. 3 of them are flashing in tracking station so there should be an error in the vessel file i would think

**Comment by gavazquez** [comment]
Hi!

I tried to reproduce it but I couldn't do it as I lack the correct time from your server.
I will edit the issue template to show it but in order to reproduce your issue, I need the full "UNIVERSE" folder as it contains also the scenario data.

Still I will to play today around and see if I manage to reproduce it.

**Comment by gavazquez** [comment]
OK I managed to kind of reproduce it.

THe issue was that some vessels were crashing against Kerbin and since you didn't had the UpdateLock (you get the update lock when you are within load distance) you coudn't send "RemoveVessel" messages to the server. Now that is fixed

Also some vessels had orbits with all values as "0". I also protected against that error.

This doesn't mean that all errors are fixed, you had a ton of vessels around and I don't know why you had so many of them since you started with only 3

**Comment by Brute1984** [comment]
[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1659422/Universe.zip)
here is my universe folder.. when i get home i will remove asteroids and do some launching and just watch the vessels folder to see when it starts creating extras

**Comment by Brute1984** [comment]
also what about when you revert .. does it delete the old vessel?

**Comment by gavazquez** [comment]
Reverting should delete the old vessel but the debris is another story... Perhaps that could be the issue?

Did you reverted after creating many debris?

**Comment by Brute1984** [comment]
if i had a failed launch when it was going to crash back to earth , yeah

**Comment by gavazquez** [comment]
Hmmm it's quite difficult to know what debris belongs to what original vessel but I will see what can be done. The other solution would be to avoid the creation of debris at all....

**Comment by Brute1984** [comment]
i did also have more then the set value for asteroids as well so whatever it is effects them too

**Comment by gavazquez** [comment]
OK I added a system to detect if you revert. If that happens then it removes your old vessel and it's debris. Hopefully this will solve most of the issues....
