### ISSUE TITLE
Server exception deserealizing ModMsgData

### ISSUE THREAD

**Issue by jrodrigv** [LunaMultiplayer/LunaMultiplayer#64]
Hi Dagger,

I have been playing with the current Master and have errors on the Server side when trying to deseralize the ModMsgData that I'm sending. 

This was working before so I was wondering if maybe I have to change something on BDArmory.

The exception that I'm getting is:

Error deserializing message! System.NullReferenceException: Object reference not set to an instance of an object.

_e.Data.ModMsgData.InternalDeserialize(NetIncomingMessage lidgrenMsg, Boolean dataCompressed) in LunaMultiplayer-master\Common\Message\Data\ModMsgData.cs:line 54
   at LunaCommon.Message.Base.MessageData.Deserialize(NetIncomingMessage lidgrenMsg, Boolean dataCompressed) 
in LunaMultiplayer-master\Common\Message\Base\MessageData.cs:line 52
   at LunaCommon.Message.Base.FactoryBase.Deserialize(NetIncomingMessage lidgrenMsg, Int64 receiveTime) in LunaMultiplayer-master\Common\Message\Base\FactoryBase.cs:line 28
   at Server.Server.MessageReceiver.DeserializeMessage(NetIncomingMessage msg)  
in LunaMultiplayer-master\Server\Server\MessageReceiver.cs:line 80_

If I debug the server I can see the the problem is related with the Data property of the ModMsgData  that contains a null value.  However, I have also performed a debug on the Client code and it seems that the Data property is not null when it is sent.

(Find attached the settings that I'm using for the server)
[Settings.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1661896/Settings.txt)

 And this is the code I'm using to send the messages:

` BdaMessage messageToSend = new BdaMessage() {Type = message.GetType(), Content = message};

            SystemsContainer.Get<ModApiSystem>().SendModMessage(ModName, BinaryUtils.Serialize(messageToSend), true);`

Regards,
Jesus

**Comment by gavazquez** [comment]
Sorry Jesus, I made a mistake and the field "Data" was not initialized.

Please make sure to fill up both NumBytes and Data fields as that array is being reused to reduce the GC allocations. Therefore, do not use Data.length
