### ISSUE TITLE
Warping in Kerbal Space Center or Tracker then trying to fly your ship causes it to explode

### ISSUE THREAD

**Issue by antonpersson99** [LunaMultiplayer/LunaMultiplayer#67]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1675368/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1675371/output_log.txt)
[LMPServer Univers and Config.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1675375/LMPServer.Univers.and.Config.zip)
[LMPModControl.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1675376/LMPModControl.txt)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.3.1.1981

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.0.10

------------------------------------------------------------------------------

MODS (add link to download them): Use this https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1226-guiana/ and this
[My mods.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1675395/My.mods.zip) to get my whole modlist

------------------------------------------------------------------------------

Expected behaviour: Ship will not explode

------------------------------------------------------------------------------

Current behaviour: Ship explodes

------------------------------------------------------------------------------

Steps to reproduce: Fly up to orbit with something, go back to the space center, go to the tracking station then warp for a half-a-year to a year, choose your ship and press fly.

**Comment by gavazquez** [comment]
Not reproduceable on version 0.0.10.483 nightly:

![image](https://user-images.githubusercontent.com/12727761/35742727-adf18c42-083b-11e8-98da-62008d58367f.png)
