### ISSUE TITLE
Error regarding VesselPositionMsgData Message

### ISSUE THREAD

**Issue by MrAshieB** [LunaMultiplayer/LunaMultiplayer#78]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 
Windows 10
------------------------------------------------------------------------------

KSPVersion: 
1.3.1.1891
------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.1.12.587
------------------------------------------------------------------------------

MODS (add link to download them): 
MechJeb - https://kerbal.curseforge.com/projects/mechjeb
------------------------------------------------------------------------------

Expected behaviour: 
Connect to server with no issues
------------------------------------------------------------------------------

Current behaviour: 
Connect to server, other players get disconnected with error;
[14:37:57][Debug] : MK3424 sent Connection end message, reason: Error handling LunaCommon.Message.Data.Vessel.VesselPositionMsgData Message
------------------------------------------------------------------------------

Steps to reproduce: 
Connect to server with someone else already connected

There is no output_log.txt file
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1716661/KSP.log)
[Server Logs.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1716663/Server.Logs.zip)
[MK3424 log.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1716737/MK3424.log.zip)

**Comment by gavazquez** [comment]
Checked that bug. It was fixed on commit:
https://github.com/LunaMultiplayer/LunaMultiplayer/commit/4407dbd25539fa4fc5e5c50cf3cf596c267cdeae

Get latest nighlty to have it fixed
