### ISSUE TITLE
THIS IS A EXACT REPLICA OF THE DARK MULTIPLAYER MOD, IT LOOKS THE SAME

### ISSUE THREAD

**Issue by diveyez** [LunaMultiplayer/LunaMultiplayer#80]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: 

------------------------------------------------------------------------------

KSPVersion: 

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 

------------------------------------------------------------------------------

MODS (add link to download them): 

------------------------------------------------------------------------------

Expected behaviour: 

------------------------------------------------------------------------------

Current behaviour: 

------------------------------------------------------------------------------

Steps to reproduce:

**Comment by TheHellBox** [comment]
First, please, give an issue. Like bad sync or something like that. Second: LMP works a lot better, also that is not a REPLICA, that a fork of DMP. Third: Do not spam in issues, please

**Comment by godarklight** [comment]
I've talked to them and explained I wanted a fork of DMP for ages. And I'm helping LMP because they've got a better system underneath. I'm closing this, do not worry about it, it's a good thing :P

**Comment by njbrown09** [comment]
lol OP you are a moron
