### ISSUE TITLE
Duplicating vessels every time I revert to hangar - one player on a home server

### ISSUE THREAD

**Issue by garemoko** [LunaMultiplayer/LunaMultiplayer#88]
OS: sever - windows 10, client - macOS 10.13.3 (High Sierra)

------------------------------------------------------------------------------

KSPVersion: 1.3.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.1.13
------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: When I revert flight, the vessel should be removed. When I recover a vessel, the vessel should be removed

------------------------------------------------------------------------------

Current behaviour: Whenever I revert a flight the vessel doesn't get removed from the server so I'm ending up with lots and lots of duplicate vessels lying around. I have been able to recover them before but today when i connected I tried to recover everything that apparently got created last time I played and they just reappear after recovering them. 

------------------------------------------------------------------------------

Other information: I set up the server recently on my local network for myself and my daughter to play. So far only I have played by myself. I have not put anything in orbit yet and mostly have just been testing around the KSC. 

Is there any config I can try?

**Comment by garemoko** [comment]
[Config.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1753155/Config.zip)

**Comment by garemoko** [comment]
This appears to relate to using the Master warp setting. I deleted my universe folder to reset the server and change the config to Subspace warp and now can't replicate the issue.

**Comment by garemoko** [comment]
Scratch that. It's still happening. Seems to just be around the KSC so i turned on the KSC nuke to 5 minutes. Not sure what this does but maybe it will clear out the vessels. 

By the way, I have a LOT of vessels in the universe folder. Are these all asteroids? Would turning off asteroids make connecting faster? Is there a setting for that?

**Comment by gavazquez** [comment]
there were several bugs on latest stable version. Try with 0.2 as it has a huge cleanup of all the code

**Comment by garemoko** [comment]
Thanks! RE "Kerbals in EVA should work fine now and not become spaghetti monsters" I saw that one too!

Would you recommend tossing the universe and starting again, or is the new version compatible? 

By the way, I did find the setting for turning astroids off and that stopped new one generating and made loading vessels much faster.

**Comment by gavazquez** [comment]
You'll have to clean the universe as vessels now are in XML format. Also made a hotfix release because master servers were failing

**Comment by garemoko** [comment]
Ok. I can't test this week but will try it next week and let you know if this is resolved.
