### ISSUE TITLE
Malwarebytes periodically removes LMP `Server.exe` as ransomware?

### ISSUE THREAD

**Issue by d4rkd0s** [LunaMultiplayer/LunaMultiplayer#90]
Windows 10, latest
Malwarebytes Premium Latest
LMP Server 0.1.13

![image](https://user-images.githubusercontent.com/2348814/36650648-c2bcf9da-1a61-11e8-9349-3991fa6c4cfc.png)

Very odd, trying to look into it with Malwarebytes

**Comment by gavazquez** [comment]
I think it has to do with the heuristics but there's no malware inside ;)
Perhaps if the .exe was signed it woudn't be so supsicious for AV... will look into it but a good signing certificate (EV) can be expensive....

**Comment by d4rkd0s** [comment]
@gavazquez Thanks, will close this, I wanted something on record, also sent to Malwarebytes so they can look at it and determine the false positive.
