### ISSUE TITLE
How Do I enable collsions for craft

### ISSUE THREAD

**Issue by Toxici11i** [LunaMultiplayer/LunaMultiplayer#92]
Hey guys, new host here.
I have a server setup, me and two friends are playing.
We are running a slightly combat based server (stock) And would like to know how to enable collisions, since they arent working atm (we just phase through eachother) Any and all advice will help, thanks

**Comment by gavazquez** [comment]
That's not a supported feature.
Still if you want to do it at your own risk (we don't give support for that) you can do that by disabling the "Vessel immortal system" in the "Systems" button on a debug build.
You can access that button on the status window by pressing "Systems"
