### ISSUE TITLE
[Website] Include release dates on Changelog page

### ISSUE THREAD

**Issue by JohannesMP** [LunaMultiplayer/LunaMultiplayer#94]
Currently the changelogs on the [official website](http://lunamultiplayer.com/changelog) do not include release dates.

Since text appears do be markdown that has not been rendered, I am assuming you are simply pulling from the github releases data, so it should be easy to also grab the release date and just append that.

Also, you should really markdown-ify the description again so it has the correct formatting :)

**Comment by gavazquez** [comment]
I'll comment it to robin and leave it in his hand as he's the responsible of the web

**Comment by JohannesMP** [comment]
is there a public repo for the website?

**Comment by gavazquez** [comment]
unfortunately not, you can contact with "Robin" and help him on the discord chat though

**Comment by SupperRobin6394** [comment]
@JohannesMP you're correct on the Github Releases data part, I simply pull it from GitHub and format it (PHP).
I'll add the dates to the releases, shouldn't be too hard.

- Robin

**Comment by SupperRobin6394** [comment]
Done, date has been added
