### ISSUE TITLE
Player Disconnect - EAS-1 External Command Seat - Bug

### ISSUE THREAD

**Issue by Sladernimo** [LunaMultiplayer/LunaMultiplayer#95]
Player getting disconnected when trying to get Kerbal into EAS-1 External Command Seat.

LMP Message: Disconnected: Connection Error: Object reference not set to an instance of an object.

Happens when using Stock Aeris A3 with added external seat on top.
Doesnt happen with custom build test cars (included in universe at runway).

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: WIN7 x64

------------------------------------------------------------------------------

KSPVersion: 1.4.0.2077

------------------------------------------------------------------------------

LMP version: 0.3.26 Debug

------------------------------------------------------------------------------

MODS (add link to download them): No mods used ...

------------------------------------------------------------------------------

Expected behaviour:
-Getting Kerbals into EAS-1 External Command Seat without disconnecting ...

------------------------------------------------------------------------------

Current behaviour: 
-Player getting disconnected when trying to get Kerbal into EAS-1 External Command Seat.
-Happens when using Stock Aeris A3 with added external seat on top.

------------------------------------------------------------------------------

Steps to reproduce: 
-Start Aeris A3 with added EAS-1 External Command Seat on top.
-Try to get Kerbal into EAS-1 External Command Seat.

**Comment by Sladernimo** [comment]
Attached logs and universe ...

[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1810960/output_log.txt)

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1810961/KSP.log)

[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1810963/Universe.zip)

**Comment by gavazquez** [comment]
The log doesn't contain the error. Have you attached the correct log?

**Comment by Sladernimo** [comment]
Yes think I did. I just reproduced the bug to attach files again. Also added lmpserver log:

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1811029/KSP.log)

[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1811030/output_log.txt)

[lmpserver 2018-03-14 13-28-50.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1811031/lmpserver.2018-03-14.13-28-50.log)

[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1811032/Universe.zip)

**Comment by Sladernimo** [comment]
Just updated to KSP 1.4.1 and LMP 0.3.27.
On trying to reproduce the bug, the player doesn't get disconnected anymore, instead the kerbal is dublicated when trying to get into EAS-1 External Command Seat.

**Comment by gavazquez** [comment]
Yes.... I think it's not going to be an easy thing....

**Comment by Sladernimo** [comment]
We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard ;)
